- model_downloader/downloader.py
- model_downloader/list_topologies.yml
> added new several features and models

- intel_models/index.md
- intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-0230.md
- intel_models/resnet50-binary-0001/description/resnet50-binary-0001.md
Models version: 1be69775597a1735ee1b2ffd524a291448c27731
Tools version: af51d62f575306064605c7dc70e2ad7773122ed5
> Models for R1'19 including INT8 models

- demos/smart_classroom_demo/include/face_reid.hpp
- demos/smart_classroom_demo/include/smart_classroom_demo.hpp
- demos/smart_classroom_demo/main.cpp
- demos/smart_classroom_demo/src/action_detector.cpp
- demos/smart_classroom_demo/src/detector.cpp
- demos/smart_classroom_demo/src/reid_gallery.cpp
- demos/smart_classroom_demo/src/tracker.cpp
Added Face Registration interface.
@snosov1 @LeonidBeynenson @sovrasov @evgeny-izutov @vmatveic
> [SAMPLES] Smart Class Room: Added face registration interface

- model_downloader/downloader.py
If we fail to read the cache, we can still download the needed file directly.
If we fail to update the cache, that doesn't affect the output of
the downloader, so we can ignore it.
These changes make the downloader more resilient to network connectivity issues
(in case when the cache is on a remote FS) and enable its usage with read-only
cache directories.
> model_downloader: Tolerate cache access errors

- model_downloader/common.py
- model_downloader/downloader.py
The plan is to use this module in another tool that will convert the downloaded models into the Inference Engine format. I also took the opportunity to add more comprehensive config validation.
> model_downloader: Factor out input validation into a separate module

- README.md
- model_downloader/README.md
- model_downloader/common.py
- model_downloader/converter.py
- model_downloader/license.txt
~Also, move the model downloader and the new tool under `tools/automation` and call them the OMZ automation tools.~
> Add a tool for converting downloaded models

- model_downloader/common.py
- model_downloader/downloader.py
- model_downloader/list_topologies.yml
This eliminates a lot of information duplication within the config file,
as the different variants are the same in everything but the files.
> model_downloader: merge different precision variants of the same model

- demos/smart_classroom_demo/create_list.py
> [smart classroom demo] Fix generation of gallery description

- demos/crossroad_camera_demo/models.lst
- demos/human_pose_estimation_demo/models.lst
- demos/interactive_face_detection_demo/models.lst
- demos/multichannel_demo/models.lst
- demos/object_detection_demo_ssd_async/models.lst
- demos/pedestrian_tracker_demo/models.lst
- demos/python_demos/3d_segmentation_demo/models.lst
- demos/python_demos/action_recognition/models.lst
- demos/python_demos/instance_segmentation_demo/models.lst
- demos/python_demos/object_detection_demo_ssd_async/models.lst
- demos/python_demos/segmentation_demo/models.lst
- demos/security_barrier_camera_demo/models.lst
- demos/segmentation_demo/models.lst
- demos/smart_classroom_demo/models.lst
- demos/super_resolution_demo/models.lst
- demos/text_detection_demo/models.lst
These will enable users to automatically download all models that a demo needs.
It might also aid other automation tasks.
> Add a list of supported models to (almost) every demo

- intel_models/single-image-super-resolution-1032/description/single-image-super-resolution-1032.md
- intel_models/single-image-super-resolution-1033/description/single-image-super-resolution-1033.md
The documentation was reporting wrong reference performance values.
> Fixed issue with performance values for SR models

- tools/downloader/list_topologies.yml
This will make the diff easier to understand when the list of models is updated for the next release.
> list_topologies.yml: Alphabetize Intel models

- tools/downloader/list_topologies.yml
Most models, that is. Some are still unavailable due to known bugs.
> Add R2 models to the model downloader config

- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/postprocessor/nms.py
fix postprocessing for person-detection-action-recognition models family.
> Accuracy Checker: fix supported types for nms

- intel_models/inceptionv3-int8-sparse-v1-tf-0001/description/inceptionv3-int8-sparse-v1-tf-0001.md
- intel_models/inceptionv3-int8-sparse-v2-tf-0001/description/inceptionv3-int8-sparse-v2-tf-0001.md
- intel_models/inceptionv3-int8-tf-0001/description/inceptionv3-int8-tf-0001.md
- intel_models/mobilenetv2-int8-sparse-v1-tf-0001/description/mobilenetv2-int8-sparse-v1-tf-0001.md
- intel_models/mobilenetv2-int8-sparse-v2-tf-0001/description/mobilenetv2-int8-sparse-v2-tf-0001.md
- intel_models/mobilenetv2-int8-tf-0001/description/mobilenetv2-int8-tf-0001.md
- intel_models/resnet-50-int8-sparse-v1-tf-0001/description/resnet-50-int8-sparse-v1-tf-0001.md
- intel_models/resnet-50-int8-sparse-v2-tf-0001/description/resnet-50-int8-sparse-v2-tf-0001.md
- intel_models/resnet-50-int8-tf-0001/description/resnet-50-int8-tf-0001.md
- intel_models/resnet50-binary-0001/description/resnet50-binary-0001.md
Standardize documentation regarding accuracy metrics
> Standardize documentation regarding accuracy metrics

- demos/README.md
- demos/gaze_estimation_demo/README.md
- demos/mask_rcnn_demo/README.md
- demos/object_detection_demo_faster_rcnn/README.md
- demos/segmentation_demo/README.md
- demos/smart_classroom_demo/README.md
- demos/super_resolution_demo/README.md
- demos/text_detection_demo/README.md
Added notes about lack of support for some topologies on Myriad/HDDL
> Demo docs myriad update

- demos/object_detection_demo_ssd_async/main.cpp
- demos/text_detection_demo/main.cpp
- demos/text_detection_demo/src/cnn.cpp
I cannot build demos with current dldt release branch without that fixes
> demos: include missing <chrono>

- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
@IRDonch, please take a look. 
P.S. Internal validation pipeline passed.
> Accuracy Checker: fix cpu_extension search for Mac OS

- tools/accuracy_checker/accuracy_checker/adapters/mask_rcnn.py
previous variant does not assume not aspect ratio resize and it gives wrong results for instance-segmentation-security-0050
> accuracy checker fix postprocessing for instance segmentation

- tools/downloader/license.txt
- tools/downloader/list_topologies.yml
> Update license.txt and fix some errors in it

- demos/README.md
Fixed link to the Security Barrier Camera Demo
> Fixed link

- demos/README.md
- demos/crossroad_camera_demo/README.md
- demos/gaze_estimation_demo/README.md
- demos/human_pose_estimation_demo/README.md
- demos/interactive_face_detection_demo/README.md
- demos/mask_rcnn_demo/README.md
- demos/pedestrian_tracker_demo/README.md
- demos/security_barrier_camera_demo/README.md
- demos/security_barrier_camera_demo/security_barrier_camera_demo.hpp
- demos/segmentation_demo/README.md
- demos/smart_classroom_demo/README.md
- demos/super_resolution_demo/README.md
As Maria is unavailable, I made all the fixes from https://github.com/opencv/open_model_zoo/pull/240 in current merge request.
> added more comments to demo

- demos/crossroad_camera_demo/main.cpp
Added checks  in per-layer performance statistics print option
> fix potential crash in crossroad_camera_demo

- README.md
Also, replace the dot with a space, because there isn't supposed to be a dot there.
> README.md: Update the stable release icon

- demos/text_detection_demo/main.cpp
I was referring to `object_detection_demo_ssd_async`.
> text_detection_demo: align verbosity

- demos/python_demos/action_recognition/README.md
- demos/python_demos/action_recognition/action_recognition.py
- demos/python_demos/action_recognition/action_recognition_demo/result_renderer.py
- demos/python_demos/action_recognition/action_recognition_demo/steps.py
enable capturing from camera
wait for Esc or q
fix misspelled fps->ms
should be merged after https://github.com/opencv/open_model_zoo/pull/229
> action_recognition: fixes

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/nlp.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/wmt.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/machine_translation.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/preprocessor/nlp_preprocessors.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/nlp_representation.py
Changes necessary for enabling GNMT model in OpenVINO validation
> Accuracy Checker: supports Neural Machine Translation

- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/accuracy_checker/utils.py
--has_background False works incorrectly due to type casting (False is string and not empty string to bool casting gives always True)
This PR fix this porblem for annotation conversion via command line
> Accuracy Checker: fix bool args in command line

- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
These changes fix problem with running gaze estimation model
> AC: fix complex data reader construction

- tools/accuracy_checker/accuracy_checker/annotation_converters/brats.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar10.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cityscapes.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/detection_opencv_storage.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/icdar.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/imagenet.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/lfw.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/market1501.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/mars.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/mnist.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/ncf_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/sample_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/vgg_face_regression.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/wider.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/wmt.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/utils.py
- tools/accuracy_checker/tests/test_dataset.py
- tools/accuracy_checker/tests/test_dlsdk_launcher.py
Feature request from DL Workbench
TO DO:
> Accuracy Checker: check dataset content

- tools/downloader/list_topologies.yml
Add --reverse_input_channels flag
> Fix densenets conversion params

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/common_semantic_segmentation.py
- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
- tools/accuracy_checker/accuracy_checker/utils.py
general converter for semantic segmentation without bounding for a specific dataset.
> AC: generalized converter for semantic segmentation

- demos/common/samples/args_helper.hpp
- demos/security_barrier_camera_demo/README.md
- demos/security_barrier_camera_demo/main.cpp
- demos/security_barrier_camera_demo/security_barrier_camera_demo.hpp
Functions in `args_helper.hpp` were copied almost without changes from `benchmark_app`.
> Security barrier camera update multi device and fps

- demos/common/samples/args_helper.hpp
- demos/multichannel_demo/fd/README.md
IP cameras through RTSP protocol support added.
> Added IP-cameras support (RTSP protocol), ReadMe fixed.

- tools/downloader/common.py
> Miscellaneous improvements to the downloader

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_object_detection.py
this converter will cover all object detection tasks in pre-commit CI
> AC:  supproted CVAT annotation format for Object Detection task 

- models/intel/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.md
Reference metric values updated using values obtained in accuracy checker tool on source model:
model: vehicle-license-plate-detection-barrier-0106
launcher: tf
device: CPU
dataset: bitvehicle_dataset
OpenCV version: 4.1.1-openvino
9850 objects processed in 2957.084 seconds
map@vehicle: 0.9988170311234137 
map@plate: 0.9942246211244122 
map@mean: 0.9965208261239129
> Update reference metric values for vehicle-license-plate-detection-barrier-0106

- tools/downloader/README.md
- tools/downloader/converter.py
The intended primary user of this is DL Workbench; however, the option is general enough to be of use to others, as well.
> tools/downloader/converter.py: add an option to specify extra MO args

- tools/downloader/common.py
Also, display deserialization errors in a friendlier way. See the commit messages for details.
> tools/downloader: add more config file validation

- models/public/octave-se-resnet-50-0.125/model.yml
- models/public/octave-se-resnet-50-0.125/octave-se-resnet-50-0.125.md
- tools/downloader/license.txt
In addition to another OctaveNets ([PR 282](https://github.com/opencv/open_model_zoo/pull/282))
> Added octave-se-resnet-50 with alpha=0.125

- tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_age_gender_recognition.py
- tools/accuracy_checker/accuracy_checker/postprocessor/normalize_landmarks_points.py
- tools/accuracy_checker/configs/age-gender-recognition-retail-0013.yml
- tools/accuracy_checker/configs/emotions-recognition-retail-0003.yml
- tools/accuracy_checker/configs/face-detection-retail-0044.yml
- tools/accuracy_checker/configs/facial-landmarks-35-adas-0002.yml
- tools/accuracy_checker/configs/inceptionv3-int8-sparse-v1-tf-0001.yml
- tools/accuracy_checker/configs/inceptionv3-int8-sparse-v2-tf-0001.yml
- tools/accuracy_checker/configs/inceptionv3-int8-tf-0001.yml
- tools/accuracy_checker/configs/mobilenetv2-int8-sparse-v1-tf-0001.yml
- tools/accuracy_checker/configs/mobilenetv2-int8-sparse-v2-tf-0001.yml
- tools/accuracy_checker/configs/mobilenetv2-int8-tf-0001.yml
- tools/accuracy_checker/configs/octave-se-resnet-50-0.125.yml
- tools/accuracy_checker/configs/person-attributes-recognition-crossroad-0230.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-0005.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-0006.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-teacher-0002.yml
- tools/accuracy_checker/configs/person-detection-raisinghand-recognition-0001.yml
- tools/accuracy_checker/configs/person-detection-retail-0002.yml
- tools/accuracy_checker/configs/person-detection-retail-0013.yml
- tools/accuracy_checker/configs/resnet-50-int8-sparse-v1-tf-0001.yml
- tools/accuracy_checker/configs/resnet-50-int8-sparse-v2-tf-0001.yml
- tools/accuracy_checker/configs/resnet-50-int8-tf-0001.yml
- tools/accuracy_checker/configs/vehicle-attributes-recognition-barrier-0039.yml
- tools/accuracy_checker/configs/vehicle-license-plate-detection-barrier-0106.yml
- tools/accuracy_checker/dataset_definitions.yml
> AC: added new configs

- tools/accuracy_checker/accuracy_checker/metrics/hit_ratio.py
'origin/ncf_iterr_issue'.
To fix the ncf iters issue as the lenght of pred_per_user[user] varies.
By shide.dong@intel.com
Sep. 11th, 2019
Changes to be committed:
modified:   tools/accuracy_checker/accuracy_checker/metrics/hit_ratio.py
> Ncf iter issue

- tools/downloader/README.md
- tools/downloader/downloader.py
resolves https://github.com/opencv/open_model_zoo/issues/308
> --precisions flag for downloader.py

- demos/README.md
- demos/smart_classroom_demo/README.md
> Smart Classroom Demo fix

- tools/accuracy_checker/accuracy_checker/dataset.py
now model evaluator is able reset annotations after postprocessing
> AC: fix reset annotation

- demos/smart_classroom_demo/src/reid_gallery.cpp
Add a comment concerning one assert in smart classroom demo
> Add comment to smart classroom demo

- models/public/googlenet-v3-pytorch/model.yml
- models/public/mobilenet-v2-pytorch/model.yml
- models/public/resnet-50-pytorch/model.yml
- tools/downloader/common.py
- tools/downloader/converter.py
Implementation of [this](https://github.com/opencv/open_model_zoo/pull/392#discussion_r329005443) idea.
> Conversion to ONNX  is unified

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/segmentation.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/semantic_segmentation.py
Also slightly adopted `dice_index` metric
> AC: supported single class semantic segmentation

- tools/accuracy_checker/accuracy_checker/launcher/__init__.py
- tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher.py
- tools/accuracy_checker/tests/test_pytorch_launcher.py
Pytorch requires a lot of time for loading, even it does not used.
It affects common working pipeline when Pytorch installed in the python environment
> AC: Pytorch Launcher import

- demos/python_demos/face_recognition_demo/README.md
- demos/python_demos/face_recognition_demo/face_identifier.py
- demos/python_demos/face_recognition_demo/face_recognition_demo.py
- demos/python_demos/face_recognition_demo/faces_database.py
Currently by default hungarian assignment(linear_sum_assignment) is used when do face match.   Some customers prefer using "mininum cosion distance" for face matching in some use cases.  This pull request created to add this option.
> add match algorithm option support for face matching

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/pipeline_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/average_meter.py
- tools/accuracy_checker/accuracy_checker/metrics/character_recognition.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py
- tools/accuracy_checker/accuracy_checker/metrics/detection.py
- tools/accuracy_checker/accuracy_checker/metrics/metric.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
- tools/accuracy_checker/accuracy_checker/metrics/question_answering.py
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/metrics/semantic_segmentation.py
- tools/accuracy_checker/accuracy_checker/metrics/text_detection.py
- tools/accuracy_checker/accuracy_checker/representation/regression_representation.py
- tools/accuracy_checker/tests/test_metric_evaluator.py
- tools/accuracy_checker/tests/test_model_evaluator.py
- tools/accuracy_checker/tests/test_presenter.py
- tools/accuracy_checker/tests/test_regression_metrics.py
- tools/accuracy_checker/tests/test_segmentation_metrics.py
> AC: per data instance metrics

- demos/pedestrian_tracker_demo/main.cpp
- demos/pedestrian_tracker_demo/src/cnn.cpp
VPU calls base implementation which is to throw error for SetBatch.
https://github.com/opencv/open_model_zoo/issues/505
Signed-off-by: Aung Naing <aung.t.naing@intel.com>
> Fix error thrown from SetBatch in VPUs

- demos/smart_classroom_demo/create_list.py
Signed-off-by: Chia-Chen Wong <wongchiacheng@gmail.com>
> Generate faces_gallery.json file in multi-lines format

- tools/downloader/pytorch_to_onnx.py
- Added support for multi-input and multi-output models
- Added model parameters support
NEW:
Model parameters are set by multiple use of `--model-param` key, one parameter per key, e.g.:
```
--model-param foo=17 -model-param bar=True --model-param 'baz="BAZ"'
```
> Conversion pytorch-to-onnx new features

- tools/accuracy_checker/accuracy_checker/adapters/action_recognition.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
- tools/accuracy_checker/configs/octave-resnet-200-0.125.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-0005.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-teacher-0002.yml
- tools/accuracy_checker/configs/person-detection-raisinghand-recognition-0001.yml
* workaround to work both R3 & R4 models - person-detection-action-recognition
* fixed config for FP16 octavenet
* fixed voc segmentation converter
> AC: fix after latest update

- demos/mask_rcnn_demo/CMakeLists.txt
- demos/mask_rcnn_demo/main.cpp
See the individual commits for details.
> Various cleanups in mask_rcnn_demo

- tools/accuracy_checker/accuracy_checker/metrics/regression.py
fix wrong optimization direction for PSNR metric. Strongly required for calibration.
@IRDonch, please merge ASAP
> AC: PSNR metric sense

- tools/accuracy_checker/accuracy_checker/config/config_reader.py
allow merge content of json config (which has relation with AC) using env vars
> AC: allow merge calibration config with path prefix and definitions

- models/intel/index.md
> Fix reid-related table on the common description page

- demos/tests/cases.py
- demos/tests/run_tests.py
Collection of execution time for demos added
> Collection of execution time for demos added

- tools/accuracy_checker/custom_evaluators/mtcnn_evaluator.py
prevent converting 2 models with he same name
> AC: fix MTCNN conversion

- demos/python_demos/3d_segmentation_demo/3d_segmentation_demo.py
- demos/python_demos/3d_segmentation_demo/README.md
Added support for single nifti file.
> 3d segmentation demo fix

- demos/smart_classroom_demo/include/action_detector.hpp
- demos/smart_classroom_demo/include/cnn.hpp
- demos/smart_classroom_demo/include/detector.hpp
- demos/smart_classroom_demo/include/face_reid.hpp
- demos/smart_classroom_demo/main.cpp
- demos/smart_classroom_demo/src/cnn.cpp
- demos/smart_classroom_demo/src/reid_gallery.cpp
- demos/tests/cases.py
See the commits for more details.
> smart_classroom_demo: factor out the face recognition code into a class

- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py
- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation_3d.py
- tools/accuracy_checker/accuracy_checker/metrics/mpjpe_multiperson.py
- tools/accuracy_checker/accuracy_checker/representation/pose_estimation_3d_representation.py
- tools/accuracy_checker/accuracy_checker/representation/pose_estimation_representation.py
during calibration of this model, found issue with nan values in outputs. Allows adapter handle this situation.
> AC: make human-pose-3d adapter more stable to unexpected value range

- tools/accuracy_checker/accuracy_checker/config/config_reader.py
accidentally removed command line option processing...
> AC: fix removing deprecated IR generation

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
- tools/accuracy_checker/accuracy_checker/metrics/reid.py
- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessing_executor.py
person reid model can not be quantized due to metric specification. (it is require to have at least 1 pair image for each image in the subset. Extended subset selection logic for this case,
> AC: update pairwise subset logic for quantization reid models

- tools/accuracy_checker/accuracy_checker/annotation_converters/action_recognition.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/camvid.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar10.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cityscapes.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/common_semantic_segmentation.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/detection_opencv_storage.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/imagenet.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/mnist.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/wider.py
AC allows labels overriding using json file.Added check that label map format is correct in this case.
> AC: add custom label map format verification

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
- tools/accuracy_checker/accuracy_checker/metrics/detection.py
- tools/accuracy_checker/accuracy_checker/metrics/multilabel_recognition.py
- tools/accuracy_checker/accuracy_checker/metrics/semantic_segmentation.py
some metrics use dataset meta info (e.g. label map)during evaluation added check that necessary info provided where it is necessary
> AC: added providing dataset meta verification in metrics

- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
resolve issue with device id specification without query api
> AC: support myriad device id specification

- demos/python_demos/3d_segmentation_demo/3d_segmentation_demo.py
- demos/python_demos/3d_segmentation_demo/README.md
1. support of different input modalities order
2. support of brain-tumor-segmentation-0002 model
> 3d segmentation demo update

- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
reduce memory on semantic-segmentation-adas-0001
> AC: restore condition for saving annotation and prediction

- ci/requirements-demos.txt
- demos/mask_rcnn_demo/README.md
- demos/mask_rcnn_demo/models.lst
- demos/python_demos/requirements.txt
- demos/tests/args.py
- demos/tests/cases.py
- demos/tests/data_sequences.py
- demos/tests/image_sequences.py
- demos/tests/run_tests.py
> Demo tests

- demos/python_demos/human_pose_estimation_3d_demo/pose_extractor/src/peak.cpp
This is pretty much a port of 57fa87f5.
> pose_extractor: replace unnecessary vectors with arrays

- tools/accuracy_checker/accuracy_checker/adapters/yolo.py
necessary for support [MobileFace Detection MXNet](https://github.com/becauseofAI/MobileFace/tree/128cea33b928dc9bb6d1963202b57a97f5661ccf#detection)
> AC: add support nhwc layout for yolo v3

- tools/accuracy_checker/configs/alexnet.yml
- tools/accuracy_checker/dataset_definitions.yml
> AC: fix typo in configs

- tools/downloader/README.md
- tools/downloader/common.py
This will be used by `text-spotting-0001-recognizer-encoder`.
> downloader: add new task type "feature_extraction"

- tools/accuracy_checker/accuracy_checker/annotation_converters/_nlp_common.py
Each Chinese character should be considered as a separate word in order
for AC to be compatible with contemporary Chinese tokenization schemae
> Fix tokenization for Chinese

- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher_readme.md
- tools/accuracy_checker/tests/test_input_feeder.py
> AC: support input precision specification

- demos/crossroad_camera_demo/main.cpp
- demos/object_detection_demo_ssd_async/main.cpp
- demos/object_detection_demo_yolov3_async/main.cpp
Similar to de05b4db7e4a502f7b33e97c947991f0d549360b
> demos: update cnnnetreader weights reading

- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessing_executor.py
necessary for calibration metrics and postprocessing overriding
> AC: fix initialization order

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/brats.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
- tools/accuracy_checker/dataset_definitions.yml
for support new models data reader default layout was changed, it affects old models.
> AC: fix nifti reader

- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
> AC: fix brain-tumor-segmentation-0002

- models/intel/asl-recognition-0003/description/asl-recognition-0003.md
- models/intel/human-pose-estimation-0001/description/human-pose-estimation-0001.md
- models/intel/person-reidentification-retail-0031/description/person-reidentification-retail-0031.md
- models/intel/person-reidentification-retail-0103/description/person-reidentification-retail-0103.md
- models/intel/person-reidentification-retail-0107/description/person-reidentification-retail-0107.md
- models/intel/person-reidentification-retail-0200/description/person-reidentification-retail-0200.md
- models/intel/product-detection-0001/description/product-detection-0001.md
- models/intel/text-spotting-0001-detector/description/text-spotting-0001-detector.md
- models/intel/text-spotting-0001-recognizer-decoder/description/text-spotting-0001-recognizer-decoder.md
- models/intel/text-spotting-0001-recognizer-encoder/description/text-spotting-0001-recognizer-encoder.md
- models/public/brain-tumor-segmentation-0002/brain-tumor-segmentation-0002.md
- models/public/efficientnet-b0-pytorch/efficientnet-b0-pytorch.md
- models/public/efficientnet-b0/efficientnet-b0.md
- models/public/efficientnet-b0_auto_aug/efficientnet-b0_auto_aug.md
- models/public/efficientnet-b5-pytorch/efficientnet-b5-pytorch.md
- models/public/efficientnet-b5/efficientnet-b5.md
- models/public/efficientnet-b7-pytorch/efficientnet-b7-pytorch.md
- models/public/efficientnet-b7_auto_aug/efficientnet-b7_auto_aug.md
- models/public/human-pose-estimation-3d-0001/description/human-pose-estimation-3d-0001.md
- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessing_executor.py
Still in progress, couldn't find some models
> Documentation Review

- demos/python_demos/asl_recognition_demo/README.md
- demos/python_demos/asl_recognition_demo/asl_recognition_demo.py
- demos/python_demos/asl_recognition_demo/asl_recognition_demo/common.py
- demos/python_demos/asl_recognition_demo/asl_recognition_demo/person_detector.py
- demos/python_demos/asl_recognition_demo/asl_recognition_demo/video_library.py
- Added option to show example of some ASL gestures
- Fixed issue with multi-output network
> ASL gesture recognition demo enhancement

- models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md
related issue https://github.com/opencv/open_model_zoo/issues/795
> fix emotions-recognition-retail-0003 naming in description

- models/intel/person-reidentification-retail-0200/description/person-reidentification-retail-0200.md
This is updated metrics for model 0200.
> Update metrics for model 0200

- demos/text_detection_demo/src/text_recognition.cpp
Fix for MR https://github.com/opencv/open_model_zoo/commit/d4e0da61079546e8ce9517293f602afc2de329ce
> Fixed compilation on CentOS

- tools/accuracy_checker/dataset_definitions.yml
add voc2012 without background to dataset definitions
> add voc2012 without background to dataset definitions

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar.py
- tools/accuracy_checker/sample/opencv_sample_config.yml
- tools/accuracy_checker/sample/sample_config.yml
attempt 2, now from own fork repo :)
> AC: support CIFAR100 dataset

- demos/common/monitors/presenter.cpp
Make plot lines reach edges of graphs.
Make graph titles darker to contrast with light background.w
> demos/monitors: beautify

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/_nlp_common.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/squad.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- added [SentencePiece](https://github.com/google/sentencepiece) tokenizer - required for XLNet enabling
- new datasets:
- new metrics
> AC: extend NLP support

- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
workaround for sg2, where we can not program several bitstream in config (but we need be able validate it)
> AC: sharing bitstream from previous run

- tools/accuracy_checker/README.md
- tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
- tools/accuracy_checker/accuracy_checker/adapters/text_detection.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/fashion_mnist.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/mnist.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/reid.py
- tools/accuracy_checker/accuracy_checker/postprocessor/brats_postprocessing.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/preprocessor/brats_preprocessing.py
- tools/accuracy_checker/accuracy_checker/preprocessor/centernet_preprocessing.py
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
- tools/accuracy_checker/accuracy_checker/progress_reporters.py
- tools/accuracy_checker/accuracy_checker/utils.py
- tools/accuracy_checker/requirements.in
declare way how install without dependencies and allow user manage components where it is possible
> AC: separated dependencies installation possibility

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_super_resolution.py
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
update adapter and add some postprocessing steps for enabling [SRGAN](https://github.com/tensorlayer/srgan) model
improvements:
> AC: support SRGAN

- tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/pipeline_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/presenters.py
- tools/accuracy_checker/custom_evaluators/mtcnn_evaluator.py
- tools/accuracy_checker/custom_evaluators/sequential_action_recognition_evaluator.py
- tools/accuracy_checker/custom_evaluators/text_spotting_evaluator.py
value for extraction (affect only usage AC as API) format is more suitable for validation pipeline
> AC: revise result extraction

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/action_recognition.py
it helps to enable i3d-flow model in AC
> AC: added support numpy files for action recognition

- demos/crossroad_camera_demo/crossroad_camera_demo.hpp
- demos/gaze_estimation_demo/gaze_estimation_demo.hpp
- demos/human_pose_estimation_demo/include/human_pose_estimation_demo.hpp
- demos/interactive_face_detection_demo/interactive_face_detection.hpp
- demos/mask_rcnn_demo/mask_rcnn_demo.h
- demos/multi_channel/common/multichannel_params.hpp
- demos/object_detection_demo_faster_rcnn/main.cpp
- demos/object_detection_demo_faster_rcnn/object_detection_demo_faster_rcnn.h
- demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.hpp
- demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.hpp
- demos/pedestrian_tracker_demo/include/pedestrian_tracker_demo.hpp
- demos/security_barrier_camera_demo/security_barrier_camera_demo.hpp
- demos/segmentation_demo/segmentation_demo.h
- demos/smart_classroom_demo/include/smart_classroom_demo.hpp
- demos/super_resolution_demo/super_resolution_demo.h
> demos: Remove unnecessary line continuations

- tools/accuracy_checker/accuracy_checker/annotation_converters/_nlp_common.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py
Fix errors during convert_annotation from  [IMDB](http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz) dataset
> Mzuevx xlnet accuracy

- tools/downloader/README.md
- tools/downloader/common.py
- tools/downloader/converter.py
- tools/downloader/downloader.py
- tools/downloader/info_dumper.py
It's been deprecated for two releases now; time to get rid of it.
> downloader: remove the --config option

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
some datasets for semantic segmentation has separated folders for labels, added config parameter for it.
> AC: introduce isolated location segmentation masks from images

- tools/accuracy_checker/custom_evaluators/mtcnn_evaluator.py
> AC: fix MTCNN input transformation

- models/intel/index.md
- models/intel/unet-camvid-onnx-0001/description/unet-camvid-onnx-0001.md
add description of pre-trained on CamVid unet model for semantic segmentation
> add unet-camvid-onnx-0001 description

- demos/README.md
- demos/multi_channel/face_detection_demo/README.md
- demos/security_barrier_camera_demo/README.md
- models/intel/gaze-estimation-adas-0002/description/gaze-estimation-adas-0002.md
- models/intel/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.md
- models/intel/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.md
- models/intel/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.md
- models/intel/pedestrian-detection-adas-binary-0001/description/pedestrian-detection-adas-binary-0001.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/_nlp_common.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/icdar.py
> Remove non-ASCII characters

- ci/update-requirements.py
This automates the process I've been doing manually so far. This will make it easier, and will enable everyone else to do it too.
> Add a script to update ci/requirements-*.txt

- demos/CMakeLists.txt
- demos/interactive_face_detection_demo/CMakeLists.txt
- demos/interactive_face_detection_demo/detectors.cpp
- demos/multi_channel/object_detection_demo_yolov3/CMakeLists.txt
- demos/multi_channel/object_detection_demo_yolov3/main.cpp
- demos/object_detection_demo_ssd_async/CMakeLists.txt
- demos/object_detection_demo_ssd_async/main.cpp
- demos/object_detection_demo_yolov3_async/CMakeLists.txt
- demos/object_detection_demo_yolov3_async/main.cpp
- demos/pedestrian_tracker_demo/CMakeLists.txt
- demos/pedestrian_tracker_demo/src/detector.cpp
- demos/smart_classroom_demo/CMakeLists.txt
- demos/smart_classroom_demo/src/detector.cpp
CC @ilyachur, please, review as well.
> Supported IR v10 natively

- demos/multi_channel/face_detection_demo/README.md
- demos/multi_channel/human_pose_estimation_demo/README.md
- demos/multi_channel/object_detection_demo_yolov3/README.md
These demos all support RTSP, so the text should be identical. Synchronize it and improve it a little bit.
I simplified the "web (USB) or IP cameras" wording from `face_detection_demo/README.md`, since IP cameras are also web cameras.
> demos/multi_channel: update the IP-camera-related docs

- tools/accuracy_checker/README.md
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_async_request.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/tests/test_model_evaluator.py
move async from wait_for_any fo callback based api
TO DO:
Next steps
> AC: revise async execution

- tools/accuracy_checker/README.md
- tools/accuracy_checker/requirements-core.in
- tools/accuracy_checker/requirements.in
- tools/accuracy_checker/setup.py
added command to simplify installation with manual dependency management
added warning if opencv not found for better error understanding
> AC: install core components command

- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/representation/character_recognition_representation.py
- tools/accuracy_checker/accuracy_checker/representation/classification_representation.py
- tools/accuracy_checker/accuracy_checker/representation/detection_representation.py
- tools/accuracy_checker/accuracy_checker/representation/multilabel_recognition.py
- tools/accuracy_checker/accuracy_checker/representation/pose_estimation_representation.py
- tools/accuracy_checker/accuracy_checker/representation/regression_representation.py
- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
- tools/accuracy_checker/accuracy_checker/representation/text_detection_representation.py
- tools/accuracy_checker/accuracy_checker/utils.py
I found that some commits weren't merged with #776, so here they are
> AC: add thresholding to annotation creation

- models/public/midasnet/model.yml
This allows us to remove one of the postprocessing steps.
> midasnet: put the source files in a subdirectory

- tools/accuracy_checker/accuracy_checker/adapters/centernet.py
resolves [893](https://github.com/opencv/open_model_zoo/issues/893)
> AC: make centernet adapter compatible with numpy < 1.15

- tools/accuracy_checker/accuracy_checker/main.py
simple accuracy checker results writing. Can be useful for manual testing
> AC: write result in csv

- tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py
There are some small difference between annotation conversion for BERT and XLNet.
> AC: fix annotation converter for BERT text classification

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessor.py
- tools/accuracy_checker/tests/test_model_evaluator.py
required for NLP models support
> AC: support CN layout

- tools/accuracy_checker/configs/icnet-camvid-ava-tf-0001.yml
- tools/accuracy_checker/configs/icnet-camvid-ava-tf-sparse-30-0001.yml
- tools/accuracy_checker/configs/icnet-camvid-ava-tf-sparse-60-0001.yml
add configs for icnet-camvid-ava-tf-0001, icnet-camvid-ava-tf-sparse-30-0001 and icnet-camvid-ava-tf-sparse-60-0001 models
> add configs for icnet-camvid-ava-tf models

- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
> AC: fix clip accuracy update result

- tools/accuracy_checker/configs/yolo-tiny-v2-ava-0001.yml
- tools/accuracy_checker/configs/yolo-tiny-v2-ava-sparse-30-0001.yml
- tools/accuracy_checker/configs/yolo-tiny-v2-ava-sparse-60-0001.yml
- tools/accuracy_checker/configs/yolo-v2-ava-0001.yml
- tools/accuracy_checker/configs/yolo-v2-ava-sparse-35-0001.yml
- tools/accuracy_checker/configs/yolo-v2-ava-sparse-70-0001.yml
add global_defintions to yolo accuracy checker configs
> global_defintions in yolo configs

- demos/python_demos/object_detection_demo_yolov3_async/models.lst
- demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
- demos/tests/cases.py
- models/public/index.md
- models/public/yolo-v1-tiny-tf/keras_to_tensorflow.py.patch
- models/public/yolo-v1-tiny-tf/model.yml
- models/public/yolo-v1-tiny-tf/yolo-v1-tiny-tf.md
- models/public/yolo-v2-tf/keras_to_tensorflow.py.patch
- models/public/yolo-v2-tf/model.yml
- models/public/yolo-v2-tf/yolo-v2-tf.md
- models/public/yolo-v2-tiny-tf/keras_to_tensorflow.py.patch
- models/public/yolo-v2-tiny-tf/model.yml
- models/public/yolo-v2-tiny-tf/yolo-v2-tiny-tf.md
- models/public/yolo-v3-tf/keras_to_tensorflow.py.patch
- models/public/yolo-v3-tf/model.yml
- models/public/yolo-v3-tf/yolo-v3-tf.md
- tools/accuracy_checker/configs/yolo-v1-tiny-tf.yml
- tools/accuracy_checker/configs/yolo-v2-tf.yml
- tools/accuracy_checker/configs/yolo-v2-tiny-tf.yml
- tools/accuracy_checker/configs/yolo-v3-tf.yml
Models: YOLO v1 Tiny (VOC), YOLO v2 Tiny (COCO) from TF JS, YOLO v2, YOLO v3 from Keras
TODO:
> Added YOLO models

- models/intel/person-reidentification-retail-0103/description/person-reidentification-retail-0103.md
- models/intel/person-reidentification-retail-0107/description/person-reidentification-retail-0107.md
- models/intel/person-reidentification-retail-0200/description/person-reidentification-retail-0200.md
> Update name of test person-ReID dataset

- tools/accuracy_checker/configs/person-reidentification-retail-0103.yml
- tools/accuracy_checker/configs/person-reidentification-retail-0107.yml
- tools/accuracy_checker/configs/person-reidentification-retail-0200.yml
- tools/accuracy_checker/dataset_definitions.yml
> AC configs: replace dataset for person reid

- tools/accuracy_checker/configs/yolo-v2-tiny-ava-0001.yml
- tools/accuracy_checker/configs/yolo-v2-tiny-ava-sparse-30-0001.yml
- tools/accuracy_checker/configs/yolo-v2-tiny-ava-sparse-60-0001.yml
sync configs with yolo naming change
> align yolo naming

- tools/accuracy_checker/accuracy_checker/adapters/detection.py
- tools/accuracy_checker/configs/person-detection-asl-0001.yml
workaround for output names changes
> AC: output search logic change for fcos adapter

- tools/accuracy_checker/configs/unet-camvid-onnx-0001.yml
add unet-camvid-onnx-0001 accuracy checker config
> unet-camvid-onnx-0001 accuracy checker config

- tools/accuracy_checker/configs/person-detection-asl-0001.yml
add fp16 section to person-detection-asl-0001 config
> fp16 section in person-detection-asl-0001 config

- tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
- tools/accuracy_checker/dataset_definitions.yml
> AC: voc segmentation converter update

- demos/text_detection_demo/include/cnn.hpp
- demos/text_detection_demo/src/cnn.cpp
IE doesn't recomend using setBatchSize() and for that demo using it leads to errors.
> text_detection remove setBatchSize()

- models/public/i3d-rgb-tf/freeze.py
- models/public/i3d-rgb-tf/i3d-rgb-tf.md
- models/public/i3d-rgb-tf/model.yml
- models/public/index.md
- tools/accuracy_checker/configs/i3d-rgb-tf.yml
- tools/accuracy_checker/dataset_definitions.yml
Model distributed as frozen graph, instruction and script for manual freezing also added.
> Added I3D-RGB model

- tools/accuracy_checker/configs/yolo-v1-tiny-tf.yml
- tools/accuracy_checker/configs/yolo-v3-tf.yml
> fix definitions

- tools/accuracy_checker/configs/efficientnet-b0.yml
- tools/accuracy_checker/configs/person-detection-action-recognition-0006.yml
- tools/accuracy_checker/configs/resnet18-xnor-binary-onnx-0001.yml
- tools/accuracy_checker/dataset_definitions.yml
fixed part of problem found during light-weight AV
> AC configs fix typos

- ci/update-requirements.py
This lets people update `ci/requirements-*.txt` when they change one of the input requirements files without introducing unrelated changes to package versions.
> ci/update-requirements.py: don't update versions by default

- tools/accuracy_checker/accuracy_checker/metrics/character_recognition.py
prevent broken AC installation due to impossibility to install lib on ARM
> AC: unnecessary imports

- demos/common/samples/common.hpp
- demos/interactive_face_detection_demo/detectors.cpp
- demos/interactive_face_detection_demo/detectors.hpp
- demos/multi_channel/object_detection_demo_yolov3/main.cpp
- demos/object_detection_demo_faster_rcnn/README.md
- demos/object_detection_demo_faster_rcnn/main.cpp
- demos/object_detection_demo_faster_rcnn/object_detection_demo_faster_rcnn.h
- demos/object_detection_demo_yolov3_async/main.cpp
- demos/pedestrian_tracker_demo/src/detector.cpp
- demos/smart_classroom_demo/src/detector.cpp
Ignore `object_detection_demo_ssd_async` because there are still older IRs for the demo.
> Demos C++ fix warnings

- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
fix deprecation warning with backward compatibility
> AC: IE API read net update

- tools/accuracy_checker/configs/instance-segmentation-security-1025.yml
@snosov1 @yssemaev @vladimir-dudnik
> Accuracy checker config for instance-segmentation-security-1025

- models/public/brain-tumor-segmentation-0002/brain-tumor-segmentation-0002.md
- models/public/index.md
The main issue - the name of original model is missing.
> Model brain-tumor-segmentation-0002 added to index.md

- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
fixed segfault after removal compiled blob in evaluation finalization stage.
> AC: remove inputs from input feeder in release stage

- demos/security_barrier_camera_demo/main.cpp
https://github.com/opencv/open_model_zoo/pull/639/files/1d1646d77d66ed206b12d66c480ddc03139e4bf1#r386952886
> Security barrier camera demo, fix config_value

- demos/common/monitors/presenter.cpp
- demos/common/monitors/presenter.h
- demos/gaze_estimation_demo/main.cpp
- demos/interactive_face_detection_demo/main.cpp
- demos/multi_channel/common/graph.cpp
- demos/object_detection_demo_faster_rcnn/object_detection_demo_faster_rcnn.h
- demos/security_barrier_camera_demo/main.cpp
- demos/segmentation_demo/main.cpp
Add it to the files where it's needed and remove from the files where it's not.
> demos: fix #include <chrono> usage

- tools/accuracy_checker/configs/mtcnn-o.yml
- tools/accuracy_checker/custom_evaluators/mtcnn_evaluator.py
> Fix MTCNN config and model conversion

- demos/tests/run_tests.py
Details in the commit messages.
> Overhaul the handling of models in run_tests.py

- models/public/yolo-v1-tiny-tf/yolo-v1-tiny-tf.md
- models/public/yolo-v2-tf/yolo-v2-tf.md
- models/public/yolo-v2-tiny-tf/yolo-v2-tiny-tf.md
- models/public/yolo-v3-tf/yolo-v3-tf.md
Since YOLO models have very tricky output, I expanded info about it to make it clear
> YOLO documentation update

- demos/python_demos/object_detection_demo_ssd_async/models.lst
- demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py
- demos/tests/cases.py
- models/public/index.md
- models/public/licenses/APACHE-2.0-MLPerf.txt
- models/public/ssd-resnet34-1200-onnx/model.yml
- models/public/ssd-resnet34-1200-onnx/ssd-resnet34-1200-onnx.md
- tools/accuracy_checker/configs/ssd-resnet34-1200-onnx.yml
I added the `onnx` suffix, because model downloading in ONNX format, but was pretrained in PyTorch (see [here](https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection) for details).
> SSD Resnet34 1200x1200

- tools/accuracy_checker/accuracy_checker/adapters/yolo.py
> Update Yolo Adapter to Fix Feature Scale Detection

- tools/accuracy_checker/accuracy_checker/adapters/nlp.py
Google BERT has excess dims in output, it leads to wrong results after postprocessing
> AC: flattenize BERT output in question answering adapter

- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
use new Python API functionality to prevent layout mismatch.
Changes isolated to work with blobs only,  no impact on common validation pipeline.
> AC: set blob

- demos/python_demos/object_detection_demo_yolov3_async/models.lst
- demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
- demos/tests/cases.py
mobilefacedet-v1-mxnet is yolo v3 based model. In comparision with other yolo models it has NHWC layout (there is no way to convert model with NCHW), these changes handle these difference.
> Add mobilefacedet-v1-mxnet in yolo demo

- tools/accuracy_checker/accuracy_checker/adapters/classification.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/preprocessor/audio_preprocessing.py
Support includes:
- reading wav files
- transforming audio: clipping, resampling
- multi-infer
> Added support for audio classification models

- tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
changes in input feeder is not necessary, but lets stay them for experiments
> AC: update for multi frame SR

- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessor.py
solve problem with audio networks quantization
> AC: register clip audio preprocessing as multi_infer

- tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/representation/base_representation.py
- tools/accuracy_checker/accuracy_checker/representation/representaton_container.py
data source in quantization broken for complicated representation types
> AC: fix providing data source for container annotation

- tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
resolves problem with BERT processing  (with int64 input precision) via ONNX Runtime launcher
> AC: use input dtype for onnxruntime launcher

- demos/python_demos/action_recognition/README.md
- demos/python_demos/action_recognition/action_recognition.py
- demos/python_demos/action_recognition/action_recognition_demo/meters.py
- demos/python_demos/action_recognition/action_recognition_demo/models.py
- demos/python_demos/action_recognition/action_recognition_demo/pipeline.py
- demos/python_demos/action_recognition/action_recognition_demo/queue.py
- demos/python_demos/action_recognition/action_recognition_demo/result_renderer.py
- demos/python_demos/action_recognition/action_recognition_demo/steps.py
- demos/python_demos/action_recognition/action_recognition_demo/timer.py
> Action recognition demo update

- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_async_request.py
update AC to work with new IE python API
> AC: update getting infer request outputs

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/image_processing.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/image_processing.py
- tools/accuracy_checker/accuracy_checker/representation/super_resolution_representation.py
created common image processing task specific entities suitable for image processing tasks (like super resolution, denoising, debluring style transfer e.t.c.) to avoid some misleading and simplify enabling new tasks.
Also supported NHWC layout for these tasks
> AC: support general image processing task

- demos/python_demos/face_recognition_demo/README.md
> Fix README of face_recognition_demo

- demos/python_demos/object_detection_demo_yolov3_async/README.md
- demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
*UPDATE:*
The demo will be updated to proportional resize.
> YOLO python demo: proportional resize

- demos/object_detection_demo_yolov3_async/main.cpp
Fixed problem with infer on GPU, caused by some problems with nGraph and plugin. Also removed using of deprecated class `CNNLayer`.
> YOLO cpp demo fix

- tools/downloader/pytorch_to_onnx.py
Also, remove unnecesary linebreaks from that message.
> pytorch_to_onnx.py: add missing format call to a message

- demos/object_detection_demo_yolov3_async/models.lst
- demos/tests/cases.py
Merge after [PR 1113](https://github.com/opencv/open_model_zoo/pull/1113)
> Added cpp object_detection_demo_yolov3_async to test setup

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/adapter.py
- tools/accuracy_checker/accuracy_checker/adapters/yolo.py
remove users confusing behaviour
> AC: update adapter configuration

- models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md
> Update typo error faster_rcnn_inception_v2_coco.md

- models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md
Reverts opencv/open_model_zoo#1153 as we do not accept PR for master branch in general (this is branch corresponding content of the latest public release)
> Revert "Update typo error faster_rcnn_inception_v2_coco.md"

- demos/classification_demo/README.md
- demos/classification_demo/classification_demo.hpp
- demos/classification_demo/main.cpp
- demos/classification_demo/models.lst
Works with all three new HBONet-s.
I've also changed the default resolution because 1920x1080 was higher than what almost all other demos had.
> classification_demo: Add HBONet support, change default resolution

- tools/accuracy_checker/accuracy_checker/progress_reporters.py
now it prints progress always begin from new line, logs are expanded very much
> AC: fix tqdm reporter

- ci/requirements-ac-test.txt
- ci/requirements-ac.txt
- ci/requirements-conversion.txt
- ci/requirements-demos.txt
- ci/requirements-downloader.txt
- demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
Don't bump the versions, just update the lists.
> Update ci/requirements-*.txt using a prerelease build of OpenVINO 2020.4

- tools/accuracy_checker/accuracy_checker/annotation_converters/oar3d.py
Fixes absolute paths in ge_tiling dataset annotations
> Fix absolute paths in annotations

- demos/object_detection_demo_ssd_async/README.md
- demos/object_detection_demo_ssd_async/main.cpp
- demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.hpp
- demos/object_detection_demo_yolov3_async/README.md
- demos/object_detection_demo_yolov3_async/main.cpp
- demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.hpp
Adds option `-labels` for file with labels mapping. Also fixed previous errors with reading labels.
> [DEMO] Add labels file to CPP Object Detection demos

- models/public/faster_rcnn_resnet101_coco/model.yml
- models/public/faster_rcnn_resnet101_coco/quantization.yml
- models/public/faster_rcnn_resnet50_coco/model.yml
- models/public/faster_rcnn_resnet50_coco/quantization.yml
- tools/downloader/quantizer.py
To do that, implement custom quantization config support in Model Quantizer.
> Enable quantization for faster_rcnn_resnet*

- tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
fix for AA quantization of instance segmentation models
> AC: fix segmentation mask processing in coco metric

- tools/downloader/common.py
- tools/downloader/downloader.py
Now when we retry a download, we try to resume from where we left off, and if that fails, restart from the beginning.
Currently, this is only implemented for plain HTTP sources (i.e., not Google Drive).
> tools/downloader: implement download resumption

- models/intel/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.md
fix framework in semantic-segmentation-adas-0001 description
> semantic-segmentation-adas-0001 fix fwk

- demos/python_demos/text_spotting_demo/README.md
- demos/python_demos/text_spotting_demo/text_spotting_demo.py
model does not work on HDDL/MyriadX, so do not mention these devices in demo documentation
> fix demo doc

- tools/accuracy_checker/accuracy_checker/adapters/detection.py
Before, each single batch prediction was matched with all the candidates detected in the previous stage. Instead, each item in raw 
(single batch prediction) should be matched with a single corresponding candidate.
> Fix error in VAS Face detection refinement stage adapter

- demos/README.md
> Remove links to the deleted Face Recognition demo

- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
@vladimir-dudnik  please merge ASAP, currently validation of any model is broken
> AC: fix data reader

- tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/fashion_mnist.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/mnist.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_style_transfer.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_super_resolution.py
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
- tools/accuracy_checker/requirements-core.in
- tools/accuracy_checker/requirements.in
in some tasks, it is impossible to work without PIL (e.g. segmentation) or do not guarantee results reproducibility with other similar tools
On other hand, it is easy to install and available for all platforms, so I decide to include it to core requirements list
> AC: make Pillow core requirement

- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/tests/test_model_evaluator.py
> AC: support LSTM input

- tools/downloader/common.py
Testing showed that GDrive does support range requests, so it seems reasonable to enable it.
> downloader: implement download resumption for Google Drive files

- tools/accuracy_checker/accuracy_checker/annotation_converters/cifar.py
fix customizing labels via `label_map`
> AC: fix CIFAR converter

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/ade20k_dataset_converter.py
- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/extend_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
and some deeplab specific pre- post- processing
> AC: support ADE20K dataset

- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/postprocessor/crop_ground_truth_image.py
- tools/accuracy_checker/accuracy_checker/postprocessor/crop_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/preprocessor/crop.py
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
supported preprocessing and postprocessing like in https://www.tensorflow.org/api_docs/python/tf/image/resize_with_crop_or_pad
> AC: realize crop or pad preprocessing

- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_prediction_boxes.py
added fixing boxes size on model input shape
enables ssd gluoncv models
> AC: support detection boxes rescaling

- models/public/index.md
fix odd `|` character in table for CTPN row
> fix CTPN row in the table

- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
closes https://github.com/openvinotoolkit/open_model_zoo/issues/1078
> AC docs: fix postprocessor name

- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/reid.py
* add top_k parameter in normalized_embedding_accuracy
* update docs
* evaluation by numpy matrix multiplication instead of double for loops
> Add `top_k` parameter in normalized_embedding_accuracy

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/criteo_kaggle_dac.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/postprocessor/cast_to_int.py
- tools/accuracy_checker/accuracy_checker/representation/classification_representation.py
Support for accuracy test for DLRM model. 
Annotation_converter for Criteo kaggle dac dataset added.
NumpyReader modified to allow reading multiple features from multiple files.
"Accuracy" metric enabled for ArgMaxClassificationPrediction.
Cast_to_int postprocessor enabled for ClassificationAnnotation, ClassificationPrediction
> Support for DLRM model and criteo kaggle dac dataset

- tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/style_transfer.py
- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/utils.py
fix for relative path in config without prefix usage
> AC: fix paths conversion

- models/public/aclnet/aclnet.md
- models/public/aclnet/model.yml
- models/public/index.md
- tools/downloader/README.md
- tools/downloader/common.py
Add model description for sound classification with AclNet
Co-authored by: Paulo Lopez Meyer <paulo.lopez.meyer@intel.com>
Signed-off-by: Sathish Kuttan <sathish.k.kuttan@intel.com>
> AclNet - Model description

- tools/accuracy_checker/dataset_definitions.yml
let's use consistent naming convention, at least for similar datasets
> naming consistency

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/yolact.py
- tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
- tools/accuracy_checker/dataset_definitions.yml
> AC: Yolact adapter

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/face_recognition_quality_assessment.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/score_class_comparison.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/quality_assessment.py
- add representations for face recognition quality assessment model: `QualityAssessmentAnnotation`, `QualityAssessmentPrediction`
- add adapter for face recognition quality assessment model: `QualityAssessmentAdapter`
- add metric for face recognition quality assessment model: `ScoreClassComparison`
> Add representation, adapter and metric for face recognition quality assessment model

- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/preprocessor/crop.py
reimplementation of [decode_and_crop](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/preprocessing.py#L171)
> AC: support center crop from tf official

- tools/accuracy_checker/accuracy_checker/adapters/detection_person_vehicle.py
it is the reason of low accuracy :)
> AC: fix boxes scaling in person vehicle detection adapter

- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
in this release were added more common way to specify path to additional data resources (hr image for super resolution task, reference features and so on), added opportunity to use the same way in segmentation case
> AC: additional data source as segmentation mask source

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
and handled scenario when lr suffix is empty string
> AC: enabled suffixes ignoring in sr converter

- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
for debug and visualization purposes it can become useful to get prediction result for single image. This Pr introduce such functional API
> AC: process single image method

- demos/python_demos/object_detection_demo_ssd_async/models.lst
The old face-detection models were removed and the new ones haven't been
added yet.
> Temporarily remove face-detection-* from models.lst

- tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher.py
- tools/accuracy_checker/accuracy_checker/preprocessor/color_space_conversion.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
- tools/accuracy_checker/tests/test_tf_launcher.py
tf is trouble maker due to specific requirements on protobuf version and issues with its search.
I suggest to import it only if user want use it directly, it reduces troubles connected with tf configuration from user side
> AC: tf import localization

- tools/accuracy_checker/accuracy_checker/postprocessor/crop_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/postprocessor/encode_segmentation_mask.py
- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessor.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
resize prediction mask back to original image size in single image processing mode.
No affect of regular running
> AC: support prediction reconstruction if annotation is not provided

- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
Wrapper to use  sklearn.metrics.roc_auc_score in accuracy_checker.
Needed for DLRM MLPERF 100GB model validation.
> ROC AUC metric implementation

- models/public/ssd-resnet34-1200-onnx/model.yml
- models/public/ssd-resnet34-1200-onnx/ssd-resnet34-1200-onnx.md
The source repository layout has changed.
> ssd-resnet34-1200-onnx: fix link in the description

- demos/object_detection_demo_yolov3_async/models.lst
- demos/python_demos/object_detection_demo_yolov3_async/models.lst
- models/public/index.md
- models/public/yolo-v3-tiny-tf/accuracy-check.yml
- models/public/yolo-v3-tiny-tf/model.yml
- models/public/yolo-v3-tiny-tf/yolo-v3-tiny-tf.md
- tools/accuracy_checker/configs/yolo-v3-tiny-tf.yml
> Add Yolo V3 Tiny from Keras

- demos/python_demos/human_pose_estimation_3d_demo/modules/parse_poses.py
Inspired by issue [1500](https://github.com/openvinotoolkit/open_model_zoo/issues/1500)
> Add info for importing pose_extractor error

- models/intel/yolo-v2-tiny-vehicle-detection-0001/description/yolo-v2-tiny-vehicle-detection-0001.md
> Update accuracy numbers for yolo-v2-tiny-vehicle-detection-0001

- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
Fix wrong model input name match in numpy_reader.
Fix wrong 1D arrays processing in _data_to_blob()
> Mzuevx dlrm fixes

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
in some rare cases, mtcnn produces invalid crop candidates for other steps. added check for filtering such boxes
> AC: add validation of detections for mtcnn

- tools/accuracy_checker/accuracy_checker/preprocessor/inpainting_preprocessor.py
fixed casting to int parameters for inpaint preprocessing
> AC: fix inpainting preprocessing

- demos/classification_demo/main.cpp
- demos/crossroad_camera_demo/main.cpp
- demos/gaze_estimation_demo/main.cpp
- demos/human_pose_estimation_demo/main.cpp
- demos/interactive_face_detection_demo/main.cpp
- demos/mask_rcnn_demo/main.cpp
- demos/multi_channel/face_detection_demo/main.cpp
- demos/multi_channel/human_pose_estimation_demo/main.cpp
- demos/multi_channel/object_detection_demo_yolov3/main.cpp
- demos/object_detection_demo_faster_rcnn/main.cpp
- demos/object_detection_demo_ssd_async/main.cpp
- demos/object_detection_demo_yolov3_async/main.cpp
- demos/pedestrian_tracker_demo/main.cpp
- demos/security_barrier_camera_demo/main.cpp
- demos/segmentation_demo/main.cpp
- demos/smart_classroom_demo/main.cpp
- demos/super_resolution_demo/main.cpp
- demos/text_detection_demo/main.cpp
inference engine version output
> fix version output

- demos/python_demos/formula_recognition_demo/models.lst
add models.lst to formula_recognition_demo
> fix formula_recognition_demo

- tools/accuracy_checker/accuracy_checker/metrics/im2latex_images_match.py
Added check if important programs are installed to correctly perform formula-recognition evaluation. Also added progress information while rendering and comparing images.
> formula-recognition: progress info & check for important programs

- models/public/gmcnn-places2-tf/freeze_model.patch
- models/public/gmcnn-places2-tf/gmcnn-places2-tf.md
- models/public/gmcnn-places2-tf/model.yml
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/representation/image_inpainting.py
Accuracy checker is updated correspondingly.
> gmcnn-places2-tf is modified for BGR->BGR processing.

- demos/python_demos/asl_recognition_demo/asl_recognition_demo/common.py
- demos/python_demos/instance_segmentation_demo/instance_segmentation_demo.py
- demos/python_demos/monodepth_demo/monodepth_demo.py
- demos/python_demos/multi_camera_multi_target_tracking/utils/ie_tools.py
- demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py
- demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
- demos/python_demos/segmentation_demo/segmentation_demo.py
- demos/python_demos/text_spotting_demo/text_spotting_demo.py
- demos/python_demos/whiteboard_inpainting_demo/utils/ie_tools.py
PR should go to develop branch. We do not merge PRs to master without explicit need
> Revert "fix #38545 remove CPU network layer check for py demos"

- demos/python_demos/image_inpainting_demo/README.md
- demos/python_demos/image_inpainting_demo/inpainting_gui.py
> Image Inpainting GUI modifications

- models/public/colorization-v2/colorization-v2.md
> update link in colorization description

- tools/accuracy_checker/accuracy_checker/annotation_converters/im2latex.py
This patch fixes unsafe mutating of the dictionary while iterating over it. Previous version of this code lead to incorrect conversion of the keys (not all keys were converted from str to int).
> save mutating dict while iterating over it

- demos/gaze_estimation_demo/gaze_estimation_demo.hpp
> fix for issue 1570

- demos/CMakeLists.txt
> [Demos] Bumping demos cmake to 3.10

- demos/python_demos/object_detection_demo_ssd_async/models.lst
> Resolve a TODO in python_demos/object_detection_demo_ssd_async/models.lst

- demos/python_demos/formula_recognition_demo/models.lst
And sort the list while I'm at it.
> formula_recognition_demo: fix the model names in models.lst

- demos/python_demos/multi_camera_multi_target_tracking/multi_camera_multi_target_tracking.py
This pull request solves https://github.com/openvinotoolkit/open_model_zoo/issues/1578.
> Fix the out of memory error in FramesThreadBody

- demos/multi_channel/common/CMakeLists.txt
- demos/multi_channel/face_detection_demo/main.cpp
- demos/multi_channel/human_pose_estimation_demo/main.cpp
- demos/multi_channel/object_detection_demo_yolov3/main.cpp
Follows up https://github.com/openvinotoolkit/open_model_zoo/pull/1567
> multi_channel: hide threading

- demos/python_demos/text_spotting_demo/text_spotting_demo.py
Resolves https://github.com/openvinotoolkit/open_model_zoo/issues/1625
> text_spotting: fix dir input

- models/public/efficientnet-b0-pytorch/efficientnet-b0-pytorch.md
- models/public/efficientnet-b0/efficientnet-b0.md
- models/public/efficientnet-b0_auto_aug/efficientnet-b0_auto_aug.md
- models/public/efficientnet-b5-pytorch/efficientnet-b5-pytorch.md
- models/public/efficientnet-b5/efficientnet-b5.md
- models/public/efficientnet-b7-pytorch/efficientnet-b7-pytorch.md
- models/public/efficientnet-b7_auto_aug/efficientnet-b7_auto_aug.md
Fix output format description for both original and converted model
> EfficientNets description fixes

- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/gan_metrics.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/raw_representation.py
This PR provides realizations of IS(Inception score) and FID(Frechet Inception Distance) metrics.
> Add metrics for GAN models

- tools/accuracy_checker/accuracy_checker/representation/nlp_representation.py
Representation has been expanded to use in models without input_mask, segment_ids and tokens.
> AC: Updated TextClassificationAnnotation

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/detection.py
- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py
- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation_3d.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/squad_emb.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/serialize_parameters.py
- tools/accuracy_checker/accuracy_checker/utils.py
- tools/accuracy_checker/dataset_definitions.yml
- tools/accuracy_checker/tests/test_dataset.py
- tools/accuracy_checker/tests/test_dlsdk_launcher.py
- tools/accuracy_checker/tests/test_input_feeder.py
- tools/accuracy_checker/tests/test_presenter.py
A few of the things with errors in them weren't needed at all, so I just removed them.
One of these changes should actually reenable a test that has been accidentally disabled this whole time.
> AC: Fix several spelling errors

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/place_recognition.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/reid.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/reid_representation.py
- tools/accuracy_checker/setup.cfg
> AC: support image based localization task

- demos/python_demos/speech_recognition_demo/requirements.txt
- demos/python_demos/speech_recognition_demo/speech_recognition_demo.py
- demos/python_demos/speech_recognition_demo/utils/context_timer.py
Replace contexttimer module; fix the broken alphabet file example
> Fix speech recognition demo

- models/intel/handwritten-simplified-chinese-recognition-0001/description/handwritten-simplified-chinese-recognition-0001.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/unicode_character_recognition.py
and restore converter name for backward compatibility
> update descriptiom for simplified-chinese-recognition

- ci/get-jobs-for-changes.py
Should fix the build for #1450.
> ci/get-jobs-for-changes.py: be more careful with per-model Python files

- ci/check-basics.py
* Check that all path lengths are below a limit;
* Check that our shebang lines don't implicitly request Python 2.
> Add more basic checks

- demos/python_demos/instance_segmentation_demo/README.md
- demos/python_demos/instance_segmentation_demo/instance_segmentation_demo.py
- demos/python_demos/instance_segmentation_demo/instance_segmentation_demo/model_utils.py
- demos/python_demos/instance_segmentation_demo/models.lst
- models/public/index.md
- models/public/yolact-resnet50-fpn-pytorch/accuracy-check.yml
- models/public/yolact-resnet50-fpn-pytorch/model.py
- models/public/yolact-resnet50-fpn-pytorch/model.yml
- models/public/yolact-resnet50-fpn-pytorch/yolact-resnet50-fpn-pytorch.md
- tools/accuracy_checker/configs/yolact-resnet50-fpn-pytorch.yml
- tools/downloader/common.py
> add yolact-resnet50-fpn support

- demos/python_demos/colorization_demo/README.md
- demos/python_demos/colorization_demo/colorization_demo.py
- demos/python_demos/colorization_demo/models.lst
- models/public/colorization-siggraph/accuracy-check.yml
- models/public/colorization-siggraph/colorization-siggraph.md
- models/public/colorization-siggraph/model.yml
- models/public/index.md
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/colorization_evaluator.py
- tools/accuracy_checker/configs/colorization-siggraph.yml
- tools/downloader/pytorch_to_onnx.py
PyTorch model for Real-Time User-Guided Image Colorization.
> Add colorization-siggraph model

- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/postprocessor/shift.py
converted Efficientdet model returns class labels shifted by 1 (starting from 0, where 0 is person label)
> AC: Add detection labels shift postprocessing for Efficientdet

- models/public/retinaface-anti-cov/model.yml
- models/public/retinaface-anti-cov/retinaface-anti-cov.md
- models/public/retinaface-resnet50/model.yml
- models/public/retinaface-resnet50/retinaface-resnet50.md
update links on retainaface models according to updated repository structure
> Docs: update links on retinaface

- models/public/gmcnn-places2-tf/accuracy-check.yml
- tools/accuracy_checker/accuracy_checker/adapters/style_transfer.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/inpainting_preprocessor.py
- tools/accuracy_checker/dataset_definitions.yml
and made results compatible for different datasets
> AC: support mask inversion in inpainting

- demos/python_demos/formula_recognition_demo/formula_recognition_demo.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/i3d_evaluator.py
(and fix the spelling of "performance")
> Replace Cyrillic С with Latin C

- demos/python_demos/gesture_recognition_demo/models.lst
Added common-sign-language-???? model to the model list of gesture recognition demo.
> Updates gesture recognition demo model support

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/optical_flow.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/optical_flow.py
> AC: support optical flow task

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/salient_objects_detection.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/salient_object_detection.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/salient_objects_detection.py
- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/postprocessor/normalize_salient_map.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
> AC: support salient region detection

- demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/ctc_beam_search_decoder.cpp
- demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/decoder_utils.h
- demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/path_trie.cpp
- demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/word_prefix_set.cpp
- demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/yoklm/memory_section.hpp
* uninitialized class members;
* useless calls to "empty";
* some narrowing conversions.
> speech_recognition_demo: fix various warnings in ctcdecode-numpy

- models/public/ctdet_coco_dlav0_384/ctdet_coco_dlav0_384.md
- models/public/ctdet_coco_dlav0_512/ctdet_coco_dlav0_512.md
Correct the information about centernet. It is detection, not classification.
> Correct the information about centernet. It is detection, not classification.

- tools/accuracy_checker/requirements.in
reduce parasail version due to unavailability for mac os
> AC: restriction on parasail version

- tools/downloader/downloader.py
Added checks for hashes and sizes of cached files to avoid using corrupted cache files
> Checks for cache hash and size in downloader.py

- models/public/face-recognition-mobilefacenet-arcface/accuracy-check.yml
- models/public/face-recognition-mobilefacenet-arcface/face-recognition-mobilefacenet-arcface.md
- models/public/face-recognition-resnet100-arcface/accuracy-check.yml
- models/public/face-recognition-resnet100-arcface/face-recognition-resnet100-arcface.md
- models/public/face-recognition-resnet34-arcface/accuracy-check.yml
- models/public/face-recognition-resnet34-arcface/face-recognition-resnet34-arcface.md
- models/public/face-recognition-resnet50-arcface/accuracy-check.yml
- models/public/face-recognition-resnet50-arcface/face-recognition-resnet50-arcface.md
- tools/accuracy_checker/accuracy_checker/adapters/reidentification.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/lfw.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/dataset_definitions.yml
updated accuracy measurement according proposed by authors
> AC: update accuracy evaluation method for arcface models

- models/public/license-plate-recognition-barrier-0007/license-plate-recognition-barrier-0007.md
update ref values for actually used synthetic dataset
> update ref for license-plate-recognition-barrier-0007

- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
scores output become an optional in new model generation
> AC: fix text spotting evaluator for quantization

- models/public/resnet-50-tf/resnet-50-tf.md
See https://github.com/openvinotoolkit/openvino/issues/3070
> Fixed link to script

- licensing/third-party-programs.txt
It's for `demos/python_demos/speech_recognition_demo/ctcdecode-numpy/ctcdecode_numpy/numpy.i`.
> Add NumPy to third-party-programs.txt

- demos/README.md
- demos/python_demos/3d_segmentation_demo/README.md
- demos/python_demos/action_recognition/README.md
- demos/python_demos/bert_question_answering_demo/README.md
- demos/python_demos/gesture_recognition_demo/README.md
- demos/python_demos/human_pose_estimation_3d_demo/README.md
- demos/python_demos/image_retrieval_demo/README.md
- demos/python_demos/instance_segmentation_demo/README.md
- demos/python_demos/multi_camera_multi_target_tracking/README.md
- demos/python_demos/segmentation_demo/README.md
- demos/python_demos/text_spotting_demo/README.md
- demos/segmentation_demo/README.md
make consistent escape symbols usage (instead of `Python*` use `Python\*`)
> add escape symbols

- tools/accuracy_checker/accuracy_checker/metrics/reid.py
auc and precision_recall_curve are simple functions which can be implemented on pure numpy, it should not be restriction for models evaluation.
Possibly in future we remove them at all
> AC: added alternatives sklearn for reid if it is not available

- demos/python_demos/segmentation_demo/README.md
- demos/python_demos/segmentation_demo/models.lst
- demos/python_demos/segmentation_demo/segmentation_demo.py
- demos/segmentation_demo/models.lst
This PR is a try to solve issue #411. Features:
1. Now demo can work with files and save results to ouput file.
2. Demo using numpy random to create colors for classes.
3. Users can specify classes and colors.
4. Add parameter `classes` to add information about accordance class-color to the image.
> Change python segmentation demo

- demos/python_demos/image_translation_demo/README.md
- demos/python_demos/image_translation_demo/image_translation_demo.py
> fix readme

- models/intel/person-detection-action-recognition-0005/description/person-detection-action-recognition-0005.md
- models/intel/person-detection-action-recognition-teacher-0002/description/person-detection-action-recognition-teacher-0002.md
- models/intel/person-detection-asl-0001/description/person-detection-asl-0001.md
- models/intel/person-detection-raisinghand-recognition-0001/description/person-detection-raisinghand-recognition-0001.md
- models/intel/vehicle-detection-0202/description/vehicle-detection-0202.md
> fix ref values

- .flake8
- .gitattributes
- ci/check-basics.py
- ci/requirements-check-basics.in
- ci/requirements-check-basics.txt
- demos/python_demos/instance_segmentation_demo/instance_segmentation_demo/model_utils.py
- demos/python_demos/machine_translation_demo/machine_translation_demo.py
- demos/python_demos/text_to_speech_demo/utils/text_preprocessing.py
- demos/smart_classroom_demo/action_event_metrics.py
- tools/accuracy_checker/accuracy_checker/metrics/reid.py
Enable a limited set of checks for now. I'd like to gradually enable more checks as time goes on.
Fix all issues detected so far (see commit messages for slightly more details).
> Add flake8 to the basic checks

- .flake8
- demos/python_demos/handwritten_text_recognition_demo/utils/codec.py
- demos/python_demos/single_human_pose_estimation_demo/estimator.py
- demos/python_demos/text_to_speech_demo/utils/numbers.py
- tools/accuracy_checker/tests/test_parameters.py
Fix existing indentation problems.
> flake8: add some indentation checks

- models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md
1- person, 2 - vehicle, 3 - bike
> add classes description

- .flake8
- demos/python_demos/image_translation_demo/image_translation_demo.py
- demos/python_demos/object_detection_demo/object_detection_demo.py
- demos/python_demos/text_to_speech_demo/models/mel2wave_ie.py
- demos/tests/cases.py
Fix all existing issues, which are all star imports.
> flake8: enable all remaining pyflakes checks

- .flake8
- ci/documentation_updater/documentation_updater.py
- demos/tests/cases.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/_nlp_common.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/inpainting.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py
- tools/accuracy_checker/accuracy_checker/data_analyzer/__init__.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_to_speech_evaluator.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/instance_segmentation_metric_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/object_detection_metric_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/metrics/speech_recognition.py
- tools/accuracy_checker/accuracy_checker/preprocessor/crop.py
- tools/accuracy_checker/tests/test_preprocessor.py
I think this might be the last check from base flake8 that I'm going to enable for the time being. However, there are several promising flake8 plugins that I'll be looking into.
> flake8: enable check for closing bracket indentation

- models/public/cocosnet/model.yml
> Several fixes for cocosnet

- models/public/colorization-siggraph/accuracy-check-pipelined.yml
- models/public/colorization-siggraph/accuracy-check.yml
- models/public/colorization-siggraph/colorization-siggraph.md
- models/public/colorization-v2/accuracy-check-pipelined.yml
- models/public/colorization-v2/accuracy-check.yml
- models/public/colorization-v2/colorization-v2.md
- models/public/index.md
- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/super_resolution_image_recovery.py
- tools/accuracy_checker/dataset_definitions.yml
> Added configs for colorization models without pipeline

- models/public/ssd300/ssd300.md
- models/public/ssd512/ssd512.md
update voc2012 dataset details for ssd models
> update ssd models description

- demos/common/models/include/models/detection_model_faceboxes.h
- demos/common/models/src/detection_model_faceboxes.cpp
- demos/object_detection_demo/main.cpp
- demos/object_detection_demo/models.lst
Add cpp wrapper for faceboxes-pytorch model.
> cpp object detection demo: add faceboxes wrapper

- tools/accuracy_checker/accuracy_checker/adapters/segmentation.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/camvid.py
- tools/accuracy_checker/accuracy_checker/launcher/tf2_launcher.py
- tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
also fixed byte scaling for segmentation mask resizing
extended segmentation adapter to work with NHWC output format
> AC: support camvid with 32 cls and segmentation model with flatten out

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/see_in_the_dark.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/accuracy_checker/preprocessor/raw_image_preprocessing.py
- tools/accuracy_checker/accuracy_checker/representation/image_processing.py
- tools/accuracy_checker/requirements.in
supported models described in the [paper](https://cchen156.github.io/paper/18CVPR_SID.pdf) from this [repo](https://github.com/cchen156/Learning-to-See-in-the-Dark)
> AC: support see in the dark task

- demos/object_detection_demo/models.lst
- demos/python_demos/object_detection_demo/models.lst
- demos/tests/cases.py
add efficientdets and faceboxes to models.lst and test cases
> object detection demo models

- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
Add ability to launch TF models with LSTM_INPUT in configuration
> Add LSTM inputs to TF_Launcher

- tools/accuracy_checker/accuracy_checker/metrics/im2latex_images_match.py
Some fixes to make AC for im2latex models work on windows correctly
> Fix im2latex AC on windows

- models/public/aclnet/aclnet.md
- models/public/aclnet/model.yml
- models/public/cocosnet/cocosnet.md
- models/public/cocosnet/model.yml
- models/public/faceboxes-pytorch/faceboxes-pytorch.md
- models/public/faceboxes-pytorch/model.yml
- models/public/fast-neural-style-mosaic-onnx/fast-neural-style-mosaic-onnx.md
- models/public/fast-neural-style-mosaic-onnx/model.yml
- models/public/faster_rcnn_inception_resnet_v2_atrous_coco/faster_rcnn_inception_resnet_v2_atrous_coco.md
- models/public/faster_rcnn_inception_resnet_v2_atrous_coco/model.yml
- models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md
- models/public/faster_rcnn_inception_v2_coco/model.yml
- models/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.md
- models/public/faster_rcnn_resnet101_coco/model.yml
- models/public/faster_rcnn_resnet50_coco/faster_rcnn_resnet50_coco.md
- models/public/faster_rcnn_resnet50_coco/model.yml
- models/public/forward-tacotron/description/forward-tacotron.md
- models/public/mobilefacedet-v1-mxnet/mobilefacedet-v1-mxnet.md
- models/public/mobilefacedet-v1-mxnet/model.yml
- models/public/pelee-coco/model.yml
- models/public/pelee-coco/pelee-coco.md
- models/public/resnest-50-pytorch/model.yml
- models/public/resnest-50-pytorch/resnest-50-pytorch.md
- models/public/shufflenet-v2-x1.0/model.yml
- models/public/shufflenet-v2-x1.0/shufflenet-v2-x1.0.md
- models/public/wavernn/description/wavernn.md
- tools/accuracy_checker/accuracy_checker/metrics/README.md
* Link to the newest version instead of specific versions
* Link to the abstract instead of the full text
> Normalize arXiv links

- tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/metric.py
- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessor.py
- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessor.py
- tools/accuracy_checker/tests/test_config_validator.py
do not mixup position in config and parameter name
> AC: fix uri tracing

- demos/python_demos/action_recognition/README.md
- demos/python_demos/action_recognition/action_recognition.py
- demos/python_demos/action_recognition/action_recognition_demo/result_renderer.py
- demos/python_demos/action_recognition/action_recognition_demo/steps.py
- demos/python_demos/action_recognition/action_recognition_demo/timer.py
- demos/python_demos/colorization_demo/README.md
- demos/python_demos/colorization_demo/colorization_demo.py
- demos/python_demos/human_pose_estimation_3d_demo/README.md
- demos/python_demos/human_pose_estimation_3d_demo/human_pose_estimation_3d_demo.py
- demos/python_demos/human_pose_estimation_demo/README.md
- demos/python_demos/human_pose_estimation_demo/human_pose_estimation.py
- demos/python_demos/image_retrieval_demo/README.md
- demos/python_demos/image_retrieval_demo/image_retrieval_demo.py
- demos/python_demos/image_retrieval_demo/image_retrieval_demo/visualizer.py
- demos/python_demos/instance_segmentation_demo/README.md
- demos/python_demos/instance_segmentation_demo/instance_segmentation_demo.py
- demos/python_demos/object_detection_demo/README.md
- demos/python_demos/object_detection_demo/object_detection_demo.py
- demos/python_demos/segmentation_demo/README.md
- demos/python_demos/segmentation_demo/segmentation_demo.py
- demos/python_demos/single_human_pose_estimation_demo/README.md
- demos/python_demos/single_human_pose_estimation_demo/single_human_pose_estimation_demo.py
- demos/python_demos/whiteboard_inpainting_demo/README.md
- demos/python_demos/whiteboard_inpainting_demo/whiteboard_inpainting_demo.py
This PR is intended to add demo capability to write output, which usually shown on screen to video file, using motion jpeg as an encoder.
> Python demos: add capability to record output video in a file

- demos/CMakeLists.txt
- demos/classification_demo/cpp/CMakeLists.txt
- demos/common/cpp/models/CMakeLists.txt
- demos/common/cpp/pipelines/CMakeLists.txt
- demos/gaze_estimation_demo/cpp/CMakeLists.txt
- demos/human_pose_estimation_demo/cpp/CMakeLists.txt
- demos/interactive_face_detection_demo/cpp/CMakeLists.txt
- demos/interactive_face_detection_demo/cpp_gapi/CMakeLists.txt
- demos/multi_channel_common/cpp/CMakeLists.txt
- demos/multi_channel_face_detection_demo/cpp/CMakeLists.txt
- demos/multi_channel_human_pose_estimation_demo/cpp/CMakeLists.txt
- demos/multi_channel_object_detection_demo_yolov3/cpp/CMakeLists.txt
- demos/object_detection_demo/cpp/CMakeLists.txt
- demos/pedestrian_tracker_demo/cpp/CMakeLists.txt
- demos/security_barrier_camera_demo/cpp/CMakeLists.txt
- demos/segmentation_demo/cpp/CMakeLists.txt
- demos/smart_classroom_demo/cpp/CMakeLists.txt
- demos/text_detection_demo/cpp/CMakeLists.txt
These were found with cmakelint.
> Fix CMake style issues

- models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md
correct input and output info provided for emotion recognition
> fix input/output names for emotion recognition model

- models/public/fastseg-large/model.yml
- models/public/fastseg-small/model.yml
This doesn't affect the generated ONNX files.
> fastseg-*: disable unnecessary downloads during conversion

- tools/accuracy_checker/accuracy_checker/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/adapter.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/metrics/metric.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
- tools/accuracy_checker/accuracy_checker/postprocessor/postprocessor.py
- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessor.py
- tools/accuracy_checker/tests/test_config_validator.py
provided access to config validation scheme via API for config generation purpoces.
added small fixes for config validation API
> AC: support validation scheme API

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/yolo.py
support yolo v3 tf2 example from https://github.com/YunYang1994/TensorFlow2.0-Examples/tree/master/4-Object_Detection/YOLOV3
> AC: support YOLO V3 tf2

- tools/accuracy_checker/accuracy_checker/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/adapter.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/tests/test_dataset.py
- tools/accuracy_checker/tests/test_model_evaluator.py
> AC: support subset dumping/selection using file

- demos/security_barrier_camera_demo/cpp/main.cpp
Close https://github.com/openvinotoolkit/open_model_zoo/issues/2040
> security_barrier_camera: downgrade frameCounter to 32-bit

- demos/text_to_speech_demo/python/requirements.txt
- demos/text_to_speech_demo/python/utils/text_preprocessing.py
Removed dependency with unresolved license
> Removed unused dependency

- demos/common/python/models/segmentation.py
- demos/image_retrieval_demo/python/image_retrieval_demo.py
- demos/place_recognition_demo/python/README.md
- demos/place_recognition_demo/python/place_recognition_demo.py
+Deleted unused code in `segmentation.py`.
> image_retrieval, place_recognition demos: fix the opening of VideoWriter

- demos/common/cpp/models/include/models/detection_model_retinaface.h
- demos/common/cpp/models/src/detection_model_retinaface.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/cpp/models.lst
- demos/tests/cases.py
Added support for ssh-mxnet model.
> cpp object detection demo: ssh-mxnet support

- models/intel/person-detection-retail-0002/description/person-detection-retail-0002.md
> add class id to model description

- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/models.lst
- demos/object_detection_demo/python/object_detection_demo.py
- demos/tests/cases.py
Model type retina could be a little confusing because we have retinanet model and it differs from retinaface models, so it's would be good to use more specific and clear name - retinaface.
>  py object detection demo: model type name retina changed to retinaface in args 

- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/README.md
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/sr_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
Introduces ability to pass data from model output to model input at evaluator level
> Custom evaluator with data feedback

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
Added the ability to generate  CoCoInstanceSegmentationAnnotation or  SegmentationAnnotation with VOC labels.
> AC: Added support for using COCO dataset with VOC labels

- demos/common/cpp/models/include/models/associative_embedding_decoder.h
- demos/common/cpp/models/include/models/hpe_model_associative_embedding.h
- demos/common/cpp/models/src/associative_embedding_decoder.cpp
- demos/common/cpp/models/src/hpe_model_associative_embedding.cpp
- demos/human_pose_estimation_demo/python/human_pose_estimation_demo/decoder_ae.py
- models/intel/human-pose-estimation-0005/description/human-pose-estimation-0005.md
- models/intel/human-pose-estimation-0006/description/human-pose-estimation-0006.md
- models/intel/human-pose-estimation-0007/description/human-pose-estimation-0007.md
- tools/accuracy_checker/accuracy_checker/adapters/pose_estimation_associative_embedding.py
Changelog:
- Added support of human-pose-estimation-0005/0006/0007 models.
- Made changes to C++ postprocessing code to align it with the changes from #2063.
- Made a minor change in the Python postprocessing. Updated models' metrics accordingly.
- Found and fixed some errors in C++ postprocessing.
- Speed up postprocessing (at least I see the boost on my laptop).
> Human Pose Estimation C++ demo fixes and update

- models/intel/text-recognition-0013/description/text-recognition-0013.md
Update description since model weights and architecture changed.
> update info about text-rec-13

- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/kenlm_v5_loader.cpp
- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/kenlm_v5_loader.hpp
- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/language_model.cpp
- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/language_model.hpp
- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/memory_section.cpp
- demos/speech_recognition_demo/python/ctcdecode-numpy/ctcdecode_numpy/yoklm/memory_section.hpp
Refactor yoklm C++ lib for n-gram Language Model inference inside Speech Recognition Demo. Improve resilience to broken LM files.
This commit can go in any order relative to the commit that adds online mode to Speech Recognition Demo.
> Speech recognition demo: Refactor yoklm C++ library

- models/intel/text-spotting-0004/accuracy-check.yml
- models/intel/text-spotting-0004/description/text-spotting-0004.md
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
- tools/accuracy_checker/accuracy_checker/metrics/text_detection.py
one more fix to match AC metric to original one
> very last fix for text-spotting-0004

- tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
* create the files securely, by using `NamedTemporaryFile` (previously, the file created by `NamedTemporaryFile` was unused).
* delete the files after they are no longer needed.
> AC: Fix temporary file usage in MSCOCOorigBaseMetric

- demos/README.md
- demos/common/python/models/deblurring.py
Add demo to list of demos and copy preprocessing and postprocessing from c++ image_processing demo.
> Micro changes to simplify deblurring_demo py

- ci/documentation_updater/README.md
- demos/action_recognition_demo/python/README.md
- demos/bert_question_answering_demo/python/README.md
- demos/bert_question_answering_embedding_demo/python/README.md
- demos/classification_demo/cpp/README.md
- demos/formula_recognition_demo/python/README.md
- demos/gesture_recognition_demo/python/README.md
- demos/handwritten_text_recognition_demo/python/README.md
- demos/human_pose_estimation_3d_demo/python/README.md
- demos/image_retrieval_demo/python/README.md
- demos/multi_camera_multi_target_tracking_demo/python/README.md
- demos/multi_channel_face_detection_demo/cpp/README.md
- demos/multi_channel_human_pose_estimation_demo/cpp/README.md
- demos/multi_channel_object_detection_demo_yolov3/cpp/README.md
- demos/place_recognition_demo/python/README.md
- demos/segmentation_demo/cpp/README.md
- demos/single_human_pose_estimation_demo/python/README.md
- demos/speech_recognition_demo/python/README.md
- demos/text_detection_demo/cpp/README.md
- demos/text_spotting_demo/python/README.md
- demos/text_to_speech_demo/python/README.md
- demos/whiteboard_inpainting_demo/python/README.md
- models/public/aclnet-int8/aclnet-int8.md
- models/public/aclnet/aclnet.md
- models/public/ssd300/ssd300.md
- models/public/ssd512/ssd512.md
unified docs and fixed link to non markdown files
> unify docs and fix non markdown links

- demos/common/python/models/__init__.py
- demos/common/python/models/yolo.py
- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/models.lst
- demos/object_detection_demo/python/object_detection_demo.py
- demos/tests/cases.py
Awaits [PR 1978](https://github.com/openvinotoolkit/open_model_zoo/pull/1978). **DONE**
> Yolov4 demo support

- demos/formula_recognition_demo/python/utils.py
- tools/downloader/downloader.py
> Improve temporary file handling in formula_recognition_demo and Model Downloader

- demos/object_detection_demo/python/object_detection_demo.py
cv::circle expect center arg to be integer but landmark is float, so need casting  to int
> fix cv circle arg

- demos/instance_segmentation_demo/python/instance_segmentation_demo.py
- demos/instance_segmentation_demo/python/instance_segmentation_demo/model_utils.py
- fix for case if all boxes filtered by threshold
- removed aspect ratio preserving mode (model does not support it) for yolact
> demos: fix instance segmentation demo for yolact

- tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
current data reading approch does not allow non-unique names as identifiers. Changed identifier for single human pose estimation
> AC: fix single human pose estimation

- models/intel/icnet-camvid-ava-0001/description/icnet-camvid-ava-0001.md
- models/intel/icnet-camvid-ava-sparse-30-0001/description/icnet-camvid-ava-sparse-30-0001.md
- models/intel/icnet-camvid-ava-sparse-60-0001/description/icnet-camvid-ava-sparse-60-0001.md
- models/intel/unet-camvid-onnx-0001/description/unet-camvid-onnx-0001.md
add 12 CamVid classes description
> camvid classes description

- models/public/fastseg-large/fastseg-large.md
- models/public/fastseg-small/fastseg-small.md
add reference to Cityscapes classes description
> fastseg classes description

- models/public/common-sign-language-0001/model.yml
The task it performs is clearly more akin to action recognition than object attribute estimation. In fact, its interface is almost exactly like that of `i3d-rgb-tf`.
> common-sign-language-0001: fix the task type

- demos/common/cpp/models/include/models/detection_model_faceboxes.h
- demos/common/cpp/models/include/models/detection_model_retinaface.h
- demos/common/cpp/models/src/detection_model_faceboxes.cpp
- demos/common/cpp/models/src/detection_model_retinaface.cpp
- demos/common/cpp/utils/include/utils/nms.hpp
- demos/common/python/models/ctpn.py
- demos/common/python/models/faceboxes.py
- demos/common/python/models/retinaface.py
- demos/common/python/models/utils.py
- demos/instance_segmentation_demo/python/instance_segmentation_demo.py
- demos/instance_segmentation_demo/python/instance_segmentation_demo/model_utils.py
Non-maximum Suppression is applied by several models, so is better to create the common place with implementation instead of having one in every model file.
It is moved to `models/utils.py` for python demos and to `utils/nms.hpp` for c++ demos.
> Demos: move nms function

- demos/gesture_recognition_demo/python/gesture_recognition_demo.py
- demos/tests/run_tests.py
Update run_tests.py just in case
> gesture_recognition: workaround multiprocessing for mac

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/im2latex.py
> AC docs: fix  converter name in description

- demos/common/python/models/__init__.py
- demos/common/python/models/ultra_lightweight_face_detection.py
- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/models.lst
- demos/object_detection_demo/python/object_detection_demo.py
- demos/tests/cases.py
- models/public/index.md
- models/public/ultra-lightweight-face-detection-rfb-320/accuracy-check.yml
- models/public/ultra-lightweight-face-detection-rfb-320/model.yml
- models/public/ultra-lightweight-face-detection-rfb-320/ultra-lightweight-face-detection-rfb-320.md
- models/public/ultra-lightweight-face-detection-slim-320/accuracy-check.yml
- models/public/ultra-lightweight-face-detection-slim-320/model.yml
- models/public/ultra-lightweight-face-detection-slim-320/ultra-lightweight-face-detection-slim-320.md
- tools/accuracy_checker/configs/ultra-lightweight-face-detection-rfb-320.yml
- tools/accuracy_checker/configs/ultra-lightweight-face-detection-slim-320.yml
> Added ultra-lightweight-face-detection models

- demos/colorization_demo/python/README.md
- demos/colorization_demo/python/colorization_demo.py
- demos/crossroad_camera_demo/cpp/README.md
- demos/crossroad_camera_demo/cpp/crossroad_camera_demo.hpp
- demos/gaze_estimation_demo/cpp/README.md
- demos/gaze_estimation_demo/cpp/gaze_estimation_demo.hpp
- demos/human_pose_estimation_demo/cpp/README.md
- demos/human_pose_estimation_demo/cpp/main.cpp
- demos/interactive_face_detection_demo/cpp/README.md
- demos/interactive_face_detection_demo/cpp/interactive_face_detection.hpp
- demos/interactive_face_detection_demo/cpp_gapi/README.md
- demos/interactive_face_detection_demo/cpp_gapi/interactive_face_detection_gapi.hpp
- demos/multi_channel_common/cpp/multichannel_params.hpp
- demos/multi_channel_face_detection_demo/cpp/README.md
- demos/multi_channel_face_detection_demo/cpp/main.cpp
- demos/multi_channel_human_pose_estimation_demo/cpp/README.md
- demos/multi_channel_human_pose_estimation_demo/cpp/main.cpp
- demos/multi_channel_object_detection_demo_yolov3/cpp/README.md
- demos/multi_channel_object_detection_demo_yolov3/cpp/main.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/pedestrian_tracker_demo/cpp/README.md
- demos/pedestrian_tracker_demo/cpp/include/pedestrian_tracker_demo.hpp
- demos/security_barrier_camera_demo/cpp/README.md
- demos/security_barrier_camera_demo/cpp/security_barrier_camera_demo.hpp
- demos/segmentation_demo/cpp/README.md
- demos/segmentation_demo/cpp/main.cpp
- demos/smart_classroom_demo/cpp/README.md
- demos/smart_classroom_demo/cpp/include/smart_classroom_demo.hpp
Close https://github.com/openvinotoolkit/open_model_zoo/issues/391
> demos: unify no_show

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/brats.py
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/representation/__init__.py
- tools/accuracy_checker/accuracy_checker/representation/regression_representation.py
Added special mode to brats annotation converter and nifti reader to implement 2D processing of Pacnreas-CT data.
> Support for Pancreas-CT dataset

- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/asr_encoder_decoder_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/asr_encoder_prediction_joint_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/cocosnet_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/colorization_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/i3d_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/im2latex_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/lpcnet_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/sequential_action_recognition_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/sr_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_to_speech_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/pdpd_launcher.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/tests/test_dlsdk_launcher.py
Expanded models argument to accept files and dirs and added printing of found model/weights in all cases
> Expanded models argument to accept files and dirs

- demos/CMakeLists.txt
`GENERATOR_IS_MULTI_CONFIG` as variable is not defined
> demos/CMakeLists.txt: read GENERATOR_IS_MULTI_CONFIG correctly

- models/intel/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md
- models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md
- models/intel/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.md
- models/intel/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.md
- models/intel/vehicle-detection-adas-0002/description/vehicle-detection-adas-0002.md
- models/intel/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.md
add missed classes description
cc @snosov1
> add missed classes description

- demos/multi_camera_multi_target_tracking_demo/python/README.md
fixed some phrasing in demo's README.md
> fix README language

- models/intel/index.md
> update intel models index

- models/public/efficientdet-d0-tf/model.yml
- models/public/efficientdet-d0-tf/pre-convert.py
- models/public/efficientdet-d1-tf/model.yml
- models/public/efficientdet-d1-tf/pre-convert.py
See commit messages for details.
> efficientdet-*-tf: fix conversion issues

- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/README.md
I think this fixes the last broken external link in OMZ. 😌
> AC: update links in custom_evaluators/README.md

- .gitattributes
Documentation job triggering on changes to any documentation files
> Added documentation job attribute for all .md files

- demos/README.md
> update supported devices

- demos/tests/cases.py
- demos/text_detection_demo/cpp/README.md
- demos/text_detection_demo/cpp/include/text_recognition.hpp
- demos/text_detection_demo/cpp/main.cpp
- demos/text_detection_demo/cpp/models.lst
- demos/text_detection_demo/cpp/src/text_recognition.cpp
- demos/text_detection_demo/cpp/text_detection_demo.hpp
- models/intel/text-recognition-0013/README.md
- models/public/text-recognition-resnet-fc/README.md
- models/public/text-recognition-resnet-fc/accuracy-check.yml
- models/public/text-recognition-resnet-fc/model.yml
Add new `text-recognition-resnet-fc` model for text detection demo.
> Support text-recognition-resnet-fc for text_detection_demo

- demos/common/cpp/utils/include/utils/common.hpp
And replace deprecated exception API
> Added iostream include

- demos/common/cpp/utils/include/utils/common.hpp
- demos/common/cpp/utils/include/utils/ocv_common.hpp
- demos/pedestrian_tracker_demo/cpp/main.cpp
- demos/pedestrian_tracker_demo/cpp/src/cnn.cpp
- demos/pedestrian_tracker_demo/cpp/src/detector.cpp
- demos/smart_classroom_demo/cpp/src/action_detector.cpp
- demos/smart_classroom_demo/cpp/src/cnn.cpp
- demos/smart_classroom_demo/cpp/src/detector.cpp
- demos/text_detection_demo/cpp/src/cnn.cpp
Replaced IE exceptions with std::runtime_error.
> Replace IE exceptions

- demos/common/cpp/models/include/models/internal_model_data.h
- demos/common/cpp/models/src/segmentation_model.cpp
- demos/common/cpp/pipelines/src/async_pipeline.cpp
- demos/common/python/models/segmentation.py
- demos/segmentation_demo/cpp/main.cpp
remove forcing FP32 output blob type
> fix segmentation demo

- demos/README.md
- models/public/index.md
Changed models/public/index.md and demos/README.md
> Add missing links to README.md files of demos and models

- README.md
> update legal notice

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/accuracy_checker/annotation_converters/image_processing.py
- tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
- tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/preprocessor/normalization.py
- tools/accuracy_checker/tests/test_preprocessor.py
and extended tests for normalization
> AC: support image processing with variable parameters

- demos/CMakeLists.txt
Currently, this version does not mean something.
> Removed IE version from find_package

- demos/interactive_face_detection_demo/cpp/detectors.cpp
- demos/interactive_face_detection_demo/cpp_gapi/README.md
- demos/interactive_face_detection_demo/cpp_gapi/interactive_face_detection_gapi.hpp
- demos/interactive_face_detection_demo/cpp_gapi/main.cpp
- demos/object_detection_demo/python/README.md
Fix issue with landmarks distortion in case then more than one face is detected on image in interactive_face_detection_demo. Modify `-o` option, add `-limit` option in interactive_face_detection_gapi.
> Modify interactive_face_detection_demo

- ci/check-documentation.py
Checks for links to README.md files of models and demos in models/intel/index.md, models/public/index.md and demos/README.md.
> Move checking for links to README.md files from CI to OMZ repo

- ci/requirements-conversion.txt
- tools/downloader/requirements-caffe2.in
- tools/downloader/requirements-pytorch.in
- tools/downloader/requirements-tensorflow.in
- tools/downloader/requirements.in
Set more strict (`>=`, some pinned as `~=`) pip requirements for downloader, aligned over other OpenVINO components
Internal ticket 48358
> Set more strict pip requirements for Downloader

- ci/requirements-ac-test.txt
- ci/requirements-ac.txt
- ci/requirements-quantization.txt
- tools/accuracy_checker/requirements-core.in
- tools/accuracy_checker/requirements.in
Experiment to set more strict (~=) pip requirements for AC
Internal ticket 48358
> Set more strict requirements for Accuracy Checker

- demos/machine_translation_demo/python/README.md
- demos/machine_translation_demo/python/machine_translation_demo.py
Add `-d`, `-o` options, modify `-i` option (now demo can accept a .txt file as input).
> Modify machine_translation_demo

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/nyu_depth.py
Fixed nyu_depth_v2 converter behavior with converting from original format to maintain backward compatibility. Updated README.
> AC: Fixed nyu_depth_v2 converter

- tools/accuracy_checker/accuracy_checker/metrics/README.md
- Added description of metric units  and directions of growth for each metric
- Added description of missing metrics
- Fixed typos
> AC: Updated README for metrics

- demos/3d_segmentation_demo/python/README.md
- demos/action_recognition_demo/python/README.md
- demos/bert_question_answering_demo/python/models.lst
- demos/formula_recognition_demo/python/README.md
- demos/gesture_recognition_demo/python/README.md
- demos/human_pose_estimation_3d_demo/python/README.md
- demos/image_retrieval_demo/python/README.md
- demos/multi_camera_multi_target_tracking_demo/python/README.md
- demos/place_recognition_demo/python/README.md
- demos/tests/cases.py
- demos/whiteboard_inpainting_demo/python/README.md
- models/intel/bert-large-uncased-whole-word-masking-squad-0001/README.md
- models/intel/bert-large-uncased-whole-word-masking-squad-int8-0001/README.md
Fix descriptions for the demos:
> fix demo descriptions

- demos/common/cpp/models/src/detection_model_ssd.cpp
Additionally, maybe this will suppress code analyzer warning.
> demos: specify range var type

- tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/accuracy_checker/annotation_converters/yolo_labeling_converter.py
Added support of different directories for annotations and images. Fixed labels generation for datasets with one label.
> AC: Updated yolo_labeling converter

- tools/accuracy_checker/accuracy_checker/adapters/kaldi_asr_decoder.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/metrics/speech_recognition.py
connected with https://github.com/openvinotoolkit/openvino/pull/5731
> AC: add memory resetting option

- tools/accuracy_checker/README.md
- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/pdpd_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf2_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/metrics/README.md
- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
- tools/accuracy_checker/accuracy_checker/preprocessor/README.md
Added missing descriptions, fixed typos
> Updated documentation for AC

- models/public/device_support.md
update mixnet-l supported devices on base of validation results
> mixnet-l supported devices

- demos/tests/cases.py
Added models:
**bert_question_answering_demo**:
- bert-small-uncased-whole-word-masking-squad-int8-0002
- bert-large-uncased-whole-word-masking-squad-0001 (has I/O layer naming issues)
- bert-large-uncased-whole-word-masking-squad-int8-0001 (has I/O layer naming issues)
**bert_question_answering_embedding_demo**:
- bert-small-uncased-whole-word-masking-squad-emb-int8-0001
> Added BERT-* models in demo testing

- tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/base_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/module_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/accuracy_checker/utils.py
> AC: telemetry

- demos/common/python/models/__init__.py
- demos/common/python/models/retinaface.py
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/models.lst
- demos/object_detection_demo/python/object_detection_demo.py
- demos/tests/cases.py
- models/public/device_support.md
- models/public/index.md
- models/public/retinaface-resnet50-pytorch/README.md
- models/public/retinaface-resnet50-pytorch/accuracy-check.yml
- models/public/retinaface-resnet50-pytorch/model.py
- models/public/retinaface-resnet50-pytorch/model.yml
- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/retinaface.py
- tools/accuracy_checker/configs/retinaface-resnet50-pytorch.yml
> Added retinaface-resnet50-pytorch model

- models/intel/bert-large-uncased-whole-word-masking-squad-0001/README.md
- models/intel/bert-large-uncased-whole-word-masking-squad-0001/accuracy-check.yml
- models/intel/bert-large-uncased-whole-word-masking-squad-int8-0001/README.md
- models/intel/bert-large-uncased-whole-word-masking-squad-int8-0001/accuracy-check.yml
Note: test cases in demo testing are not updated as part of this request. It should be done, when model package will be uploaded
> [Docs]: update input/outputs for bert large

- demos/face_recognition_demo/python/README.md
- demos/face_recognition_demo/python/models.lst
- demos/smart_classroom_demo/cpp/README.md
- demos/smart_classroom_demo/cpp/models.lst
- demos/tests/cases.py
- models/public/device_support.md
- models/public/face-recognition-resnet100-arcface-onnx/README.md
- models/public/face-recognition-resnet100-arcface-onnx/accuracy-check.yml
- models/public/face-recognition-resnet100-arcface-onnx/model.yml
- models/public/index.md
- tools/accuracy_checker/configs/face-recognition-resnet100-arcface-onnx.yml
> Added face-recognition-resnet100-arface model from ONNX Zoo

- models/intel/text-recognition-0014/README.md
- models/intel/text-recognition-0015/README.md
rescale vals to align with previous models
> new text-recognition ref vals

- demos/tests/cases.py
> sorting test cases in alphabet order

- demos/text_to_speech_demo/python/README.md
- demos/text_to_speech_demo/python/models.lst
- demos/text_to_speech_demo/python/text_to_speech_demo.py
add text-to-speech-en-0001 models to demo description
> update text_to_speech_demo description

- demos/smart_classroom_demo/cpp/README.md
> update smart_classroom_demo doc

- models/public/yolo-v4-tiny-tf/README.md
update yolo-v4-tiny-tf ref vals based on validation
> update yolo-v4-tiny-tf reference vals

- tools/accuracy_checker/.pylintrc
- tools/accuracy_checker/accuracy_checker/metrics/image_quality_assessment.py
- tools/accuracy_checker/setup.cfg
lpips metric has issues with downloading in global environment. Rewritten metric evaluation pipeline to avoid this behavior
> AC: replace model loading in lpips

- tools/accuracy_checker/.pylintrc
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/lpcnet_evaluator.py
- tools/accuracy_checker/accuracy_checker/metrics/image_quality_assessment.py
- tools/accuracy_checker/requirements.in
- tools/accuracy_checker/setup.cfg
> AC: port bugfixes to release

- models/intel/device_support.md
- models/public/device_support.md
update models device support table
> update device support tables

- tools/accuracy_checker/accuracy_checker/adapters/README.md
- tools/accuracy_checker/accuracy_checker/adapters/__init__.py
- tools/accuracy_checker/accuracy_checker/adapters/detection.py
- tools/accuracy_checker/accuracy_checker/config/config_validator.py
- tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/accuracy_checker/launcher/launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/pdpd_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf2_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher_readme.md
- tools/accuracy_checker/tests/test_input_feeder.py
> initial support pdpd detection models

- demos/classification_demo/cpp/README.md
- demos/classification_demo/cpp/grid_mat.hpp
- demos/classification_demo/cpp/main.cpp
In a few cases might occur zero division exception ( for example - when you try to open GUI on remote machine, imshow took long time to open and `targetFPS` parameter got 0). Also added feature that allows repeating testing.
> Classification demo: fixed zero division exception, added feature to repeat testing.

- demos/common/python/models/open_pose.py
The order for model converted with latest OpenVINO has changed
> demos/py/human_pose_estimation/open_pose: don't rely on output_ops order in ng Function

- models/intel/handwritten-simplified-chinese-recognition-0001/README.md
Update the model description as the previous one is not accurate.
> Update the README for handwritten-simplified-chinese-recognition-0001.

- demos/common/cpp/models/include/models/detection_model_retinaface_pt.h
- demos/common/cpp/models/src/detection_model_retinaface_pt.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/cpp/models.lst
- demos/tests/cases.py
> retinaface-resnet50-pytorch C++ model wrapper

- demos/handwritten_text_recognition_demo/python/README.md
- demos/handwritten_text_recognition_demo/python/handwritten_text_recognition_demo.py
- demos/image_inpainting_demo/python/README.md
- demos/image_inpainting_demo/python/image_inpainting_demo.py
- demos/multi_camera_multi_target_tracking_demo/python/README.md
- demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
- demos/segmentation_demo/python/README.md
- demos/segmentation_demo/python/segmentation_demo.py
- demos/speech_recognition_deepspeech_demo/python/README.md
- demos/speech_recognition_deepspeech_demo/python/speech_recognition_deepspeech_demo.py
- demos/speech_recognition_quartznet_demo/python/README.md
- demos/speech_recognition_quartznet_demo/python/speech_recognition_quartznet_demo.py
- demos/tests/cases.py
- demos/text_to_speech_demo/python/README.md
- demos/text_to_speech_demo/python/text_to_speech_demo.py
- demos/time_series_forecasting_demo/python/time_series_forecasting_demo.py
In addition, made `--input` as required argument in _image_inpainting_demo_, _time_series_forecasting_demo_
> Python demos: add "Required" to parameters helping messages

- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/base_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/object_detection_metric_profiler.py
> AC: update metric profiler logic

- demos/segmentation_demo/python/segmentation_demo.py
It is aligned according to the other print_raw_results() functions
> Update logging in segmentation_demo.py print_raw_results()

- demos/common/python/models/yolo.py
- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/object_detection_demo.py
- Total classes now resolved by heuristic from output blobs
- Fix error for tiny model modification
- The anchors and mask are parametrizable now
- The `py/object_detection_demo` can set anchors and masks for YOLOV4
> Update ModelAPI for YoloV4

- ci/dependencies.yml
> update OpenVINO version to the latest release

- demos/classification_demo/cpp/README.md
- demos/classification_demo/cpp/grid_mat.hpp
- demos/classification_demo/cpp/main.cpp
PR #2514 : Classification demo: fixed zero division exception, added feature to repeat testing.
> cpp classification demo fix

- ci/suppressed-devices.txt
- models/public/device_support.md
> update suppression list

- demos/common/cpp/models/include/models/detection_model_yolo.h
- demos/common/cpp/models/src/detection_model_yolo.cpp
- demos/multi_channel_object_detection_demo_yolov3/cpp/main.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/cpp/models.lst
> add yolov2 support

- tools/accuracy_checker/accuracy_checker/postprocessor/README.md
> AC docs: fix postprocessing documentation

- demos/common/cpp/models/include/models/detection_model_yolo.h
- demos/common/cpp/models/src/detection_model_yolo.cpp
- demos/multi_channel_object_detection_demo_yolov3/cpp/main.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/cpp/models.lst
* Support for Yolo V1, V2
* Docs update
* Fixes based on comments
* fix warning
Co-authored-by: Fedor Zharinov <Fedor.Zharinov@intel.com>
> add yolov2 support (#2620)

- demos/common/cpp/utils/include/utils/config_factory.h
- demos/common/cpp/utils/src/config_factory.cpp
Minor imrovements in config factory.
> cpp demos: changed getDevices implementation in config factory.

- demos/social_distance_demo/cpp/main.cpp
Follow up https://github.com/openvinotoolkit/open_model_zoo/pull/2071
> social_distance: downgrade frameCounter to 32-bit

- tools/accuracy_checker/accuracy_checker/__init__.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/accuracy_checker/preprocessor/audio_preprocessing.py
- tools/accuracy_checker/accuracy_checker/preprocessor/audio_preprocessing_ext.py
- tools/accuracy_checker/accuracy_checker/preprocessor/brats_preprocessing.py
- tools/accuracy_checker/accuracy_checker/preprocessor/centernet_preprocessing.py
- tools/accuracy_checker/accuracy_checker/preprocessor/crop.py
- tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/accuracy_checker/preprocessor/nlp_preprocessors.py
- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessing_executor.py
- tools/accuracy_checker/accuracy_checker/preprocessor/preprocessor.py
- tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
- tools/accuracy_checker/tests/test_dlsdk_launcher.py
- tools/accuracy_checker/tests/test_model_evaluator.py
> AC: handle undefined input shape provided in IR

- ci/prepare-documentation.py
Check for .md files (that are referenced by other online documentation files) existence in the online documentation.
> Added check for relative links to online documentation files

- demos/common/cpp/models/src/classification_model.cpp
- demos/common/cpp/models/src/deblurring_model.cpp
- demos/common/cpp/models/src/hpe_model_associative_embedding.cpp
- demos/common/cpp/models/src/hpe_model_openpose.cpp
- demos/smart_classroom_demo/cpp_gapi/main.cpp
Replaced remaing `\n` with` slog::endl` and made print statstream only if it isn't emtpy.
> cpp demos: logging fix

- tools/accuracy_checker/README.md
- tools/accuracy_checker/accuracy_checker/adapters/segmentation.py
- tools/accuracy_checker/accuracy_checker/adapters/ssd.py
- tools/accuracy_checker/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/accuracy_checker/launcher/__init__.py
- tools/accuracy_checker/accuracy_checker/launcher/gapi_launcher.py
- tools/accuracy_checker/accuracy_checker/launcher/gapi_launcher_readme.md
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/tests/test_gapi_launcher.py
> AC: G-API based launcher POC

- demos/security_barrier_camera_demo/cpp/net_wrappers.hpp
- models/public/license-plate-recognition-barrier-0007/README.md
adopt to model license-plate-recognition-0007 I32 output blob type
> security barrier camera demo fix

- demos/common/cpp/models/include/models/detection_model_retinaface_pt.h
- demos/common/cpp/models/src/detection_model_retinaface_pt.cpp
- demos/object_detection_demo/cpp/README.md
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/cpp/models.lst
- demos/tests/cases.py
Merging separately to release branch
> C++ Model API support for retinaface resnet50 (to 2021.4.1 release), CVS-61892

- demos/gesture_recognition_demo/python/gesture_recognition_demo/action_recognizer.py
- demos/gesture_recognition_demo/python/gesture_recognition_demo/common.py
- demos/gesture_recognition_demo/python/gesture_recognition_demo/person_detector.py
Action recognizer infers only in sync mode, person tracker infers only in async mode, so removed methods are useless.
> Code refactoring in python gesture recognition demo

- tools/accuracy_checker/accuracy_checker/launcher/gapi_launcher.py
FYI @Wovchena @azhogov  it is fix for pip-conflict (have no relation on dependency installation really
> AC: align imports of ie

- demos/classification_demo/cpp/README.md
- demos/classification_demo/cpp/models.lst
- demos/tests/cases.py
- models/public/device_support.md
- models/public/index.md
- models/public/shufflenet-v2-x0.5/README.md
- models/public/shufflenet-v2-x0.5/accuracy-check.yml
- models/public/shufflenet-v2-x0.5/model.yml
- tools/accuracy_checker/configs/shufflenet-v2-x0.5.yml
model added to test MO operations coverage
> Add Caffe model shufflenet-v2-x0.5

- models/intel/noise-suppression-poconetlike-0001/README.md
- models/intel/noise-suppression-poconetlike-0001/accuracy-check.yml
- models/intel/noise-suppression-poconetlike-0001/model.yml
update model and download link
> update noise-suppression-poconetlike-0001 weights

- tools/accuracy_checker/accuracy_checker/dataset.py
- tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/accuracy_checker/main.py
- tools/accuracy_checker/accuracy_checker/metrics/classification.py
- tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py
- tools/accuracy_checker/accuracy_checker/metrics/detection.py
- tools/accuracy_checker/accuracy_checker/metrics/metric.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/__init__.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/base_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/classifcation_metric_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/instance_segmentation_metric_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/object_detection_metric_profiler.py
- tools/accuracy_checker/accuracy_checker/metrics/metric_profiler/profiling_executor.py
- tools/accuracy_checker/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/accuracy_checker/presenters.py
- tools/accuracy_checker/tests/test_dlsdk_launcher.py
- tools/accuracy_checker/tests/test_presenter.py
- tools/accuracy_checker/tests/test_regression_metrics.py
- tools/accuracy_checker/tests/test_segmentation_metrics.py
port metric profiling functionality to release
> AC: provide metric analytics to release

- demos/common/cpp/monitors/src/cpu_monitor.cpp
- demos/common/cpp/monitors/src/memory_monitor.cpp
> Fix for mean values calculations

- data/dataset_definitions.yml
- demos/README.md
- demos/gpt2_text_prediction_demo/python/README.md
- demos/gpt2_text_prediction_demo/python/gpt2_text_prediction/generation_utils.py
- demos/gpt2_text_prediction_demo/python/gpt2_text_prediction_demo.py
- demos/gpt2_text_prediction_demo/python/models.lst
- demos/tests/cases.py
- models/public/device_support.md
- models/public/gpt-2/README.md
- models/public/gpt-2/accuracy-check.yml
- models/public/gpt-2/model.py
- models/public/gpt-2/model.yml
- models/public/index.md
- tools/accuracy_checker/configs/gpt-2.yml
- tools/downloader/README.md
- tools/downloader/src/open_model_zoo/model_tools/_common.py
> Added GPT-2 model

- demos/classification_demo/cpp/README.md
- demos/classification_demo/cpp/models.lst
- models/public/device_support.md
- models/public/index.md
- models/public/swin-tiny-patch4-window7-224/README.md
- models/public/swin-tiny-patch4-window7-224/accuracy-check.yml
- models/public/swin-tiny-patch4-window7-224/model.py
- models/public/swin-tiny-patch4-window7-224/model.yml
- tools/accuracy_checker/configs/swin-tiny-patch4-window7-224.yml
> Added Swin Transformer Tiny model

- demos/common/python/models/__init__.py
- demos/common/python/models/yolo.py
- demos/object_detection_demo/python/README.md
- demos/object_detection_demo/python/models.lst
- demos/object_detection_demo/python/object_detection_demo.py
- demos/tests/cases.py
- models/public/device_support.md
- models/public/index.md
- models/public/licenses/APACHE-2.0-PyTorch-YOLOX.txt
- models/public/yolox-tiny/README.md
- models/public/yolox-tiny/accuracy-check.yml
- models/public/yolox-tiny/model.py
- models/public/yolox-tiny/model.yml
- tools/accuracy_checker/configs/yolox-tiny.yml
> Added YOLOX Tiny model

- tools/downloader/requirements-tensorflow.in
Second iteration of CVS-59837 check.
Connected PR to OpenVINO: openvinotoolkit/openvino#6620
Integration check: intel-innersource/frameworks.ai.openvino.ci.product-configs#229 - GREEN
> TensorFlow version to 2.5.0

- ci/requirements-conversion.txt
restore mxnet==1.2.0 for win32
> Added mxnet==1.2.0 to requirements-conversion.txt for Demos Windows

- demos/build_demos.sh
- demos/build_demos_msvc.bat
[no-ci]
fix OMZ build scripts according to new layout of OpenVINO package for 2022.1
> fix for OpenVINO 2022.1 new layout

- data/dataset_definitions.yml
- models/intel/face-reidentification-retail-0095/README.md
- models/public/hybrid-cs-model-mri/README.md
- models/public/hybrid-cs-model-mri/model.yml
- models/public/index.md
- Added missing dataset in dataset_definitions.yml
- Updated docs formatting for face-reidentification-retail-0095
- Added description and input/output sections for hybrid-cs-model-mri
> Added fixes in models documentation

- models/public/retinanet-tf/README.md
fix for CVS-59714 [OV-DOC] Issues with retinanet-tf documentation
> Update documentation for retinanet-tf

- demos/common/cpp/models/src/detection_model_centernet.cpp
- demos/common/cpp/models/src/detection_model_faceboxes.cpp
- demos/common/cpp/models/src/detection_model_retinaface.cpp
- demos/common/cpp/models/src/detection_model_retinaface_pt.cpp
- demos/common/cpp/models/src/detection_model_ssd.cpp
- demos/common/cpp/models/src/detection_model_yolo.cpp
- demos/common/cpp/utils/include/utils/common.hpp
- demos/object_detection_demo/cpp/main.cpp
Rectangles clipping to avoid rectangles going out-of-bounds of image
> clipping is added to detection models

- ci/requirements-conversion.txt
* Added mxnet==1.2.0 for win32
> Added mxnet==1.2.0 to requirements-conversion.txt for Windows

- demos/common/python/requirements.txt
> Add scipy to requirements of modelAPI

- demos/build_demos.sh
- demos/build_demos_msvc.bat
https://github.com/openvinotoolkit/openvino/pull/8263
> demos: enable a custom build output folder

- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/__init__.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/convert.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/speaker_identification.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/data_readers/README.md
- tools/accuracy_checker/openvino/tools/accuracy_checker/data_readers/audio_readers.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/dataset.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/README.md
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/__init__.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/audio_preprocessing.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/audio_preprocessing_ext.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/geometric_transformations.py
- tools/accuracy_checker/tests/test_dataset.py
> AC: support speaker reidentification

- demos/README.md
- demos/human_pose_estimation_3d_demo/python/README.md
python ext modules should be added to PYTHONPATH
> human_pose_estimation_3d doc

- demos/interactive_face_detection_demo/cpp_gapi/models.lst
- demos/tests/cases.py
Added face-detection-retail model to test suite.
> G-API: Aligning test cases for g-api demos.

- models/public/dla-34/README.md
- models/public/googlenet-v3-pytorch/README.md
- models/public/googlenet-v3/README.md
- models/public/hbonet-0.25/README.md
- models/public/hbonet-0.5/README.md
- models/public/hbonet-1.0/README.md
- models/public/mobilenet-v1-0.25-128/README.md
- models/public/mobilenet-v1-0.50-160/README.md
- models/public/mobilenet-v1-0.50-224/README.md
- models/public/mobilenet-v1-1.0-224-tf/README.md
- models/public/mobilenet-v2-1.0-224/README.md
- models/public/mobilenet-v2-1.4-224/README.md
- models/public/mobilenet-v2-pytorch/README.md
- models/public/mobilenet-v2/README.md
- models/public/nfnet-f0/README.md
- models/public/regnetx-3.2gf/README.md
- models/public/repvgg-a0/README.md
- models/public/repvgg-b1/README.md
- models/public/repvgg-b3/README.md
- models/public/resnest-50-pytorch/README.md
- models/public/resnet-18-pytorch/README.md
- models/public/resnet-34-pytorch/README.md
- models/public/resnet-50-pytorch/README.md
- models/public/rexnet-v1-x1.0/README.md
- models/public/shufflenet-v2-x1.0/README.md
check and correct description for classification model's output format (probability in [0, 1] range and logits format)
> correct output format for classification models

- tools/accuracy_checker/openvino/tools/accuracy_checker/argparser.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/config/config_reader.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/base_models.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/dlsdk_launcher.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/input_feeder.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
* support for onnx models in custom evaluators
* add more layouts for 5D tensors
* improvement for selection new openvino api launcher via config
> AC: minor fixes

- demos/interactive_face_detection_demo/cpp_gapi/face.hpp
- demos/interactive_face_detection_demo/cpp_gapi/visualizer.cpp
- demos/interactive_face_detection_demo/cpp_gapi/visualizer.hpp
I hope, that this #include <map> from utils.hpp was an unnecessary removal.
> GAPI: Returning include to IFD GAPI. Part 2. The std::map.

- demos/README.md
- demos/noise_suppression_demo/cpp/CMakeLists.txt
- demos/noise_suppression_demo/cpp/README.md
- demos/noise_suppression_demo/cpp/main.cpp
- demos/noise_suppression_demo/cpp/models.lst
- demos/noise_suppression_demo/python/noise_suppression_demo.py
- demos/tests/cases.py
cpp demo to run noise suppression for master
> add cpp noise_suppression_demo for master

- ci/dependencies.yml
switch public CI to the latest OpenVINO 2021.4.2 release
> ci: openvino 2021.4.752

- demos/common/cpp/models/src/detection_model_yolo.cpp
- demos/object_detection_demo/cpp/main.cpp
fix double print in obj_detection demo and clamp in yolo wrapper
> fix object_detection_demo/cpp for yolo models

- demos/classification_demo/python/README.md
- demos/classification_demo/python/classification_demo.py
https://github.com/openvinotoolkit/open_model_zoo/pull/2957
> Classification demo readme fix

- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/asr_custom_encoder_decoder_joint.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/asr_encoder_decoder_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/asr_encoder_prediction_joint_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/base_models.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/cocosnet_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/colorization_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/custom_text_recognition_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/i3d_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/lpcnet_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator_utils.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/mtcnn_models.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/opennmt_encoder_decoder_generator_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/segnet_background_matting.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/sequential_action_recognition_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/sr_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/tacotron2_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/text_to_speech_evaluator.py
Within the PR , custom mtcnn models have been inherited from the base classes with overriding of some methods. Also init method of cascade models has been aligned and minor refactoring of evaluators and models have been done.
> AC: Refactoring mtcnn models and init in cascade models

- ci/lib/omzdocs.py
- ci/requirements-check-basics.txt
- ci/requirements-documentation.in
I was hoping to do this after the release came out, and it finally happened.
> Update mistune to the 2.0 release version

- models/public/efficientdet-d0-tf/model.yml
- models/public/efficientdet-d1-tf/model.yml
- models/public/faster_rcnn_inception_resnet_v2_atrous_coco/model.yml
- models/public/faster_rcnn_inception_v2_coco/model.yml
- models/public/faster_rcnn_resnet101_coco/model.yml
- models/public/faster_rcnn_resnet50_coco/model.yml
- models/public/mask_rcnn_inception_resnet_v2_atrous_coco/model.yml
- models/public/mask_rcnn_inception_v2_coco/model.yml
- models/public/mask_rcnn_resnet101_atrous_coco/model.yml
- models/public/mask_rcnn_resnet50_atrous_coco/model.yml
- models/public/retinanet-tf/model.yml
- models/public/rfcn-resnet101-coco-tf/model.yml
- models/public/ssd_mobilenet_v1_coco/model.yml
- models/public/ssd_mobilenet_v1_fpn_coco/model.yml
- models/public/ssd_mobilenet_v2_coco/model.yml
- models/public/ssd_resnet50_v1_fpn_coco/model.yml
- models/public/ssdlite_mobilenet_v2/model.yml
- models/public/yolo-v1-tiny-tf/model.yml
- models/public/yolo-v2-tf/model.yml
- models/public/yolo-v2-tiny-tf/model.yml
- tools/model_tools/src/openvino/model_zoo/omz_converter.py
there is no extensions dir inside mo anymore after changing namespace
Update extension directory finding logic
> OMZ converter fix path to extensions

- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/base_models.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
1. correctly build PartialShape for reshape with values range
2. handle infer for tensors without names
> AC: API 2.0 fixes

- demos/tests/run_tests.py
Fixed `KeyError: 'mtcnn-p'` in Demos jobs.
> Fixed composite models processing in run_tests.py script

- .gitmodules
> Add .git to submodule URL

- demos/interactive_face_detection_demo/cpp/detectors.cpp
- demos/interactive_face_detection_demo/cpp_gapi/README.md
- demos/interactive_face_detection_demo/cpp_gapi/face.cpp
- demos/interactive_face_detection_demo/cpp_gapi/face.hpp
- demos/interactive_face_detection_demo/cpp_gapi/interactive_face_detection_gapi.hpp
- demos/interactive_face_detection_demo/cpp_gapi/main.cpp
- demos/interactive_face_detection_demo/cpp_gapi/models.lst
- demos/interactive_face_detection_demo/cpp_gapi/visualizer.cpp
- demos/interactive_face_detection_demo/cpp_gapi/visualizer.hpp
- demos/tests/cases.py
Added anti spoof scenario for G-API version of IFD demo.
Tested.
> G-API: Adding anti spoofing scenario for IFD-GAPI

- demos/gaze_estimation_demo/cpp/README.md
- demos/gaze_estimation_demo/cpp/gaze_estimation_demo.hpp
- demos/gaze_estimation_demo/cpp/include/face_inference_results.hpp
- demos/gaze_estimation_demo/cpp/include/ie_wrapper.hpp
- demos/gaze_estimation_demo/cpp/include/landmarks_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/utils.hpp
- demos/gaze_estimation_demo/cpp/main.cpp
- demos/gaze_estimation_demo/cpp/models.lst
- demos/gaze_estimation_demo/cpp/src/eye_state_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/face_detector.cpp
- demos/gaze_estimation_demo/cpp/src/face_inference_results.cpp
- demos/gaze_estimation_demo/cpp/src/gaze_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/head_pose_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/ie_wrapper.cpp
- demos/gaze_estimation_demo/cpp/src/landmarks_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/results_marker.cpp
- demos/tests/cases.py
adds support for facial-landmarks-98-detection-0001 model
> add facial-landmarks-98-detection model to gaze_estimation_demo

- demos/gesture_recognition_demo/python/gesture_recognition_demo.py
add meaningful message for the error
> gesture_recognition_demo_fix

- tools/model_tools/src/openvino/model_zoo/omz_converter.py
fixed path to mo in omz_converter
> align mo_dir to point to mo folder

- tools/model_tools/src/openvino/model_zoo/download_engine/cache.py
Relates to https://github.com/openvinotoolkit/open_model_zoo/pull/3047
> model_tools: fix retrieving from cache

- ci/requirements-ac-test.txt
- ci/requirements-ac.txt
- ci/requirements-downloader.txt
- ci/requirements-quantization.txt
- tools/accuracy_checker/requirements-core.in
- tools/model_tools/requirements.in
> Add openvino-telemetry to requirements

- demos/common/cpp/models/src/detection_model_retinaface_pt.cpp
> detection_model_retinaface_pt fix

- ci/unsupported-devices.txt
- demos/README.md
- demos/background_subtraction_demo/python/README.md
- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/background_subtraction_demo/python/models.lst
- demos/common/python/openvino/model_zoo/model_api/models/__init__.py
- demos/common/python/openvino/model_zoo/model_api/models/instance_segmentation.py
- demos/tests/cases.py
This is a background subtraction demo that uses instance segmentation based models.
> Add background subtraction demo

- tools/accuracy_checker/openvino/tools/accuracy_checker/presenters.py
Added support of reference in str format. Example: `reference: 1e-5`
> Added support of reference in str format

- demos/gpt2_text_prediction_demo/python/README.md
- demos/gpt2_text_prediction_demo/python/gpt2_text_prediction_demo.py
- models/intel/bert-small-uncased-whole-word-masking-squad-emb-int8-0001/README.md
- models/public/gpt-2/README.md
- models/public/gpt-2/model.yml
GPT2 text generation demo with dynamic input
> OV2.0: GPT2 text generation demo with dynamic input support

- models/intel/noise-suppression-poconetlike-0001/README.md
- models/intel/person-vehicle-bike-detection-2000/README.md
- models/intel/person-vehicle-bike-detection-2001/README.md
- models/intel/person-vehicle-bike-detection-2002/README.md
- models/intel/person-vehicle-bike-detection-2003/README.md
- models/intel/person-vehicle-bike-detection-2004/README.md
- models/public/netvlad-tf/README.md
fixed dead links found at documentation check by CI
> fix dead links

- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/README.md
> fix dead link

- demos/text_spotting_demo/python/text_spotting_demo.py
Migrate python text_spotting_demo to OV2.0 API.
> ov 2.0: python text_spotting_demo

- demos/action_recognition_demo/python/README.md
- demos/action_recognition_demo/python/action_recognition_demo.py
- demos/action_recognition_demo/python/action_recognition_demo/models.py
- demos/action_recognition_demo/python/action_recognition_demo/steps.py
migrate python action_recognition demo to OV2.0 API
> OV2.0 python action_recognition_demo

- demos/instance_segmentation_demo/python/README.md
- demos/instance_segmentation_demo/python/instance_segmentation_demo.py
- demos/instance_segmentation_demo/python/instance_segmentation_demo/model_utils.py
Migrate python instance_segmentation_demo to OV2.0 API
> ov 2.0: python instance_segmentation_demo

- demos/single_human_pose_estimation_demo/python/detector.py
- demos/single_human_pose_estimation_demo/python/estimator.py
- demos/single_human_pose_estimation_demo/python/single_human_pose_estimation_demo.py
Migrate python single_human_pose_estimation_demo to OV2.0 API
> ov 2.0: python single_human_pose_estimation_demo

- demos/speech_recognition_quartznet_demo/python/speech_recognition_quartznet_demo.py
- demos/speech_recognition_wav2vec_demo/python/speech_recognition_wav2vec_demo.py
Migrate speech_recognition_wav2vec_demo and speech_recognition_quartznet_demo to OV2.0
> ov 2.0: python speech_recognition_wav2vec_demo and speech_recognition_quartznet_demo

- demos/image_retrieval_demo/python/image_retrieval_demo/image_retrieval.py
- demos/place_recognition_demo/python/place_recognition_demo/place_recognition.py
Migrate image_retrieval_demo and place_recognition_demo to OV2.0
> ov 2.0: python image_retrieval_demo and place_recognition_demo

- demos/image_translation_demo/python/image_translation_demo.py
- demos/image_translation_demo/python/image_translation_demo/models.py
- demos/mri_reconstruction_demo/python/mri_reconstruction_demo.py
- demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
- demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py
- demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py
- demos/time_series_forecasting_demo/python/time_series_forecasting_demo.py
- demos/whiteboard_inpainting_demo/python/utils/ie_tools.py
- demos/whiteboard_inpainting_demo/python/utils/network_wrappers.py
- demos/whiteboard_inpainting_demo/python/whiteboard_inpainting_demo.py
Modify the following python demos with new OpenVINO 2.0 API:
- image_translation_demo
- mri_reconstruction_demo
- multi_camera_multi_target_tracking_demo
- time_series_forecasting_demo
- whiteboard_inpainting_demo
> ov2.0: modify python non model API demos [Part 2] 

- demos/sound_classification_demo/python/sound_classification_demo.py
migrate python sound classification demo to OV2.0 API
> OV 2.0: python sound classification demo

- ci/dependencies.yml
update to openvino 2022.1.518 (ww04.1 master) build
> Bumped OV package version to 518.

- CONTRIBUTING.md
- ci/requirements-conversion.txt
- ci/update-requirements.py
- demos/segmentation_demo/cpp/README.md
- demos/segmentation_demo/cpp/models.lst
- demos/segmentation_demo/python/README.md
- demos/segmentation_demo/python/models.lst
- demos/tests/cases.py
- models/public/device_support.md
- models/public/index.md
- models/public/ocrnet-hrnet-w48-paddle/README.md
- models/public/ocrnet-hrnet-w48-paddle/accuracy-check.yml
- models/public/ocrnet-hrnet-w48-paddle/model.yml
- models/public/ocrnet-hrnet-w48-paddle/pre-convert.py
- tools/model_tools/README.md
- tools/model_tools/requirements-paddle.in
- tools/model_tools/setup.py
- tools/model_tools/src/openvino/model_zoo/_common.py
add ocrnet-hrnet-w48-paddle model to demonstrate PaddlePaddle framework support in OpenVINO
> add paddle OCRNet

- demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py
- demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py
- demos/tests/cases.py
have to turn off tests because the demo is hanging with OV2.0 2022.1.518 build. Need to be enabled back once fixed.
> multi_camera_multi_target_tracking_demo comment tests

- demos/common/cpp/utils/include/utils/common.hpp
- demos/noise_suppression_demo/cpp/CMakeLists.txt
- demos/noise_suppression_demo/cpp/README.md
- demos/noise_suppression_demo/cpp/main.cpp
OV2.0 in noise_suppression_demo
> OV2.0 c++ noise suppression

- demos/colorization_demo/python/colorization_demo.py
migrate Python colorization_demo to OV2.0 API
> OV 2.0: python colorization demo

- demos/common/python/requirements.txt
align numpy dependency wih other ov components
> model api: less restricted numpy version

- demos/machine_translation_demo/python/machine_translation_demo.py
Migrate python machine_translation_demo to OV2.0 API
> ov 2.0: python machine_translation_demo

- demos/common/cpp/models/src/style_transfer_model.cpp
- demos/gaze_estimation_demo/cpp/src/landmarks_estimator.cpp
- demos/gesture_recognition_demo/cpp_gapi/main.cpp
- demos/gesture_recognition_demo/cpp_gapi/src/custom_kernels.cpp
- demos/interactive_face_detection_demo/cpp_gapi/face.cpp
- demos/interactive_face_detection_demo/cpp_gapi/face.hpp
Fixes for problems with Klocwork.
> Fixed some demo mistakes

- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/common/python/openvino/model_zoo/model_api/models/instance_segmentation.py
* Add `preload` arg to MaskRCNN and YOLACT
* Change `prob_threshold` to `confidence_threshold`
> Fix Instance Segmentation Model

- ci/dependencies.yml
> Added OpenCV versions for CI

- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
related to https://github.com/openvinotoolkit/openvino/pull/9927
configuration changes are backward compatible on tool side, no impact on validation if we merge before ov part will be expected
> AC: migrate on configuration api 2.0

- demos/gaze_estimation_demo/cpp/include/eye_state_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/face_detector.hpp
- demos/gaze_estimation_demo/cpp/include/gaze_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/head_pose_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/ie_wrapper.hpp
- demos/gaze_estimation_demo/cpp/include/landmarks_estimator.hpp
- demos/gaze_estimation_demo/cpp/main.cpp
- demos/gaze_estimation_demo/cpp/src/eye_state_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/face_detector.cpp
- demos/gaze_estimation_demo/cpp/src/gaze_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/head_pose_estimator.cpp
- demos/gaze_estimation_demo/cpp/src/ie_wrapper.cpp
- demos/gaze_estimation_demo/cpp/src/landmarks_estimator.cpp
- demos/noise_suppression_demo/cpp/main.cpp
> remove runtime namespace

- demos/gaze_estimation_demo/cpp/include/eye_state_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/face_detector.hpp
- demos/gaze_estimation_demo/cpp/include/gaze_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/head_pose_estimator.hpp
- demos/gaze_estimation_demo/cpp/include/landmarks_estimator.hpp
[no-ci]
remove openvino runtime namespace
required 2022.1.541 build
> gaze_estimation_demo, sync with OpenVINO PR-9781

- demos/classification_demo/python/README.md
- demos/classification_demo/python/models.lst
- models/public/device_support.md
- models/public/index.md
- models/public/t2t-vit-14/README.md
- models/public/t2t-vit-14/accuracy-check.yml
- models/public/t2t-vit-14/model.py
- models/public/t2t-vit-14/model.yml
- tools/accuracy_checker/configs/t2t-vit-14.yml
- tools/model_tools/src/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py
add t2t-vit-14 image classification public model
> Added t2t-vit-14 model

- demos/common/cpp/utils/include/utils/common.hpp
- demos/common/cpp/utils/include/utils/ocv_common.hpp
- demos/mri_reconstruction_demo/cpp/CMakeLists.txt
- demos/mri_reconstruction_demo/cpp/main.cpp
- demos/mri_reconstruction_demo/cpp/mri_reconstruction_demo.hpp
- demos/mri_reconstruction_demo/cpp/npy_reader.hpp
Migrate c++ mri reconstruction demo to new API.
> OV2.0 c++ mri reconstruction demo

- demos/image_inpainting_demo/python/image_inpainting_demo.py
- demos/image_inpainting_demo/python/inpainting.py
Migrate python image_inpainting_demo to OV2.0 API
> ov 2.0: python image_inpainting_demo

- demos/bert_question_answering_demo/python/requirements.txt
- demos/bert_question_answering_embedding_demo/python/requirements.txt
- demos/common/python/requirements.txt
- demos/face_recognition_demo/python/requirements.txt
- demos/handwritten_text_recognition_demo/python/requirements.txt
- demos/human_pose_estimation_3d_demo/python/requirements.txt
- demos/machine_translation_demo/python/requirements.txt
- demos/multi_camera_multi_target_tracking_demo/python/requirements.txt
- demos/requirements.txt
- demos/speech_recognition_deepspeech_demo/python/requirements.txt
- demos/text_to_speech_demo/python/requirements.txt
- demos/time_series_forecasting_demo/python/requirements.txt
- demos/whiteboard_inpainting_demo/python/requirements.txt
- tools/accuracy_checker/requirements-core.in
align omz numpy dependencies with https://github.com/openvinotoolkit/openvino/pull/9921
> Align numpy dependency with mo and pot

- models/intel/device_support.md
update missed models in device__support.md
> update missed models in device__support.md

- demos/formula_recognition_demo/python/requirements.txt
accidentally skipped this demo during requirements update...
> update missed numpy requirements

- demos/3d_segmentation_demo/python/requirements.txt
- demos/bert_question_answering_demo/python/requirements.txt
- demos/bert_question_answering_embedding_demo/python/requirements.txt
- demos/face_recognition_demo/python/requirements.txt
- demos/formula_recognition_demo/python/requirements.txt
- demos/handwritten_text_recognition_demo/python/requirements.txt
- demos/human_pose_estimation_3d_demo/python/requirements.txt
- demos/machine_translation_demo/python/requirements.txt
- demos/multi_camera_multi_target_tracking_demo/python/requirements.txt
- demos/requirements.txt
- demos/speech_recognition_deepspeech_demo/python/requirements.txt
- demos/text_to_speech_demo/python/requirements.txt
- demos/time_series_forecasting_demo/python/requirements.txt
- demos/whiteboard_inpainting_demo/python/requirements.txt
The merge guarantees that Snyk scans all dependencies
> demos: merge requirements.txt

- models/intel/noise-suppression-denseunet-ll-0001/README.md
add description for Y and delay outputs for noise-suppression-denseunet-ll-0001 model
> extend output description for noise-suppression-denseunet-ll-0001

- demos/interactive_face_detection_demo/cpp/detectors.cpp
See https://github.com/openvinotoolkit/openvino/pull/10100
> Removed runtime namespace usage

- demos/noise_suppression_demo/cpp/main.cpp
- demos/noise_suppression_demo/python/noise_suppression_demo.py
- demos/tests/cases.py
add delay output using into noise suppression
add processing file with any sampling freq
> add delay using into noise suppression

- demos/background_subtraction_demo/python/README.md
- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/background_subtraction_demo/python/models.lst
- demos/common/python/openvino/model_zoo/model_api/models/__init__.py
- demos/common/python/openvino/model_zoo/model_api/models/background_matting.py
- demos/tests/cases.py
This is an update for `background_subtraction_demo` to support background matting models in [PR#3054](https://github.com/openvinotoolkit/open_model_zoo/pull/3054).
> demos/background_subtraction: add support for background matting models

- demos/common/cpp/utils/include/utils/common.hpp
- demos/common/cpp/utils/include/utils/ocv_common.hpp
- demos/mask_rcnn_demo/cpp/main.cpp
- demos/mask_rcnn_demo/cpp/mask_rcnn_demo.h
OV2.0 with IR v10 and IR v11 support in mask_rcnn_demo
> OV2.0 mask_rcnn_demo

- demos/action_recognition_demo/python/action_recognition_demo.py
'VPU_HW_STAGES_OPTIMIZATION' -> 'MYRIAD_ENABLE_HW_ACCELERATION'
Deprecated config key 'VPU_HW_STAGES_OPTIMIZATION' was deleted in https://github.com/openvinotoolkit/openvino/pull/9857/
> Fix myriad config in action_recognition_demo

- models/public/deeplabv3/model.yml
- models/public/efficientdet-d0-tf/model.yml
- models/public/efficientdet-d1-tf/model.yml
- models/public/efficientnet-b0/model.yml
- models/public/efficientnet-v2-b0/model.yml
- models/public/efficientnet-v2-s/model.yml
- models/public/facenet-20180408-102900/model.yml
add layout MO param to the rest of public models
> add layouts for remained public models

- demos/multi_channel_common/cpp/graph.hpp
- demos/social_distance_demo/cpp/main.cpp
fix rest of properties in c++ demos
> OV2.0 properties rest in cpp

- demos/tests/cases.py
Suppress failed test cases on 577 package (exit code: 11 or 6)
face-detection-0205
face-detection-0206
person-vehicle-bike-detection-2003
person-vehicle-bike-detection-2004
person-reidentification-retail-0277
instance-segmentation-person-0007
person-detection-0106
yolo-v3-onnx
yolo-v3-tiny-onnx
> tests: suppress failed test cases

- demos/common/cpp/utils/include/utils/common.hpp
- demos/security_barrier_camera_demo/cpp/main.cpp
- demos/social_distance_demo/cpp/main.cpp
OV2.0 rename props to sync with OV PR #10150
requires 2022.1.582 to build
> OV2.0 rename props to sync with OV PR #10150

- tools/model_tools/src/openvino/model_zoo/_configuration.py
restore hybrid-cs-mri after MO fix 74413, 77233
> restore hybrid-cs-mri after MO fix

- models/public/device_support.md
> suppress mask_rcnn on gpu

- demos/interactive_face_detection_demo/cpp_gapi/main.cpp
> fix warn unused variable

- demos/gesture_recognition_demo/cpp_gapi/src/tracker.cpp
- demos/pedestrian_tracker_demo/cpp/src/tracker.cpp
- demos/smart_classroom_demo/cpp/src/tracker.cpp
- demos/text_detection_demo/cpp/include/cnn.hpp
- demos/text_detection_demo/cpp/main.cpp
- demos/text_detection_demo/cpp/src/cnn.cpp
- demos/text_detection_demo/cpp/src/text_recognition.cpp
> fixed warns unused vars, init order, signed/unsigned cmp

- models/public/gpt-2/model.yml
Same as https://github.com/openvinotoolkit/open_model_zoo/pull/3225
> GPT-2: update path to onnx model

- README.md
Follow up
https://github.com/openvinotoolkit/open_model_zoo/pull/2521/files#r807190674
I can't do anything about 21.4.2 because it's already released, avoid
the same mistake for 21.4.3.
> Bump the version for the next release

- models/intel/device_support.md
[skip-ci]
turn off bert on gpu until fixed
> turn off bert on gpu

- demos/mask_rcnn_demo/cpp/main.cpp
no output post-process required
> fix post-process

- demos/common/cpp/models/include/models/detection_model_yolo.h
- demos/common/cpp/models/src/detection_model_yolo.cpp
Cherry pick
6b126df45492c2316664163af6dcd921b2b58383
> Fix ModelYolo possible loss of data warning

- demos/common/cpp/models/include/models/detection_model_yolo.h
- demos/common/cpp/models/src/detection_model_yolo.cpp
fix 78864 issue (build 2021.4 OMZ demos with OpenVINO 2022.1)
> demos/cpp remove conflicting RegionYolo alias

- models/intel/device_support.md
- models/public/device_support.md
disable on GPU
Intel models (48):
face-detection-0200
face-detection-0202
face-detection-0204
face-detection-adas-0001
face-detection-retail-0004
face-detection-retail-0005
faster-rcnn-resnet101-coco-sparse-60-0001
human-pose-estimation-0001
human-pose-estimation-0005
human-pose-estimation-0006
human-pose-estimation-0007
icnet-camvid-ava-0001
icnet-camvid-ava-sparse-30-0001
icnet-camvid-ava-sparse-60-0001
instance-segmentation-security-0002
instance-segmentation-security-0228
instance-segmentation-security-1039
instance-segmentation-security-1040
landmarks-regression-retail-0009
pedestrian-and-vehicle-detector-adas-0001
pedestrian-detection-adas-0002
person-detection-0200
person-detection-0201
person-detection-0202
person-detection-retail-0013
person-reidentification-retail-0277 …
> disable tests for failed models

- models/intel/device_support.md
- models/public/device_support.md
person-reid (CPU-on, GPU-off), efficientnet-b0-pytorch GPU-off
> person-reid, efficientnet-b0-pytorch

- demos/multi_channel_face_detection_demo/cpp/main.cpp
- demos/multi_channel_human_pose_estimation_demo/cpp/main.cpp
- demos/multi_channel_object_detection_demo_yolov3/cpp/main.cpp
Use PerformanceMetrics with --no_show, to report FPS
Ticket 79502
> demos/multi_channel: perform finalizing steps even with --no_show

- models/intel/device_support.md
> face-detection-0005,0006 GPU off

- models/intel/device_support.md
> formula-medium-scan-gpu-off

- models/intel/device_support.md
[skip-ci]
This reverts commit 80ffb8b80a3fd0933742d94bb966b4209ab335ad. Revert this, let's fail on GPU on windows (need update video driver)
> Revert "formula-medium-scan-gpu-off (#3262)"

- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/bert_named_entity_recognition_demo/python/bert_named_entity_recognition_demo.py
- demos/bert_question_answering_demo/python/bert_question_answering_demo.py
- demos/bert_question_answering_embedding_demo/python/bert_question_answering_embedding_demo.py
- demos/classification_demo/python/classification_demo.py
- demos/common/python/openvino/model_zoo/model_api/pipelines/async_pipeline.py
- demos/deblurring_demo/python/deblurring_demo.py
- demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
- demos/monodepth_demo/python/monodepth_demo.py
- demos/object_detection_demo/python/object_detection_demo.py
- demos/segmentation_demo/python/segmentation_demo.py
- models/intel/device_support.md
- models/public/device_support.md
`query_state` don't relate to status of request. Now all exceptions raised in callback will be move to `callback_exceptions` list.
As I know `wait_all` for `AsyncQueue`  guarantees that callback is finished. @AlexeyLebedev1 Am I right?
> model api improvements

- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/bert_question_answering_demo/python/bert_question_answering_demo.py
- demos/classification_demo/python/classification_demo.py
- demos/deblurring_demo/python/deblurring_demo.py
- demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
- demos/instance_segmentation_demo/python/instance_segmentation_demo.py
- demos/monodepth_demo/python/monodepth_demo.py
- demos/object_detection_demo/python/object_detection_demo.py
- demos/segmentation_demo/python/segmentation_demo.py
Add changes from https://github.com/openvinotoolkit/open_model_zoo/pull/3080 and https://github.com/openvinotoolkit/open_model_zoo/pull/3260 to instance_segmentation_demo.py
> instance_segmentation_demo.py: align with recent changes

- demos/tests/cases.py
launched the demo several times with -nireq 1 (sync) and default -nireq (async). It seems the demo is not failed with `-nireq 1`, so add this option while testing
> bert_named_entity_recognition_demo.py: test in CI

- demos/tests/cases.py
- models/intel/device_support.md
- models/public/device_support.md
turn on tests on GPU for disabled models in https://github.com/openvinotoolkit/open_model_zoo/pull/3247 https://github.com/openvinotoolkit/open_model_zoo/pull/3241 https://github.com/openvinotoolkit/open_model_zoo/pull/3249
> upd device support

- models/intel/index.md
- models/public/index.md
> minor sync with pr-3239

- demos/common/cpp/models/src/classification_model.cpp
> setting output precision in cpp classification model 

- models/intel/index.md
- tools/accuracy_checker/README.md
- tools/model_tools/README.md
> sync with pr-3239

- models/public/device_support.md
> Supress robust-video-matting-mobilenetv3 model on GPU

- demos/tests/data_sequences.py
not enough GPU memory for batch 4, so reduce batch to 2
> limit batch 2

- demos/background_subtraction_demo/python/background_subtraction_demo.py
- demos/bert_named_entity_recognition_demo/python/bert_named_entity_recognition_demo.py
- demos/bert_question_answering_demo/python/bert_question_answering_demo.py
- demos/bert_question_answering_embedding_demo/python/bert_question_answering_embedding_demo.py
- demos/classification_benchmark_demo/cpp/main.cpp
- demos/classification_demo/python/classification_demo.py
- demos/common/cpp/utils/src/args_helper.cpp
- demos/common/python/openvino/model_zoo/model_api/adapters/utils.py
- demos/deblurring_demo/python/deblurring_demo.py
- demos/human_pose_estimation_demo/cpp/main.cpp
- demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
- demos/image_processing_demo/cpp/main.cpp
- demos/monodepth_demo/python/monodepth_demo.py
- demos/object_detection_demo/cpp/main.cpp
- demos/object_detection_demo/python/object_detection_demo.py
- demos/pedestrian_tracker_demo/cpp/include/pedestrian_tracker_demo.hpp
- demos/segmentation_demo/cpp/main.cpp
- demos/segmentation_demo/python/segmentation_demo.py
https://github.com/openvinotoolkit/open_model_zoo/pull/3104#discussion_r802896207
> Use : as delimiter for layout flag

- demos/common/python/openvino/model_zoo/model_api/models/model.py
`AsyncPipeline` return predictions and meta when users call `get_result`. Provide this approach to `call` method in model classes.
> ModelAPI update call method

- demos/common/python/openvino/model_zoo/__init__.py
Follow up
https://github.com/openvinotoolkit/open_model_zoo/pull/1352#issuecomment-1056751127
> demos/common/python/openvino/model_zoo: declare as namespace

- demos/tests/cases.py
- demos/tests/performance_cases.py
- demos/tests/run_tests.py
For `--demos` argument `gapi, cpp, python` values were added, which enable testing demos of corresponding implementation. Added exception in case of empty list of demos to test.
> Add ability to test demos of specific implementation.

- demos/gaze_estimation_demo/cpp/models.lst
- demos/tests/cases.py
enable facials-landmarks-98 in models.lst
> gaze_estimation_demo landmarks-98

- demos/common/cpp/models/src/classification_model.cpp
Issue #80766
Prevent app crash when results are out of array bounds
> Check intervals of labels array

- tools/model_tools/README.md
put sphinx tables to markdown comments
> sphinx tables in markdown

- tools/model_tools/README.md
put sphinx tables to mardown comments (#3346)
> fix sphinx tables in docs

- demos/tests/cases.py
- demos/tests/data_sequences.py
- demos/tests/run_tests.py
add demos build dir to PYTHONPATH, for C++ Python modules
> fix demos pythonpath

- ci/dependencies.yml
> Bump OpenVINO package version to 630

- demos/background_subtraction_demo/cpp_gapi/README.md
- demos/background_subtraction_demo/python/README.md
- demos/gesture_recognition_demo/cpp_gapi/README.md
- demos/smartlab_demo/python/README.md
fix link to MO in models description
> Updated inactive link for MO in demos readme

- demos/common/cpp/models/src/classification_model.cpp
- demos/common/cpp/pipelines/src/async_pipeline.cpp
> rethrow exception in callback

- models/intel/action-recognition-0001/composite-model.yml
- models/intel/driver-action-recognition-adas-0002/composite-model.yml
- models/intel/formula-recognition-medium-scan-0001/composite-model.yml
- models/intel/formula-recognition-polynomials-handwritten-0001/composite-model.yml
- models/intel/text-recognition-0015/composite-model.yml
- models/intel/text-recognition-0016/composite-model.yml
- models/intel/text-spotting-0005/composite-model.yml
- models/intel/text-to-speech-en-0001/composite-model.yml
- models/intel/text-to-speech-en-multi-0001/composite-model.yml
- models/public/forward-tacotron/composite-model.yml
- models/public/mtcnn/composite-model.yml
- models/public/wavernn/composite-model.yml
- tools/model_tools/src/openvino/model_zoo/_configuration.py
Update the order of composite models stages to match the order in which the models are used.
> model_tools: update order of composite models stages

- demos/README.md
> docs: remove InferenceEngine_DIR, ngraph_DIR, add Ubuntu20

- demos/README.md
> docs: remove InferenceEngine_DIR, ngraph_DIR, add Ubuntu20 (#3380)

- models/intel/device_support.md
> Suppress image_retrieval on GPU

- demos/text_to_speech_demo/python/models/forward_tacotron_ie.py
- demos/text_to_speech_demo/python/models/mel2wave_ie.py
- demos/text_to_speech_demo/python/text_to_speech_demo.py
- with latest 2022.1.0 release, inference of text to speech
for longer sentences is failing.
Signed-off-by: Sutaria, Smitesh <smitesh.sutaria@intel.com>
> fix the issue with longer sentence inference (issue #3393)

- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
cherry-pick to release branch one important fix for VPU
> AC: port important bugfix for 2022/1

- models/intel/instance-segmentation-person-0007/README.md
- models/intel/instance-segmentation-security-0002/README.md
- models/intel/instance-segmentation-security-0091/README.md
- models/intel/instance-segmentation-security-0228/README.md
- models/intel/instance-segmentation-security-1039/README.md
- models/intel/instance-segmentation-security-1040/README.md
> Updated output shapes for instance-segmentation models in docs

- tools/accuracy_checker/requirements.in
This helped to prevent dependency resolution issues that suddenly started to happen in OpenVINO precommits: https://openvino-ci.intel.com/job/private-ci/job/ie/job/e2e-tests-windows-pip-conflicts/26440
> Fix rawpy version on compatible release

- demos/tests/cases.py
- demos/tests/performance_cases.py
- demos/tests/run_tests.py
The PR extends performance scenario with demos supporting dynamic shapes. 
Also, the model precisions are written to .csv tables, because we might launch performance job with different precisions and it should be highlighted.
> Performance scope: add demos with dynamism

- demos/text_to_speech_demo/python/models/forward_tacotron_ie.py
- demos/text_to_speech_demo/python/text_to_speech_demo.py
> Fix text_to_speech demo

- demos/smartlab_demo/python/segmentor.py
fixed segmentor.py for new i3d model
> Smartlab mstcn fix

- demos/image_translation_demo/python/image_translation_demo/models.py
- demos/image_translation_demo/python/image_translation_demo/preprocessing.py
Fix preprocessing for Segmentation and Translation models: convert OV shapes to lists for slicing, add extra dimension to match models input sizes
> image_translation_demo.py: fix preprocessing

- demos/README.md
There is a typo "buid" in the document, correction to "build"
> correct the typo in the documents

- tools/accuracy_checker/requirements.in
Cherry picks from master:
https://github.com/openvinotoolkit/open_model_zoo/pull/3413
https://github.com/openvinotoolkit/open_model_zoo/pull/3415
> Fix imagecodecs and scikit-image versions

- models/public/index.md
fix based on documentation build errors
> fix TOC reference for nanodet

- demos/common/python/openvino/model_zoo/model_api/models/utils.py
Signed-off-by: Songki Choi <songki.choi@intel.com>
> Fix NaN issue for exp() in softmax function (#3490)

- demos/common/python/requirements.txt
- demos/requirements.txt
- tools/accuracy_checker/requirements-core.in
- tools/model_tools/requirements-tensorflow.in
align tf and numpy version with other openvino components.
Related to https://github.com/openvinotoolkit/openvino/pull/12191
> Update numpy and tf requirements

- ci/requirements-openvino-dev.in
- tools/model_tools/requirements-pytorch.in
OV does not currently support opset 17 introduced in onnx 1.12 release.
> Limit ONNX version

- demos/common/cpp/models/src/detection_model_yolo.cpp
Yolo models converted with the 2022.1 model optimizer have a different output shape (NHWC) compared to ones converted with an earlier version (NCHW).
The current output processing for yolo in the C++ examples assumes the output tensors use NCHW layout. This PR uses the PrePostProcessor to convert the output tensor to the expected shape regardless which version of the model optimizer was used to create it.
Fixes: https://github.com/openvinotoolkit/open_model_zoo/issues/3462
> Fix yolo detection results for models created with the 2022.1 model optimizer

- models/intel/index.md
- models/public/index.md
correcting model lists to reflect the 22.1 branch model content
> fix build errors

- demos/common/cpp/utils/src/image_utils.cpp
- demos/common/python/openvino/model_zoo/model_api/models/utils.py
- demos/common/python/openvino/model_zoo/model_api/models/yolo.py
1. swap W and H for python yolo
2. fix hqResize choice for cpp
3. align padding for resize for cpp and py
Ticket: 89481
> demos: yolo fixes

- demos/multi_camera_multi_target_tracking_demo/python/README.md
Hi, thanks for releasing all these demos. Noticed a small error in documentation on running multi_camera_multi_target_tracking_demo.py . Fix for the same
> fixes command to run tracking demo

- demos/smartlab_demo/python/evaluator.py
1: rider and tweezer can't found correctly at the same time.
2: measuring_score_weights_tweezers corner case which has empty use_tweezers_bool
> Update smartlab demo with corner case consideration.

- models/intel/machine-translation-nar-de-en-0002/README.md
- models/intel/machine-translation-nar-en-de-0002/README.md
- models/intel/machine-translation-nar-en-ru-0002/README.md
- models/intel/machine-translation-nar-ru-en-0002/README.md
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3568
> Add train link for models/intel/machine-translation

- demos/gaze_estimation_demo/cpp/src/results_marker.cpp
- demos/gaze_estimation_demo/cpp_gapi/src/results_marker.cpp
- models/intel/head-pose-estimation-adas-0001/README.md
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3558
> Explain head pose estimation adas 0001 coordinate system

- demos/face_detection_mtcnn_demo/python/face_detection_mtcnn_demo.py
infer() doesn't cast list to np.array anymore
> face_detection_mtcnn_demo: list->np.array

- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
> AC: fix add_extension()

- demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py
> demos: copy array for async

- demos/common/python/openvino/model_zoo/model_api/models/yolo.py
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3592
> demos/yolo: list->ndarray

- demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py
Merge after https://github.com/openvinotoolkit/openvino/pull/13613
> demos: don't cast shape to str

- ci/requirements-conversion.txt
Dependabot alerts vulnarabilities in tensorflow==2.9.1
> Upgrade tensorflow to version 2.9.3

- demos/face_recognition_demo/python/ie_module.py
Avoid race condition for outputs of models
> Fix bug in face_recognition_demo python version

- tools/model_tools/src/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py
* prevent loading wrong package versions during pytorch2onnx conversion
* make path extending process more safe removing added packages after usage
> [model tools]: fix adding to path order

- ci/requirements-ac-test.txt
- ci/requirements-ac.txt
- ci/requirements-check-basics.txt
- ci/requirements-conversion.txt
- ci/requirements-demos.txt
- ci/requirements-downloader.txt
- ci/requirements-openvino-dev.txt
- ci/requirements-quantization.txt
> Bump ci requirements

- demos/smart_classroom_demo/cpp/README.md
- demos/smart_classroom_demo/cpp/main.cpp
- demos/smart_classroom_demo/cpp/smart_classroom_demo.hpp
- demos/smart_classroom_demo/cpp/src/reid_gallery.cpp
- demos/smart_classroom_demo/cpp_gapi/README.md
- demos/smart_classroom_demo/cpp_gapi/include/initialize.hpp
- demos/smart_classroom_demo/cpp_gapi/main.cpp
- demos/smart_classroom_demo/cpp_gapi/smart_classroom_demo_gapi.hpp
- demos/smart_classroom_demo/cpp_gapi/src/action_detector.cpp
> smart_classroom_demo: clarify -ad, fix bbox coordinates

- demos/3d_segmentation_demo/python/3d_segmentation_demo.py
- demos/common/python/openvino/model_zoo/model_api/models/centernet.py
- demos/common/python/openvino/model_zoo/model_api/models/ctpn.py
- demos/common/python/openvino/model_zoo/model_api/models/retinaface.py
- demos/face_recognition_demo/python/face_identifier.py
- demos/smart_classroom_demo/utils/action_event_metrics.py
- demos/text_to_speech_demo/python/utils/wav_processing.py
- models/public/quartznet-15x5-en/model.yml
- tools/accuracy_checker/openvino/tools/accuracy_checker/adapters/ctpn.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/adapters/kaldi_asr_decoder.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/opennmt_encoder_decoder_generator_evaluator.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/detection.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/image_quality_assessment.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/multilabel_recognition.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/regression.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/reid.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/postprocessor/filter.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/postprocessor/normalize_boxes.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/postprocessor/normalize_landmarks_points.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/preprocessor/geometric_transformations.py
https://github.com/openvinotoolkit/openvino/pull/14728
> replace deprecated numpy dtypes

- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/custom_evaluators/opennmt_encoder_decoder_generator_evaluator.py
> fix attrubute not found np.long

- .github/workflows/build_demos.yml
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3648
> Add .github/workflows/build_demos.yml

- data/dataset_definitions.yml
- models/public/erfnet/accuracy-check.yml
- models/public/erfnet/model.yml
Fixes for precommit check.
Precommit check is in progress
> Removed extra spaces

- .github/workflows/accuracy_checker-pytest.yml
- .github/workflows/build_demos.yml
Fixes for precommit check.
Precommit check is in progress
> Added extra spaces

- tools/model_tools/src/openvino/model_zoo/_version.py
I need some hint that omz contains fix for path is None to reinstall it in notebooks, checking version looks reasonable for that
> update model tools version

- demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/sct.py
- demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
- demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py
- demos/tests/cases.py
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3480
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3619
> Fix multi_camera_multi_target_tracking_demo

- ci/dependencies.yml
> Openvino version for CI was updated

- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/README.md
- tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/background_matting.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/background_matting.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/representation/segmentation_representation.py
Support datasets with separately `pha` and 3 channel `fgr`
> Support videomatte dataset for background_matting models

- demos/tests/cases.py
Conversion fails with `ModuleNotFoundError: No module named 'keras.api'`
> demos/tests: supress efficientdets

- .bandit
- ci/requirements-check-basics.txt
- ci/requirements-conversion.txt
- ci/requirements-demos.txt
- ci/requirements-downloader.txt
- ci/requirements-openvino-dev.in
- ci/requirements-openvino-dev.txt
- ci/requirements-quantization.txt
- demos/3d_segmentation_demo/python/3d_segmentation_demo.py
- demos/speech_recognition_deepspeech_demo/python/asr_utils/audio_features.py
- demos/speech_recognition_quartznet_demo/python/speech_recognition_quartznet_demo.py
- demos/tests/cases.py
- demos/tests/run_tests.py
- demos/text_to_speech_demo/python/utils/text_preprocessing.py
> Upgrade werkzeug

- demos/common/cpp/models/src/detection_model_yolo.cpp
> object_detection/cpp: fix precision for --scale_values

- models/intel/index.md
- models/public/index.md
The changes suggested in this commit are a follow-up of 
https://github.com/openvinotoolkit/openvino/pull/15314, which entails introduction of a more versatile approach for implementing sortable tables within articles across the documentation.
> [DOCS] Sorting table contents in the articles.

- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/dlsdk_launcher_config.py
- tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py
Not sure if auto model search works for tflite -- changed this part since tf in present there.
> TFLite: direct load via frontend

- ci/requirements-openvino-dev.txt
- ci/update-requirements.py
- demos/common/python/requirements.txt
- demos/requirements.txt
- demos/tests/cases.py
- tools/model_tools/requirements-paddle.in
> Bump `scipy` package to a version supporting Python 3.11

- tools/accuracy_checker/openvino/tools/accuracy_checker/progress_reporters.py
Allow monitoring progress of accuracy validation regardless of a size of dataset.
> Report accuracy progress periodically based on elapsed time

- demos/common/cpp/models/src/segmentation_model.cpp
- demos/common/cpp/utils/include/utils/ocv_common.hpp
Fix for [EISW-83459](https://jira.devtools.intel.com/browse/EISW-83459)
[MTL-P][Corp] OpenVINO Segmentation Demo reports incorrect output on VPUX
It's back-merge of  https://github.com/openvinotoolkit/model_api/pull/63/files 
Plus, It introduces  layout guessing method based on the idea: C must be less then H and C must be less then W
> EISW-83459 [MTL-P][Corp] OpenVINO Segmentation Demo reports incorrect output on VPUX

- models/public/yolo-v3-tiny-tf/README.md
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3628
> Fix yolo-v3-tiny-tf description

- demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
- demos/tests/cases.py
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3697
> multi_camera_multi_target_tracking_demo: fix --output_video

- demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py
- demos/tests/data_sequences.py
Close https://github.com/openvinotoolkit/open_model_zoo/issues/3715
> multi_camera_multi_target_tracking_demo: fix ValueError: Input vector should be 1-D

- demos/3d_segmentation_demo/python/3d_segmentation_demo.py
- demos/tests/cases.py
> 3d_segmentation_demo: use `zoom` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated

- tools/accuracy_checker/openvino/tools/accuracy_checker/utils.py
- tools/accuracy_checker/requirements-core.in
- tools/model_tools/requirements.in
- tools/model_tools/src/openvino/model_zoo/_common.py
> Switched AC and OMZ to GA4.

- tools/model_tools/requirements-tensorflow.in
Synchronize with https://github.com/openvinotoolkit/openvino/pull/20372
> Updated TF version

- demos/classification_benchmark_demo/cpp_gapi/README.md
- removal of single `"` character causing doc build failure.
> fix nightly doc build

- README.md
- tools/accuracy_checker/openvino/tools/accuracy_checker/utils.py
- tools/accuracy_checker/requirements-core.in
- tools/model_tools/requirements.in
- tools/model_tools/src/openvino/model_zoo/_common.py
- Switch telemetry to opt-out in OMZ.
- Add info about telemetry to readme file.
> Switch telemetry to opt-out in OMZ.

- demos/background_subtraction_demo/cpp_gapi/CMakeLists.txt
- demos/tests/cases.py
OpenVINO version is updated in current master https://github.com/openvinotoolkit/openvino/pull/21790 so we can rely on it
> Temporary skip G-API background_subtraction_demo

- demos/text_detection_demo/cpp/include/text_detection.hpp
- demos/text_detection_demo/cpp/include/text_recognition.hpp
- demos/text_detection_demo/cpp/main.cpp
- demos/text_detection_demo/cpp/src/text_detection.cpp
- demos/text_detection_demo/cpp/src/text_recognition.cpp
Required for https://github.com/openvinotoolkit/openvino/pull/22429
> Removed runtime::Tensor usage

- tools/accuracy_checker/openvino/tools/accuracy_checker/evaluators/model_evaluator.py
- tools/accuracy_checker/tests/test_model_evaluator.py
Added fix and tests to check correct metrics selection.
> Correct selection of metrics with sub_evaluation disabled

- tools/accuracy_checker/accuracy_checker/metrics/image_quality_assessment.py
Allow use of local copy of models during validation
> Avoid certificate verify fails on Windows

- tools/model_tools/requirements-pytorch.in
Limit mpmath because of https://github.com/pytorch/pytorch/issues/120995 and https://github.com/sympy/sympy/issues/26273
> requirements-pytorch.in: Limit mpmath<1.4

- demos/common/python/model_zoo/model_api/pipelines/async_pipeline.py
> fix setting config for async pipeline

- demos/face_recognition_demo/python/faces_database.py
> demos/face_recognition: multiplying by 0.5

- tools/accuracy_checker/setup.py
Update the kenlm package revision to resolve errors during building wheels for kenlm on python 3.10
> Update kenlm in accuracy setup.py

- models/public/densenet-121-tf/README.md
- models/public/densenet-121-tf/model.yml
- models/public/densenet-121-tf/pre-convert.py
> Update densenet-121-tf to use modern keras API

- demos/README.md
- models/intel/index.md
- models/public/index.md
- tools/accuracy_checker/README.md
Fixing toctree directives in articles for the documentation at docs.openvino.ai
> [DOCS] Fixing toctree directives

- tools/model_tools/requirements-tensorflow.in
Align with https://github.com/openvinotoolkit/openvino/pull/26014
> Update tf upperbound

- tools/accuracy_checker/requirements-core.in
To be alignment with https://github.com/openvinotoolkit/openvino/pull/25508
> AC: set limit numpy to 2.1.0

- .github/workflows/accuracy_checker.yml
- .github/workflows/model_api.yml
- demos/requirements.txt
- tools/accuracy_checker/setup.py
> Drop Python 3.8
