demos/interactive_face_detection_demo/detectors.cpp

It looks for me that there is a bug in outputIdxPos calculation (line 616).
Because emotionsValues is a linear array with [face0emotion0, face0emotion1, ... face2emotion0... faceNemotion4], shift between face0emotion0 and faceNemotion0 is N*5, not N.
Here is output before and after fix checked on some random [image](http://www.pmamed.com/wp-content/uploads/2016/10/COPD_04_17_2018.jpg) of three happy people.
Because of index shift they get wrong final emotions.
[face_emotions_after_fix.txt](https://github.com/opencv/open_model_zoo/files/2856588/face_emotions_after_fix.txt)
[face_emotions_before_fix.txt](https://github.com/opencv/open_model_zoo/files/2856589/face_emotions_before_fix.txt)

Fix pointer error in face emotion detection demo

---

intel_models/text-detection-0001/description/text-detection-0001.md

According to original paper, the model name is PixelLink, not PixelNet. And second tensor output dimensions are [1x16x192x320], according to original paper and #31

Fix original NN name and output tensor dimensions.

---

intel_models/instance-segmentation-security-0033/description/instance-segmentation-security-0033.md
intel_models/instance-segmentation-security-0049/description/instance-segmentation-security-0049.md

Add percent characters for AP values of instance segmentation models

---

model_downloader/downloader.py
model_downloader/list_topologies.yml

Instead of hard-coding specific types of patches, allow defining per-file
regex replacements. This decouples the downloader from specifics of data
formats, making it more flexible.
Also, add some improvements to the postprocessing process:
* check that the file we're supposed to post-process exists and is located
inside the output directory;
* check that at least one replacement actually took place (because if not,
that indicates an error in the config);
* back up the original file, so that the user can examine the difference.
----
This is the first half of a series of changes that decouple the downloader from framework specifics. The second half will make downloading more generic, as well.

 model_downloader: make postprocessing more generic 

---

model_downloader/downloader.py
model_downloader/list_topologies.yml

This frees us from having to contort the meanings of "model" and "weights" to support various frameworks and makes it possible to support more than two files per model.
This change also makes the downloader keep the downloaded archive and all of its contents for models downloaded as archives. This is possible now, because the config now contains hashes for archives rather than their contents, and therefore the archives can be retrieved from a cache (when using one).
----
This is the second half of the series of changes started in #84. It completely decouples the downloader from framework specifics (in fact, the `framework` field in the config is now unused).

model_downloader: make the specification of files to download more generic

---

model_downloader/list_topologies.yml

* Make it a list rather than a string. This makes it possible to use the arguments regardless of what the system shell is. It's also a lot more human-readable.
* Replace the angle bracket placeholder syntax with shell-like variable substitutions. This will enable using Python's `string.Template` to substitute specific paths.
-----
This is a prelude to adding a tool that will automatically run Model Optimizer for each model using these arguments.

 model_downloader: make model_optimizer_args more machine-readable

---

model_downloader/downloader.py

It just leads to additional errors and crashes the downloader before it can print the list of failed topologies.

model_downloader: Don't attempt post-processing on topologies that failed to download

---

model_downloader/license.txt
model_downloader/list_topologies.yml

The server hosting the .caffemodel file for it appears to be defunct, so we can no longer support it.

Remove "dilation" from the model downloader config file

---

model_downloader/list_topologies.yml

model_downloader: don't download INT1 models into FP32 directories

---

tools/downloader/README.md
tools/downloader/converter.py

Also, make a couple of related changes:
* Rename `--download_root` into `--download_dir` for consistency with the other options. This script hasn't been a part of a release yet, so we don't need to retain the old name.
* Place converted models into a subdirectory corresponding to the precision (always "FP32" at the moment). This makes the directory structure more consistent between models that are converted and ones that are initially in the IR format, and will enable us to support alternate conversions in the future.

Add a model converter option to override the output directory

---

tools/downloader/README.md
tools/downloader/common.py
tools/downloader/converter.py
tools/downloader/downloader.py
tools/downloader/info_dumper.py

I expanded the name of this variable from "subdir", because I thought the abbreviated name was a bit too informal to expose.

info_dumper.py: expose each model's subdirectory

---

tools/downloader/common.py
tools/downloader/downloader.py

With our small chunk sizes, downloading large networks produces an obscene amount of output, which is hard to read in CI logs. Mitigate this by using a larger chunk size when standard output is not a terminal.
Also, don't attempt to overwrite the progress line when not printing to a terminal. It makes no sense, and it confuses programs that read the downloader's output into thinking that it's printing one giant line.

downloader.py: produce less output when not printing to a terminal

---

ci/requirements-ac.txt

I used pip-compile to create it, although I manually removed `opencv-python` from the resulting file, since I would prefer to use the OpenCV bindings included in OpenVINO.

Add a requirements file for Accuracy Checker CI

---

intel_models/inceptionv3-int8-sparse-v1-tf-0001/description/inceptionv3-int8-sparse-v1-tf-0001.md
intel_models/inceptionv3-int8-sparse-v2-tf-0001/description/inceptionv3-int8-sparse-v2-tf-0001.md
intel_models/inceptionv3-int8-tf-0001/description/inceptionv3-int8-tf-0001.md
intel_models/index.md
intel_models/mobilenetv2-int8-sparse-v1-tf-0001/description/mobilenetv2-int8-sparse-v1-tf-0001.md
intel_models/mobilenetv2-int8-sparse-v2-tf-0001/description/mobilenetv2-int8-sparse-v2-tf-0001.md
intel_models/mobilenetv2-int8-tf-0001/description/mobilenetv2-int8-tf-0001.md
intel_models/resnet-50-int8-sparse-v1-tf-0001/description/resnet-50-int8-sparse-v1-tf-0001.md
intel_models/resnet-50-int8-sparse-v2-tf-0001/description/resnet-50-int8-sparse-v2-tf-0001.md
intel_models/resnet-50-int8-tf-0001/description/resnet-50-int8-tf-0001.md

Added description for:
- ResNet-50 v1 INT8 quantized from TF
- ResNet-50 v1 INT8 quantized + sparse < 50% from TF
- ResNet-50 v1 INT8 quantized + sparse > 50% from TF
- Inception v3 INT8 quantized from TF
- Inception v3 INT8 quantized + sparse < 50%  from TF
- Inception v3 INT8 quantized + sparse > 50%  from TF
- MobileNet v2 INT8 quantized from TF
- MobileNet v2 INT8 quantized + sparse < 50%  from TF
- MobileNet v2 INT8 quantized + sparse > 50%  from TF

Added description for compressed models

---

tools/accuracy_checker/accuracy_checker/metrics/detection.py
tools/accuracy_checker/accuracy_checker/metrics/metric.py

the problem is the same as in https://github.com/opencv/open_model_zoo/pull/169, but this condition checked very rarely in usage dldt tools with pregenerated annotation pickles (happed only on several datasets from private part)

[Accuracy Checker]: fix namespace compatibility bug

---

models/public/alexnet/alexnet.md
models/public/densenet-121/densenet-121.md
models/public/densenet-161/densenet-161.md
models/public/densenet-169/densenet-169.md
models/public/densenet-201/densenet-201.md
models/public/googlenet-v1/googlenet-v1.md
models/public/googlenet-v2/googlenet-v2.md
models/public/googlenet-v4/googlenet-v4.md
models/public/inception-resnet-v2/inception-resnet-v2.md
models/public/mobilenet-ssd/mobilenet-ssd.md
models/public/mtcnn-o/mtcnn-o.md
models/public/mtcnn-p/mtcnn-p.md
models/public/mtcnn-r/mtcnn-r.md
models/public/squeezenet1.0/squeezenet1.0.md
models/public/squeezenet1.1/squeezenet1.1.md
models/public/ssd300/ssd300.md
models/public/ssd512/ssd512.md
models/public/ssd_mobilenet_v2_coco/ssd_mobilenet_v2_coco.md
models/public/vgg16/vgg16.md
models/public/vgg19/vgg19.md

Here presented draft version of public models documentation. Documentation represents markdown file, as documentation for intel models. All docs located in `models/public/<model name>` directories, and files are named after model name. Model name is taken from `list_topologies.yml`. Model descriptions are from [https://software.intel.com/en-us/articles/model-downloader-essentials](https://software.intel.com/en-us/articles/model-downloader-essentials)
Note: description for `dilataion` model exists, but it is removed from `list_topologies.yml`

Documentation for public model

---

demos/security_barrier_camera_demo/main.cpp

Earlier
./intel64/Release/security_barrier_camera_demo -i openvino_2019.2.201/deployment_tools/demo/car_1.bmp -m vehicle-license-plate-detection-barrier-0106.xml -m_va vehicle-attributes-recognition-barrier-0039.xml -no_show
could result in Segmentation fault (core dumped).
The reason was exiting the demo while IE still runs async inference

security_barrier_camera_demo: fix -no-show segfault

---

tools/downloader/README.md
tools/downloader/common.py

Current print_all printing all topologies in non-sorted manner.
Order all topologies for print_all to print sorted topologies.
Signed-off-by: Yeoh Ee Peng <ee.peng.yeoh@intel.com>

downloader/common.py: Order all topologies for print_all

---

tools/accuracy_checker/accuracy_checker/utils.py
tools/accuracy_checker/setup.py

usually, input data for inference in accuracy checker is ndarray. But there is model NCF where input is one scalar value. This fix handles this issue.
P.S. priority is very small, the model is not in OMZ and even has not been added to public validation yet, due to another issue related to dataset conversion.

Accuracy Checker: fix getting input data shape for scalar data

---

demos/README.md
demos/crossroad_camera_demo/README.md
demos/gaze_estimation_demo/README.md
demos/human_pose_estimation_demo/README.md
demos/interactive_face_detection_demo/README.md
demos/mask_rcnn_demo/README.md
demos/multichannel_demo/fd/README.md
demos/multichannel_demo/hpe/README.md
demos/object_detection_demo_faster_rcnn/README.md
demos/object_detection_demo_ssd_async/README.md
demos/object_detection_demo_yolov3_async/README.md
demos/pedestrian_tracker_demo/README.md
demos/python_demos/3d_segmentation_demo/README.md
demos/python_demos/action_recognition/README.md
demos/python_demos/instance_segmentation_demo/README.md
demos/python_demos/object_detection_demo_ssd_async/README.md
demos/python_demos/object_detection_demo_yolov3_async/README.md
demos/python_demos/segmentation_demo/README.md
demos/security_barrier_camera_demo/README.md
demos/segmentation_demo/README.md
demos/smart_classroom_demo/README.md
demos/super_resolution_demo/README.md
demos/text_detection_demo/README.md

Since we've finally moved the demos to this repo, there's no longer a reason to use absolute links to refer to other stuff in this repo. Doing so is wrong anyway, since we can't guarantee that the master branch (or any other) will hold any given content in the future.
Also, fix one of those links, which was broken.

demos: replace links to the repository with relative links

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

in accuracy valiation enabled a workaround for models which can not be reshaped in runtime, until bug in dldt not fixed.
Calibration tool can not get per layer statistic if model reloaded without output specification.
This PR should help calibration turn off network reloading in reshaping (they do not use such validation approach for networks)

accuracy checker: made workaround flag switched

---

models/public/Sphereface/Sphereface.md
models/public/densenet-121/densenet-121.md
models/public/densenet-161/densenet-161.md
models/public/densenet-169/densenet-169.md
models/public/densenet-201/densenet-201.md
models/public/mobilenet-v1-1.0-224-tf/mobilenet-v1-1.0-224-tf.md
models/public/mobilenet-v1-1.0-224/mobilenet-v1-1.0-224.md
models/public/mobilenet-v2-1.4-224/mobilenet-v2-1.4-224.md
models/public/mobilenet-v2/mobilenet-v2.md
models/public/resnet-101/resnet-101.md
models/public/resnet-152/resnet-152.md
models/public/resnet-50/resnet-50.md
models/public/se-inception/se-inception.md
models/public/se-resnet-101/se-resnet-101.md
models/public/se-resnet-152/se-resnet-152.md
models/public/se-resnet-50/se-resnet-50.md
models/public/se-resnext-101/se-resnext-101.md
models/public/se-resnext-50/se-resnext-50.md

Added documentation to rest public models. Descriptions are taken from `list_topologies.yml`.
Also, fixed naming for MobileNet V2 from TF

Public model documentation

---

tools/accuracy_checker/accuracy_checker/progress_reporters.py

in pipelining mode, second evaluation finishes without dataset processibng, because progress has not been reset

accuracy checker: fix progress reporter state after finishing

---

demos/python_demos/action_recognition/README.md
demos/python_demos/action_recognition/action_recognition.py

Was done:
1) Renamed demo.py to action_recognition.py, like other samples has the name of script equal with its folder
2) Change -e to -l - it is also standard of all samples.
3) As -l in this sample means labels, renamed it to -lb. Because -l is always for custom cpu lib.
4) Combined two option in one: --video_list and --video and renamed it to --input -i (like in other samples)
5) Renamed  -encoder and -decoder to  --m_encoder -m_en &  --m_decoder  -m_de  
6) Changed README file in accordance with the above changes and also added required parameter in "For example" section.

changes in action_recognition_demo for unification with оther demos

---

demos/smart_classroom_demo/action_event_metrics.py

__xrange()__ was removed in Python 3 in favor of a re-worked version of __range()__.  This PR assures equivalent functionality in both Python 2 and Python 3.  Fixes #130

Redefine range() in Python 2

---

demos/common/samples/common.hpp

Currently Core::GetAvailableDevices() will not print HDDL as available in any case. To avoid regression in the list of demos' supported devices (shown in help messages) we will just print HDDL as available as it was in R1.

demos: print HDDL as available

---

tools/downloader/downloader.py

The cache can be on a remote filesystem, so retrieving a big file from it could take a while. Flush stdout before doing it to make the log better reflect the current state of the download process when stdout is buffered (e.g. when it's redirected to a pipe).

downloader: flush stdout before retrieving something from the cache

---

demos/human_pose_estimation_demo/include/human_pose_estimator.hpp
demos/human_pose_estimation_demo/src/human_pose_estimator.cpp

With uint8 input and Myriad NCS2 device we can achieve better efficiency in case of USB 2.0:
FPS @ 456x256:
| USB | before | with PR |
|---|---|---|
|  2.0 | 3.78 | **4.02** (x1.06) |
|  3.0 | 4.71 | 4.7 |

U8 input for Human Pose Estimation Demo

---

demos/README.md

Removed `adas` from model name in demos readme.

Removed adas from human pose estimation name in readme

---

models/public/octave-densenet-121-0.125/octave-densenet-121-0.125.md
models/public/octave-resnet-101-0.125/octave-resnet-101-0.125.md
models/public/octave-resnet-200-0.125/octave-resnet-200-0.125.md
models/public/octave-resnet-26-0.25/octave-resnet-26-0.25.md
models/public/octave-resnet-50-0.125/octave-resnet-50-0.125.md
models/public/octave-resnext-101-0.25/octave-resnext-101-0.25.md
models/public/octave-resnext-50-0.25/octave-resnext-50-0.25.md
tools/downloader/license.txt
tools/downloader/list_topologies.yml

Added modificated with octave convolutions models:
- densenet-121 (&alpha;=0.125) 
- resnet-26 (&alpha;=0.25)
- resnet-50 (&alpha;=0.125)
- resnet-101 (&alpha;=0.125)
- resnet-200 (&alpha;=0.125)
- resnext-50 (&alpha;=0.25)
- resnext-101 (&alpha;=0.25)
[Paper](https://arxiv.org/abs/1904.05049)
[Source](https://github.com/facebookresearch/OctConv)
[License](https://raw.githubusercontent.com/facebookresearch/OctConv/master/LICENSE)

[MXNET] OctConv networks

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/detection.py

From one to other MO running model can have different suffixes for output layers.
It can become a problem for inplace conversion during Accuracy Checker running.

AC: allows to use regular expression instead of full output layer name for ssd pytorch

---

ci/requirements-ac.txt
ci/requirements-conversion.txt
ci/requirements-downloader.txt

~Except for numpy in `requirements-ac.txt`, which needs to stay at 1.16 due to an issue with Pylint.~
EDIT: Bumped numpy too.

ci/requirements-*.txt: bump all versions

---

.gitattributes

Attributes need to be applied to files, not directories.

Fix the omz.package attribute for demo tests

---

.gitattributes
tools/downloader/tests/representative-models.lst

These models cover the full spectrum of downloader and converter features, while weighting ~100 times less than the full set. We can use this list to make precommit builds take much less time while still being reasonably comprehensive.

Add a list of representative models for downloader testing

---

demos/pedestrian_tracker_demo/src/cnn.cpp
demos/tests/cases.py

Earlier only models with NC layout were supported.

Add supporting reid models with NCHW layout to pedestrian_tracker_demo

---

demos/python_demos/object_detection_demo_yolov3_async/README.md
demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py

YOLOv2 origin:
https://pjreddie.com/darknet/yolov2/
Classes names:
https://github.com/opencv/opencv/blob/master/samples/data/dnn/object_detection_classes_yolov3.txt
https://github.com/opencv/opencv/blob/master/samples/data/dnn/object_detection_classes_pascal_voc.txt
OpenVINO's HowTo:
http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html
**NOTE**: For YOLOv2 `--scale 255` is required:
```
python3 mo_tf.py --input_model yolov2.pb --batch 1 \
--tensorflow_use_custom_operations_config extensions/front/tf/yolo_v2.json \
--scale 255
```

Fix sample to work with YOLOv2

---

tools/downloader/common.py
tools/downloader/converter.py
tools/downloader/downloader.py
tools/downloader/info_dumper.py

So far we've been treating the words "topology" and "model" synonymously, which is both incorrect and confusing. The user-facing documentation (as well as the tools' names) uses "model", so update the internals to match.
Strictly speaking, "model" isn't correct either, since the things we call models are actually families of different-precision models. However, the difference is minor enough that I think we can ignore it.
The only occurrence of "topology" that remains is the name of the key in the deprecated combined config file format.

tools/downloader: purge the "topology" term

---

models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md

originally, ref metrics were obtained with IR from some old OpenVINO version and unknown OpenCV version. This PR updates metrics with using model in source framework format and OpenCV 4.1.1-openvino

update ref metric values for person-vehicle-bike-detection-crossroad-0078

---

models/intel/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.md

Its webpage has been down for a couple of weeks now, and it's breaking our link checking job. We'll have to remove the link, at least for now.

Unlink the BIT-Vehicle dataset

---

tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/opencv/open_model_zoo on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py:132:20: F821 undefined name 'maskUtils'
rles = maskUtils.frPyObjects(mask, height, width)
^
./tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py:133:19: F821 undefined name 'maskUtils'
rle = maskUtils.merge(rles)
^
./tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py:136:19: F821 undefined name 'maskUtils'
rle = maskUtils.frPyObjects(mask, height, width)
^
./tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py:158:26: F821 …
```

Use maskUtils to match the import on line 113

---

models/public/densenet-121-tf/model.yml
models/public/densenet-161-tf/model.yml
models/public/densenet-169-tf/model.yml

Model Optimizer doesn't need it (and, in fact, ignores it) when `--input_meta_graph` is specified.

models/public/densenet-*-tf: remove the --input_checkpoint option

---

README.md

We want the README file in the OpenVINO package to say R3, and for that to happen we need to bump the release number before the release.
This does mean that the README will be pointing to a nonexistent tag until the release is out.

Preemptively bump the release number in the badge

---

tools/accuracy_checker/setup.py

python3.7 does not have prebuilt scipy version

AC: upgrade scipy version requirements

---

demos/python_demos/multi_camera_multi_person_tracking/models.lst

The demo supports only single input nets, while person-detection-retail-0002 has two inputs.

multi_camera_multi_person_tracking: remove person-detection-retail-0002

---

tools/accuracy_checker/accuracy_checker/data_readers/README.md
tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
tools/accuracy_checker/accuracy_checker/postprocessor/resample_segmentation_prediction.py
tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
tools/accuracy_checker/accuracy_checker/postprocessor/zoom_segmentation_mask.py
tools/accuracy_checker/setup.py

removed `scipy.misc.imread` and `scipy.misc.imresize` usage. Changes allow deleting restriction on supported scipy version

AC: remove usage deprecated scipy image api

---

tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
tools/accuracy_checker/accuracy_checker/metrics/hit_ratio.py
tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py

majority of supported metrics are iterative with updating internal state, so whole range annotations and predictions in `evaluate` signature is not used for them.
Removing annotations and predictions batch if possible can reduce memory consumption.

AC: do not store annotation and predictions if they is not used for metric evaluation

---

tools/accuracy_checker/requirements.in
tools/accuracy_checker/setup.py

This makes it easier to use pip-compile on it.
Turn `tests_requirements` into a list, which is both shorter and consistent with `requirements`.

tools/accuracy_checker: move the list of dependencies to a standalone file

---

tools/downloader/README.md

The official macOS Python 3.5 binaries are linked with system OpenSSL, which doesn't support TLS 1.2. Unfortunately, some of our file sources only support TLS 1.2 and up.
The workaround is to install 'requests[security]', which includes pyOpenSSL (which Requests will automatically use if it's available).
Since Python 3.6, the official binaries bundle a newer version of OpenSSL, so the issue no longer exists.

tools/downloader: Document a workaround for a TLS connection issue

---

tools/downloader/downloader.py

I accidentally removed this in #345.

tools/downloader/downloader.py: restore the correct exit code on failure

---

demos/tests/cases.py

This demo assumes by default that the action recognition model recognizes 3 actions, but person-detection-raisinghand-recognition-0001 only recognizes 2. This causes the demo to go out of bounds when retrieving the action probabilities.
We could fix it by adding a `-student_ac` option to the test case, but a better fix is to use the top-k mode (via the `-a_top` option) for this model, since:
a) in top-k mode the demo already defaults to 2 actions; and
b) this gives us better code coverage.
In top-k mode the other 3 models aren't used, so don't add cases with them.

demos/tests/cases.py: avoid an out-of-bounds access in smart_classroom_demo

---

demos/tests/cases.py

`libcpu_extension.so` is going to be merged into the CPU plugin in IE 2019 R4, so don't add the `-l` option if it isn't present. This will allow the test script to work with both R3 and R4. After R4 is released, we can remove the passing of the option entirely.

demos/tests/cases.py: prepare for the disappearance of libcpu_extension.so

---

tools/accuracy_checker/accuracy_checker/adapters/text_detection.py

in case, when adapter created before dataset selection, we can not set `label_map`

AC: fix text detection

---

tools/downloader/converter.py

Currently, when we are in multithreaded mode, we prefix each output line with the name of the thread to disambiguate it. This makes the output unambiguous, but also very ugly and difficult to read.
So remove that logic, and instead make it so that the output of the converter in multithreaded mode is exactly like it is in single-threaded mode. Do it by buffering each job's output in an queue, and emptying each such queue into stdout in turn.
The downside of this approach is that we have to keep in memory the output of all jobs whose turn hasn't come yet, and that output can potentially be unbounded. However, it shouldn't be a problem in practice, since the amount of output produced by the conversion tools we run (and the converter itself) is fairly small. It's probably also less efficient …

tools/downloader/converter.py: serialize output of concurrent jobs

---

demos/common/samples/common.hpp
demos/crossroad_camera_demo/main.cpp
demos/gaze_estimation_demo/main.cpp
demos/human_pose_estimation_demo/include/human_pose_estimator.hpp
demos/human_pose_estimation_demo/src/human_pose_estimator.cpp
demos/human_pose_estimation_demo/src/peak.cpp
demos/human_pose_estimation_demo/src/render_human_pose.cpp
demos/interactive_face_detection_demo/detectors.cpp
demos/interactive_face_detection_demo/main.cpp
demos/mask_rcnn_demo/main.cpp
demos/multi_channel/human_pose_estimation_demo/peak.cpp
demos/multi_channel/human_pose_estimation_demo/render_human_pose.cpp
demos/security_barrier_camera_demo/net_wrappers.hpp
demos/smart_classroom_demo/main.cpp

The impetus for this is that an internal static analysis tool gets confused by vectors initialized with initializer lists. However, it's a good change in its own right: by using arrays we avoid unnecessary dynamic allocation and, in some cases, dynamic initialization.
In one case, the vector isn't necessary at all (it shadows another identical vector), so remove it completely.

demos: replace vectors with arrays where possible

---

demos/mask_rcnn_demo/main.cpp

There's no guarantee that the number of unique classes in the image is less than the number of colors, so use a remainder operation to wrap the color index.
Also, change the way that `class_color` is populated to prevent dependence on evaluation order. Evaluating `class_color[class_id]` can change the size, so the color indexes could change depending on whether the LHS or the RHS was evaluated first. Use `emplace` to set the default value instead.

demos/mask_rcnn_demo: prevent OOB accesses to the colors array

---

demos/security_barrier_camera_demo/README.md
demos/security_barrier_camera_demo/net_wrappers.hpp
demos/tests/cases.py

- `license-plate-recognition-barrier-0001` model converted from Caffe and have two input blobs
- implementation this LPR model in [TensorFlow from openvino_training_extensions](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr) have one

Add compatibility with LPR model from openvino_training_extensions

---

demos/smart_classroom_demo/README.md
demos/smart_classroom_demo/include/face_reid.hpp
demos/smart_classroom_demo/include/smart_classroom_demo.hpp
demos/smart_classroom_demo/include/tracker.hpp
demos/smart_classroom_demo/main.cpp
demos/smart_classroom_demo/src/reid_gallery.cpp
demos/smart_classroom_demo/src/tracker.cpp

The greedy matcher allows to run the demo in the cases when 
the number of gallery images is greater than 1000, although it
may decrease quality of face reidentification a bit.

Add greedy matcher to smart classroom demo

---

tools/accuracy_checker/accuracy_checker/config/config_validator.py
tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/accuracy_checker/launcher/launcher.py
tools/accuracy_checker/accuracy_checker/presenters.py
tools/accuracy_checker/custom_evaluators/sequential_action_recognition_evaluator.py
tools/accuracy_checker/tests/test_dlsdk_launcher.py

moving from deprecated IEPlugin API to IECore API
clean up launcher tests (removed part for working with adapter because adapter is independent entry now)
TO DO:

AC: moving on IECore API

---

demos/common/samples/common.hpp
demos/object_detection_demo_faster_rcnn/CMakeLists.txt
demos/object_detection_demo_faster_rcnn/main.cpp
demos/object_detection_demo_faster_rcnn/object_detection_demo_faster_rcnn.h

This allows us to remove a ton of redundant code, at the cost of a couple slight disadvantages:
* the demo now requires OpenCV to build, which shouldn't be a problem,   since nearly every other demo does so as well (the only exception being segmentation_demo);
* the demo no longer accepts files in the MNIST format as input, which also shouldn't be a problem, since it doesn't make sense to run object detection on the MNIST dataset.

OpenCV-ify object_detection_demo_faster_rcnn

---

demos/python_demos/segmentation_demo/segmentation_demo.py

To avoid out of memory error it is required just set input precision
for the model to U8 to avoid loading the input image as FP32 blob.

Fix segmentation_demo out of memory error on MYRIAD (CVS-23795)

---

tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py

make onnx runtime launcher work when batch is ommited.
it is necessary for Pytorch/ONNX mask rcnn support (e.g this [model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn))

AC: support 3 dim tensors for ONNX runtime

---

tools/accuracy_checker/accuracy_checker/metrics/semantic_segmentation.py
tools/accuracy_checker/tests/test_segmentation_metrics.py

metrics should ignore classes where predictions do not exists. Result finalization skip only nan, inf values and treat zero as valid result while for these metrics it means that label should be ignored (icnet/unet trained on camvid do not have objects for unlabled class and it should not affect metric result)

AC: fix segmentation metrics for non-existed classes

---

models/public/octave-densenet-121-0.125/model.yml
models/public/octave-resnet-101-0.125/model.yml
models/public/octave-resnet-200-0.125/model.yml
models/public/octave-resnet-26-0.25/model.yml
models/public/octave-resnet-50-0.125/model.yml
models/public/octave-resnext-101-0.25/model.yml
models/public/octave-resnext-50-0.25/model.yml
models/public/octave-se-resnet-50-0.125/model.yml

Model Optimizer ignores it unless `--nd_prefix_name` and `--pretrained_model_name` are also specified, and in the next MO release, specifying this option alone is an error.

models: remove the --input_symbol option

---

tools/accuracy_checker/accuracy_checker/config/config_reader.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/accuracy_checker/launcher/model_conversion.py
tools/accuracy_checker/accuracy_checker/main.py
tools/accuracy_checker/tests/test_config_reader.py
tools/accuracy_checker/tests/test_dlsdk_launcher.py

`--tf_custom_operation_config` option in MO is deprecated in this release.  (now in the latest versions DLDT, it raises deprecation warning). MO team recommend to replace it with `--transformations_config` 
P.S. Probably it also should affect Model Downloader configs for some TF models.

AC: support MO transformations config option

---

tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
tools/accuracy_checker/tests/test_onnx_launcher.py

new ONNX Runtime has ability of hardware acceleration with [Execution Providers API](https://github.com/microsoft/onnxruntime#high-performance). One of EP is [OpenVINO](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/OpenVINO-ExecutionProvider.md), on my view, it is potentially important to be able evaluate ONNX models with this API.
old Backend API feautres stayed for backward compatibility.

AC: update ONNX Runtime launcher for work with Execution Providers

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/detection.py

same yolo v3 models has parameter `mask` for selection anchors for specific output layer.
yolo v3 demo is able to handle this case correctly because it check layer parameters and process using OpenVINO specifically approach.
Unforutnately, accuracy checker detections processing is framework agnostic. It is the reason why we need to put this parameter explicitly in the config.

AC: support Yolo v3 with mask parameter in output

---

demos/smart_classroom_demo/main.cpp

AKA "the things I forgot to do in #658".
* the comment is wrong (it was a remnant of an earlier version of the code that I forgot to change);
* `face_config` isn't used in the body of the `if`, while `fd_model_path` is, so it makes more sense to check the latter.

smart_classroom_demo: Fix trivial issues

---

demos/common/samples/args_helper.hpp

In Linux, MYRIAD M.2 form factor enumurates as "MYRIAD./dev/mxlk0:0".
This conflicts with the current implementation of parseDevices
which accounts only for MULTI or HETERO having a":" in devicename.
This fix allows to have multiple ":" in devcename and yet parse them correctly.

Fix parseDevices() to enumerate multi-VPUs

---

demos/crossroad_camera_demo/crossroad_camera_demo.hpp
demos/gaze_estimation_demo/gaze_estimation_demo.hpp
demos/human_pose_estimation_demo/include/human_pose_estimation_demo.hpp
demos/interactive_face_detection_demo/interactive_face_detection.hpp
demos/mask_rcnn_demo/mask_rcnn_demo.h
demos/multi_channel/common/multichannel_params.hpp
demos/multi_channel/face_detection_demo/multichannel_face_detection_params.hpp
demos/multi_channel/object_detection_demo_yolov3/multichannel_object_detection_demo_yolov3_params.hpp
demos/object_detection_demo_faster_rcnn/object_detection_demo_faster_rcnn.h
demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.hpp
demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.hpp
demos/pedestrian_tracker_demo/include/pedestrian_tracker_demo.hpp
demos/security_barrier_camera_demo/security_barrier_camera_demo.hpp
demos/segmentation_demo/segmentation_demo.h
demos/smart_classroom_demo/include/smart_classroom_demo.hpp
demos/super_resolution_demo/super_resolution_demo.h
demos/text_detection_demo/text_detection_demo.hpp

They take up space and carry no information that isn't already present in the help messages themselves.

demos: remove useless comments from command line flags and help messages

---

tools/accuracy_checker/accuracy_checker/annotation_converters/cityscapes.py

usage predefined converted annotations converted on Linux broken during usage on Windows machine due to casting types. This fix for that case.

AC: fix cityscapes converter

---

README.md

There are a few reasons why:
1. It's broken.
2. I don't want to maintain links to different Jenkins jobs in different branches.
3. I'm thinking of removing the nightly trigger job and having the individual task jobs trigger themselves, so there won't even be anything to link to.

Remove the Jenkins link from the README

---

demos/common/monitors/presenter.cpp

Enable build for old gcc which doesn't have `basic_ostringstream(basic_ostringstream&&)` constructor.
It also makes more sense to use `basic_ostringstream(ios_base::openmode mode)`.

demos/monitors: update strStream init

---

tools/accuracy_checker/accuracy_checker/metrics/reid.py

in upcoming sklearn version the metric.base API become a private and can not be called in the user code. Replace `_average_binary_score` with own implementation

AC: replace usage deprecated APi from sklearn

---

demos/smart_classroom_demo/include/action_detector.hpp
demos/smart_classroom_demo/include/cnn.hpp
demos/smart_classroom_demo/include/detector.hpp
demos/smart_classroom_demo/main.cpp
demos/smart_classroom_demo/src/action_detector.cpp
demos/smart_classroom_demo/src/detector.cpp
demos/smart_classroom_demo/src/reid_gallery.cpp

Instead, use the null object pattern to disable a detector when the corresponding model option is unspecified.
My original aim with this was to fix static analyzer warnings about the fields of `ActionDetection` not being initialized (which they weren't, when `enabled` was false). I think it's a good change in its own right, though, since it applies the Single Responsibility Principle by separating the "detection enabled" and "detection disabled" behavior into different classes.

smart_classroom_demo: remove the enabled fields from detector configs

---

models/intel/person-reidentification-retail-0103/description/person-reidentification-retail-0103.md
models/intel/person-reidentification-retail-0107/description/person-reidentification-retail-0107.md
models/intel/person-reidentification-retail-0200/description/person-reidentification-retail-0200.md

fix missed '%' sign in ref metric representation

fix ref metrics representation (missed % sign)

---

models/public/face-recognition-resnet100-arcface/model.yml
tools/downloader/downloader.py

This has two benefits:
1. it makes sure file sizes are set correctly in the config files and therefore that we are reporting correct progress information;
2. if a download fails because the file on the remote server was replaced with an unrelated file, a size mismatch message will communicate more information than a hash mismatch message.
Also, break early if we receive more data than we expect. It's more efficient and it prevents a server from filling up the local file system by sending a very large (or even infinite) file.

downloader: check the size of the received file before checking the hash

---

demos/python_demos/face_recognition_demo/README.md
demos/python_demos/image_retrieval_demo/README.md
demos/python_demos/instance_segmentation_demo/README.md

It will no longer exist as a separate library in the next release of Inference Engine.

Eradicate the remaining mentions of libcpu_extension

---

demos/human_pose_estimation_demo/main.cpp
demos/python_demos/human_pose_estimation_3d_demo/human_pose_estimation_3d_demo.py

It's irrelevant, and external users don't know what that is.

Remove mentions of "ICV"

---

tools/downloader/README.md

It being unescaped makes the GitHub syntax highlighter think the rest of the file is italicized, which is annoying. See:
https://github.com/opencv/open_model_zoo/blame/372c3b5d8/tools/downloader/README.md#L53

Escape a special character in tools/downloader/README.md

---

tools/accuracy_checker/accuracy_checker/adapters/yolo.py

in openvino YoloRegion layer is flatten with shape ([batch, 125х13х13]), in TF implementation it is 4 dim tensor with shape [batch, 125, 13, 13].
Adopt yolo_v2 adapter to work for both cases,

AC: support yolo v2 TF

---

tools/accuracy_checker/accuracy_checker/dataset.py

remove extra check, which made else condition unreachable (according common-accepted dataset structure, it is rare case. It the reason why nobody know about this problem, but potentially better to fix due to ability to shuffle data)

AC: fix pairwise subset logic

---

.gitattributes
ci/get-jobs-for-changes.py

Currently, this determination is done by a similar script in an internal repository used by the CI jobs. There are, however, a few advantages to having this script in the main repo:
* It's easier to effect project layout changes, since we can update the attributes and/or the script in the same PR in which we update the layout, thus avoiding periods where the project is desynchronized from the CI logic.
* Different branches can contain different versions of the script, which lets us configure CI logic per-branch without special-casing it in the CI scripts.
* We can use Git attributes to specify most of the job triggering policy, which lets us easily create fine-grained rules.
* It's more transparent to external users.
Admittedly, since the actual definitions of CI jobs are still in an …

Add a script that determines which CI jobs to run for a pull request

---

tools/downloader/README.md
tools/downloader/common.py

In the next release, there will be quantized models based on both FP32 and FP16, so additional precision IDs will be necessary to distinguish them.
We should be able to remove the old INT1/INT8 IDs in the future, but for now we still have models using them, so they have to stay.

downloader: add more supported precisions in preparation for the next release

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/configs/faster_rcnn_resnet50_coco.yml

VPU_LOG_LEVEL is deprecated, use LOG_LEVEL instead.

AC: replace deprecated config option for vpu logging

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py

in the original CMU openpose  implementation part affinity fields and keypoints heatmaps joined to the one layer. It is difficult to get intermediate blob in the Caffe (no restriction select another layers during model conversion via MO), so I extend adapter for human-pose-estimation to cover Caffe openpose model

AC: adopt human pose adapter to work with openpose

---

tools/accuracy_checker/dataset_definitions.yml

removed cpu_extensions usage in global_definitions (removed in the package in upcoming release)

AC: remove cpu_extension from dataset definitions

---

tools/downloader/requirements-pytorch.in

While a PyTorch developer claims that a new version of torchvision with the bugfix will be released soon, that has not happened yet, and it might not happen until after our next release. So I'm applying a workaround anyway.

requirements-pytorch.in: work around a torchvision bug

---

demos/python_demos/instance_segmentation_demo/instance_segmentation_demo.py

For Ubuntu16 the demo drew wrong masks sometimes.
I was deleting and returning back parts of the demo's code to find what causes it.
It appeared, that deleting the line `del net` fixes the issue.
Delete `del exec_net` and `del ie` just because they are not really needed.

instance_segmentation: fix

---

demos/crossroad_camera_demo/README.md

person-reidentification-retail-0079 was removed.

crossroad_camera: replace person-reidentification-retail 0079 with 0031

---

tools/accuracy_checker/configs/road-segmentation-adas-0001.yml

accidentally missed metrics in OMZ config

AC configs: fix missed metrics section in road-segmentation-adas-0001

---

demos/python_demos/object_detection_demo_centernet/detector.py

NumPy 1.15 is when the axis parameter was made optional.
The NumPy version in the Ubuntu 18.04 repositories is 1.13, so it would be good to be compatible with that.

object_detection_demo_centernet: make compatible with NumPy < 1.15

---

README.md

We have merged everything that was intended for the 2020.1 release, so even though the release isn't out yet, I think it makes sense to open the branch to changes for the next one. If it turns out we need to fix something for the current release after all, I'll just create a `release` branch and we'll merge it there.

Bump the version for the next release

---

demos/text_detection_demo/README.md
demos/text_detection_demo/include/text_recognition.hpp
demos/text_detection_demo/main.cpp
demos/text_detection_demo/src/text_recognition.cpp
demos/text_detection_demo/text_detection_demo.hpp

Add another decoder method for text recognition. Just using the flag `-b` to assign bandwidth, default is `0`. If the bandwidth larger than `0` will use CTC beam search decoder, bandwidth is `0` will use CTC greedy decoder, and bandwidth is lower than `0` will show an error message and stop the program.

Add ctc beam search decoder for text_detection demo

---

demos/CMakeLists.txt
demos/crossroad_camera_demo/main.cpp
demos/gaze_estimation_demo/main.cpp
demos/gaze_estimation_demo/src/utils.cpp
demos/interactive_face_detection_demo/detectors.cpp
demos/interactive_face_detection_demo/main.cpp
demos/mask_rcnn_demo/main.cpp
demos/multi_channel/common/CMakeLists.txt
demos/multi_channel/common/graph.cpp
demos/multi_channel/face_detection_demo/CMakeLists.txt
demos/multi_channel/human_pose_estimation_demo/CMakeLists.txt
demos/multi_channel/object_detection_demo_yolov3/CMakeLists.txt
demos/object_detection_demo_faster_rcnn/main.cpp
demos/object_detection_demo_ssd_async/main.cpp
demos/object_detection_demo_yolov3_async/main.cpp
demos/pedestrian_tracker_demo/src/utils.cpp
demos/security_barrier_camera_demo/main.cpp
demos/segmentation_demo/main.cpp
demos/smart_classroom_demo/main.cpp
demos/super_resolution_demo/main.cpp
demos/text_detection_demo/main.cpp

It's no longer needed with the current Inference Engine.

Remove cpu_extension compatibility code

---

demos/object_detection_demo_faster_rcnn/detectionoutput.h
demos/object_detection_demo_faster_rcnn/main.cpp

Originally I set out to remove the usage of a soon-to-be deprecated `InferenceEngine::Data` constructor (see the first commit), but then I noticed that the code that constructor is used in is rather superfluous, so I ended up refactoring the demo to remove it entirely.
See the commit messages for more information.

Simplify post-processing in object_detection_demo_faster_rcnn

---

tools/accuracy_checker/accuracy_checker/metrics/average_meter.py

We're dividing by `increment`, so that's what we should be checking. This was probably a copy-paste error from `evaluate`.

AC: fix a divide-by-zero warning in AverageMeter

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/accuracy_checker/preprocessor/README.md
tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
tools/accuracy_checker/accuracy_checker/preprocessor/color_space_conversion.py

for unet2d where used only single channel was implemented functional for getting specified channel inside the launcher. It is wrong solution, because make a lot of inconvenience for working with non-default layout and lead to unexpected behaviour for models working with grayscale images.
Necessary logic moved to preprocessor.

AC: remove durty hack for channels alignment in launcher

---

demos/mask_rcnn_demo/README.md
demos/mask_rcnn_demo/main.cpp
demos/mask_rcnn_demo/mask_rcnn_demo.h

The documented output is `reshape_do_2d`, not `detection_output`. The current code has worked so far, because a layer named `detection_output` also exists in the network; however, it's an internal layer and we shouldn't be relying on it.
Note that currently, `detection_output` is also marked by MO as an output (unless you use IR v7). This might, however, be a bug. An internal report already exists for it.

mask_rcnn_demo: use the documented output of the models

---

tools/downloader/downloader.py

This avoid rereading the entire file from disk once it's written.

downloader: hash files while they're downloading

---

demos/security_barrier_camera_demo/README.md

modify security_barrier_camera_demo readme for using all Intel® Vision Accelerator Design with Intel® Movidius™ VPUs computation ability.
(1) -n_iqs 10: associated with the number of cores in Intel® Vision Accelerator Design with Intel® Movidius™ VPUs.
(2) -n_wt 4: associated with the number of cores in CPU
(3) -nireq 10: associated with the number of cores in Intel® Vision Accelerator Design with Intel® Movidius™ VPUs.

modify security_barrier_camera_demo readme for using all Intel® Vision Accelerator Design with Intel® Movidius™ VPUs computation ability.

---

demos/README.md
demos/crossroad_camera_demo/README.md
demos/gaze_estimation_demo/README.md
demos/human_pose_estimation_demo/README.md
demos/interactive_face_detection_demo/README.md
demos/mask_rcnn_demo/README.md
demos/multi_channel/face_detection_demo/README.md
demos/multi_channel/human_pose_estimation_demo/README.md
demos/multi_channel/object_detection_demo_yolov3/README.md
demos/object_detection_demo_faster_rcnn/README.md
demos/object_detection_demo_ssd_async/README.md
demos/object_detection_demo_yolov3_async/README.md
demos/pedestrian_tracker_demo/README.md
demos/python_demos/colorization_demo/README.md
demos/python_demos/face_recognition_demo/README.md
demos/security_barrier_camera_demo/README.md
demos/segmentation_demo/README.md
demos/smart_classroom_demo/README.md
demos/super_resolution_demo/README.md
demos/text_detection_demo/README.md

Mostly, just remove `sh` from blocks with help text, since they are not in any formal language. But there are also a few cases where a block was labeled with the wrong language.

demos: fix the languages specified for code blocks in the docs

---

demos/multi_channel/face_detection_demo/main.cpp
demos/multi_channel/human_pose_estimation_demo/main.cpp
demos/multi_channel/object_detection_demo_yolov3/main.cpp

`parseInputFilesArguments` removes any files that don't exist, so it's possible for `numberOfInputs` to be 0. In this case, `prepareDisplayParams` will divide by 0. Don't let that happen.

demos/multi_channel: don't crash if input files don't exist

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

- removed workaround with network reloading (with INT8 it increases the execution time)
- fixed problem for delayed model loading

AC: fix reshape for quantization

---

tools/accuracy_checker/accuracy_checker/adapters/action_recognition.py
tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py

quantization tool is able to add biases to output convolutions in runtime, it leads to temporal outputs renaming

AC: fix outputs

---

tools/downloader/pytorch_to_onnx.py

`__import__` has surprising behavior when you try to import a submodule (e.g. `foo.bar`), where it returns the `foo` package instead of the `foo.bar` module. This prevents non-top-level modules from being used with the `--import-module` option. `importlib.import_module` does not have this problem.

pytorch_to_onnx.py: use importlib instead of __import__

---

models/public/googlenet-v3-pytorch/model.yml
models/public/resnet-18-pytorch/model.yml
models/public/resnet-50-pytorch/model.yml
tools/downloader/pytorch_to_onnx.py

This flag is redundant, as `--import-module=torchvision.models` has the same effect (with the only difference being a slightly less clear error message when the package is missing). Removing it simplifies the code.
As a side effect, this also allows using `--model-param` with torchvision models, although there is currently no reason to do so.

pytorch_to_onnx.py: remove --from-torchvision

---

models/intel/text-detection-0003/description/text-detection-0003.md
models/intel/text-detection-0004/description/text-detection-0004.md

The outputs are listed in the wrong order (IE returns them in alphabetical order). Fix the order and list the names too.
Fixes #880.

text-detection-????: fix output documentation

---

models/intel/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.md

Sadly, it appears that ETH Zürich took this dataset down. The best thing we can do now is to point to the dataset index page.

Replace the link to the Biwi Kinect Head Pose Database

---

models/intel/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.md

Literally hours after I submitted #912, ETHZ removed the page I linked to. Fortunately, it looks like it was just moved to a different location.

Replace the link to the Biwi Kinect Head Pose Database... again

---

tools/accuracy_checker/accuracy_checker/launcher/model_conversion.py
tools/accuracy_checker/tests/test_config_reader.py
tools/accuracy_checker/tests/test_dlsdk_launcher.py

There were two kinds of problems:
* Paths starting with `/` are not absolute on Windows, which broke logic that depended on them being so.
* In a few cases, a Windows-style path was compared against a Unix-style one.

AC: Fix tests on Windows

---

tools/accuracy_checker/accuracy_checker/annotation_converters/squad.py
tools/accuracy_checker/accuracy_checker/annotation_converters/text_classification.py

all numeric values assume to be integer

AC: fix value type for NLP task annotation converters params

---

models/intel/icnet-camvid-ava-tf-0001/description/icnet-camvid-ava-tf-0001.md
models/intel/icnet-camvid-ava-tf-sparse-30-0001/description/icnet-camvid-ava-tf-sparse-30-0001.md
models/intel/icnet-camvid-ava-tf-sparse-60-0001/description/icnet-camvid-tf-ava-sparse-60-0001.md
models/intel/index.md

revert icname back, no need to play with ava-tf or tf-ava

revert icnet name

---

models/public/googlenet-v3/model.yml
models/public/inception-resnet-v2-tf/model.yml
models/public/license-plate-recognition-barrier-0007/model.yml
models/public/mobilenet-ssd/mobilenet-ssd.md
models/public/mobilenet-ssd/model.yml
models/public/mobilenet-v1-0.25-128/model.yml
models/public/mobilenet-v1-0.50-160/model.yml
models/public/mobilenet-v1-0.50-224/model.yml
models/public/mobilenet-v1-1.0-224-tf/model.yml

The unnecessarily precise scale values were previously used for compatibility with the internal benchmarking infrastructure, but due to recent internal changes, they are no longer necessary.

models/public: round the scale values

---

demos/python_demos/instance_segmentation_demo/README.md

This is needed because some of the segmentation models may have inputs/outputs different than OTE segmentation models have, and so they are not compatible with current demo implementation.

Add a note about OTE to instance_segmentation_demo's readme.md

---

tools/accuracy_checker/accuracy_checker/postprocessor/encode_segmentation_mask.py

if not convert, default type is int16, if resize operation will be called, that byte scaling will be applied and we got wrong annotation mask labels

AC: fix encode segm mask

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/detection.py

model from [IntelAI zoo](https://github.com/IntelAI/models/tree/master/benchmarks/object_detection/tensorflow/ssd-resnet34)
has a difference in feature size and layout of outputs in comparision with pytorch implementation

AC: support ssd-resnet34 TF

---

demos/common/monitors/memory_monitor.cpp

I doubt if monitors should be rewritten without `regex` because of gcc 4.8.5.

demos/monitors: trigger unimplemented regex error of gcc 4.8.5 only when MemoryMonitor is used

---

demos/gaze_estimation_demo/include/utils.hpp
demos/interactive_face_detection_demo/detectors.hpp
demos/multi_channel/common/graph.hpp

Somehow I've missed these in #802.

demos: remove remnants of cpu_extension compatibility code

---

demos/CMakeLists.txt

This enables IDEs to show them as part of the project. The code to do it was already there, but it was broken.

demos/CMakeLists.txt: make header files belong to their respective demo

---

tools/accuracy_checker/setup.py

workaround for following problems:
* no prebuilt opencv-python package for ARM
* the distibuted with OV version required specific numpy version which can be higher than default on the board, suggesting to update numpy.
* the attempt to install numpy via setup_tools (default way for setup.py install) fails with compilation problems, so we need to use pip for install it to avoid this problem

AC: install command update platform specific

---

models/public/brain-tumor-segmentation-0001/brain-tumor-segmentation-0001.md
models/public/densenet-121/densenet-121.md
models/public/densenet-161/densenet-161.md
models/public/densenet-169/densenet-169.md
models/public/densenet-201/densenet-201.md
models/public/resnet-101/resnet-101.md
models/public/resnet-152/resnet-152.md
models/public/resnet-50/resnet-50.md

These links point to the parent directory of the file they're in. Fix them so that they point to the intended destination.
Note about `resnet-*`: the link in `resnet-152` originally pointed to the wrong repository. I fixed it and added it to the other ResNet models for consistency.

Fix links with broken syntax in the model documentation

---

models/public/ssd300/model.yml
models/public/ssd300/ssd300.md
models/public/ssd512/model.yml
models/public/ssd512/ssd512.md

I believe that we already fixed this info, but these changes were overwritten.
public SSD are not face detectors.

fix SSD models description

---

demos/python_demos/3d_segmentation_demo/3d_segmentation_demo.py
demos/python_demos/action_recognition/action_recognition.py
demos/python_demos/asl_recognition_demo/asl_recognition_demo.py
demos/python_demos/colorization_demo/colorization_demo.py
demos/python_demos/face_recognition_demo/face_recognition_demo.py
demos/python_demos/handwritten_japanese_recognition_demo/handwritten_japanese_recognition_demo.py
demos/python_demos/human_pose_estimation_3d_demo/human_pose_estimation_3d_demo.py
demos/python_demos/human_pose_estimation_3d_demo/modules/draw.py
demos/python_demos/human_pose_estimation_3d_demo/modules/inference_engine.py
demos/python_demos/human_pose_estimation_3d_demo/modules/input_reader.py
demos/python_demos/human_pose_estimation_3d_demo/modules/one_euro_filter.py
demos/python_demos/human_pose_estimation_3d_demo/modules/parse_poses.py
demos/python_demos/human_pose_estimation_3d_demo/modules/pose.py
demos/python_demos/image_retrieval_demo/image_retrieval_demo.py
demos/python_demos/instance_segmentation_demo/instance_segmentation_demo.py
demos/python_demos/instance_segmentation_demo/instance_segmentation_demo/visualizer.py
demos/python_demos/monodepth_demo/monodepth_demo.py
demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py
demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
demos/python_demos/segmentation_demo/segmentation_demo.py
demos/python_demos/text_spotting_demo/text_spotting_demo.py
demos/python_demos/text_spotting_demo/text_spotting_demo/visualizer.py
demos/smart_classroom_demo/action_event_metrics.py
demos/smart_classroom_demo/create_list.py
tools/accuracy_checker/accuracy_checker/annotation_converters/market1501.py
tools/accuracy_checker/accuracy_checker/annotation_converters/mars.py

It was never really supported in the first place, but now that the OpenVINO toolkit has dropped the Python 2 bindings, it's _definitely_ not supported.

Drop Python 2 support

---

README.md

The `release` branch will now be used to develop 2020.3 while the `develop` branch will be used for 2020.4 (I will bump the version there separately).

Bump the version on the release branch

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/accuracy_checker/utils.py

IE raises error if it got OrderedDict instead of dict as plugin config

AC; support non-ordered yaml reading for device config

---

demos/object_detection_demo_ssd_async/main.cpp

But drop labels support for IR version older than 10.

object_detection_demo_ssd_async: remove deprecated flow

---

tools/downloader/README.md
tools/downloader/converter.py

I must've been careless when adding `--dry-run` and `--add-mo-arg`, and used dashes when all of the other options in the converter and in the downloader used underscores. Change them to use underscores too and provide compatibility aliases so old usages still work.
I'm sending this patch to `release` because, even though it's not too important by itself. The reason is that model quantizer (#1068) also has a dry run option, which I'd rather make use underscores from the start, and it would be nice if it was consistent between the quantizer and the converter.

Model converter: use a consistent naming convention for options

---

models/public/alexnet/model.yml
models/public/googlenet-v1/model.yml
models/public/googlenet-v3-pytorch/model.yml
models/public/mobilenet-v1-1.0-224/model.yml
models/public/mobilenet-v2-pytorch/model.yml
models/public/mobilenet-v2/model.yml
models/public/resnet-101/model.yml
models/public/resnet-152/model.yml
models/public/resnet-18-pytorch/model.yml
models/public/resnet-50-pytorch/model.yml
models/public/resnet-50/model.yml
models/public/squeezenet1.1-caffe2/model.yml
models/public/squeezenet1.1/model.yml
models/public/vgg16/model.yml
tools/downloader/README.md
tools/downloader/common.py
tools/downloader/converter.py
tools/downloader/quantizer.py

This script is akin to the model converter, but instead of converting, it quantizes full-precision models to INT8 using POT with a simple configuration. For now, only certain models (for which it's known that the resulting model has good accuracy) are marked as quantizable.
(This is a draft PR for now, because I'll be adding documentation later.)

Add a model quantizer script

---

ci/update-requirements.py

pip-tools has recently changed the output format by adding the source file paths to the comments. This causes problems for us, because some of our source files are from the OpenVINO toolkit directory, whose path changes depending on the version and the install directory. Using that path as-is would mean leaking local file system paths, as well as meaningless diffs when upgrading to newer OpenVINO versions.
Fortunately, we already use a script, which means we can just postprocess the unwanted parts away.
I also used this postprocessing to add a comment directing developers to the update script.

ci/update-requirements.py: enable usage with pip-tools >=4.5.0

---

tools/accuracy_checker/configs/alexnet.yml
tools/accuracy_checker/configs/asl-recognition-0004.yml
tools/accuracy_checker/configs/face-detection-0100.yml
tools/accuracy_checker/configs/face-detection-0102.yml
tools/accuracy_checker/configs/face-detection-0104.yml
tools/accuracy_checker/configs/face-detection-0105.yml
tools/accuracy_checker/configs/face-detection-0106.yml
tools/accuracy_checker/configs/face-recognition-resnet100-arcface.yml
tools/accuracy_checker/configs/googlenet-v1.yml
tools/accuracy_checker/configs/googlenet-v3-pytorch.yml
tools/accuracy_checker/configs/handwritten-japanese-recognition-0001.yml
tools/accuracy_checker/configs/instance-segmentation-security-1025.yml
tools/accuracy_checker/configs/mobilenet-v1-1.0-224.yml
tools/accuracy_checker/configs/mobilenet-v2-pytorch.yml
tools/accuracy_checker/configs/mobilenet-v2.yml
tools/accuracy_checker/configs/person-attributes-recognition-crossroad-0230.yml
tools/accuracy_checker/configs/person-detection-asl-0001.yml
tools/accuracy_checker/configs/person-reidentification-retail-0248.yml
tools/accuracy_checker/configs/person-reidentification-retail-0249.yml
tools/accuracy_checker/configs/person-reidentification-retail-0300.yml
tools/accuracy_checker/configs/resnet-101.yml
tools/accuracy_checker/configs/resnet-152.yml
tools/accuracy_checker/configs/resnet-18-pytorch.yml
tools/accuracy_checker/configs/resnet-50-pytorch.yml
tools/accuracy_checker/configs/resnet-50.yml
tools/accuracy_checker/configs/squeezenet1.1-caffe2.yml
tools/accuracy_checker/configs/squeezenet1.1.yml
tools/accuracy_checker/configs/vgg16.yml

AC configs have been updated according to information from info_dumper. Also launchers for FP32-INT8 and FP16-INT8 have been added for models with quantizable: yes in model.yml

Updates in AC configs

---

tools/accuracy_checker/accuracy_checker/config/config_reader.py
tools/accuracy_checker/accuracy_checker/preprocessor/resize.py
tools/accuracy_checker/tests/test_preprocessor.py

fixed wrong postprocessing in mask rcnn adapter, which lead to 0% metric if auto_resize used as preprocessing

AC: add resize meta for autoresize

---

tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py

Calculation of coco_orig_metric has been fixed.   AP has been reduced to 66.6% from 69%. After fix AP for mentioned model is 68.37%. 
In this PR usage of original and generated annotation file has been combined by condition. If there is annotation file, it is used when calculating the metric. If annotation file is missing or there is subsample_size option, use generated annotation file.

AC: Fix coco_orig_metric

---

tools/downloader/common.py
tools/downloader/converter.py
tools/downloader/downloader.py
tools/downloader/quantizer.py

The main reason I'm doing this is to prepare for implementing parallel downloading in the downloader, but as a side benefit, this also enforces consistent formatting in the converter and quantizer.
The info dumper only has machine-readable output, so it has no use for these mechanisms and is thus unaffected.
See the commit messages for more details.

Unify the reporting mechanisms used by the model tools

---

tools/downloader/downloader.py

It is possible for `duration` to be 0 if a chunk has already been received completely by the time we got to the chunk loop. In this case, we can't calculate the speed, but we can still output all the other progress information, so do so.
This is particularly important for very short files which entirely fit in one chunk, since previously there wouldn't be any progress information for them at all.
I also removed a couple of unnecessary casts in the affected code.

Model downloader: print progress even if zero time passed

---

models/public/license-plate-recognition-barrier-0007/license-plate-recognition-barrier-0007.md

The "Performance Benchmarks" link on the OpenVINO toolkit home page now links to <https://docs.openvinotoolkit.org/latest/_docs_performance_benchmarks.html>, but that page doesn't mention this model at all, so it wouldn't make sense to link to it here.

Remove broken link

---

tools/downloader/pytorch_to_onnx.py

PyTorch might change the default opset in a future release to one that is unsupported by Model Optimizer. To prevent surprises, it's better to set the opset explicitly.

pytorch_to_onnx.py: explicitly specify the ONNX opset

---

tools/downloader/README.md
tools/downloader/common.py
tools/downloader/converter.py
tools/downloader/downloader.py

This adds a `-j` option to the model downloader, which will tell it to download multiple models at the same time, similarly to the model converter. Also similarly to the converter, the output from the concurrent downloading jobs will be serialized, so that it'll be indistinguishable from downloading all models sequentially. This, I will admit, is not ideal, but it's better than just having the jobs chaotically writer over each other's output. Ideally, we should have multiple progress bars updating at the same time, but that seems quite tricky to implement.
See the individual commits for more details (and easier-to-review diffs :-) ).

Model downloader: implement parallel downloading

---

tools/downloader/pytorch_to_onnx.py

PyTorch 1.5 started assigning names to ONNX nodes, which causes Model Optimizer to use those names as IR output names, rather than the ONNX output names. For us, this is backwards-incompatible (our existing `--output` options stop working) and just plain inconvenient (the PyTorch-generated names are much less descriptive than our hand-picked output names).
Work around it by deleting the ONNX node names after conversion (effectively, restoring the PyTorch 1.4 behavior).

pytorch_to_onnx.py: work around an incompatibility with PyTorch 1.5

---

tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/colorization_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/sequential_action_recognition_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

migration on usage `Blob`, `TensorDesc` and `input_info` with preserving backward compatibilities
relates with  https://github.com/openvinotoolkit/openvino/pull/637
changes tested on all pipelined models, reshape and set precision use cases - no problems are detected

AC: migrate on new IE Python API

---

tools/accuracy_checker/accuracy_checker/adapters/classification.py
tools/accuracy_checker/configs/hbonet-0.25.yml
tools/accuracy_checker/configs/hbonet-0.5.yml
tools/accuracy_checker/configs/hbonet-1.0.yml

in some cases, MO create some artefacts layers to output (split parts), it can be useful to be able manually set output layer name

AC: support explicit output layer name in classification adapter

---

models/intel/person-reidentification-retail-0031/model.yml
models/intel/person-reidentification-retail-0249/model.yml
models/intel/person-reidentification-retail-0300/model.yml

They were deleted in #1167, but they're still used in demo tests. We can't use the new models yet, because their files haven't been published yet.
Restore them until the new models' files are published.

Temporarily restore the old ReID models

---

tools/accuracy_checker/accuracy_checker/adapters/segmentation.py

resize does not work with boolean values

AC: fix single class semantic segmentation adapter

---

tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher.py

When trying to launch a PyTorch model with Accuracy Checker in a non-CUDA environment, there is an error can happen:
```
2020-06-08 17:08:17,929 INFO: Checking the model
2020-06-08 17:08:18,191 ERROR: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Traceback (most recent call last):
...
"/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py", line 198, in create_launcher
return Launcher.provide(config_framework, launcher_config, delayed_model_loading=delayed_model_loading)
File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/ …
```

AC: Add data mapping to CPU for PyTorch launcher when no CUDA available

---

demos/gaze_estimation_demo/include/face_inference_results.hpp

This works around a static analysis warning.

gaze_estimation_demo: zero-initialize FaceInferenceResults members

---

demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py

The bug was fixed, so we don't need this anymore.
This reverts commit cad9bd1fbe781299173eddefc40fa659a32789e7.

Revert "object_detection_demo_yolov3_async: Work around a bug in the GPU plugin"

---

models/public/resnet-50-tf/model.yml
models/public/resnet-50-tf/resnet-50-tf.md

The `official/r1` directory was removed from `master` a few days ago. Link to the most recent tag instead.

resnet-50-tf: fix the link to the repository

---

demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py

The IOU filtering process aims to remove duplicate predictions of the same **objects** and ends up choosing the box with highest probablity. To validate this Pull Request, kindly run prediction on this 
[sample image](https://unsplash.com/photos/Tzz4XrrdPUE) at the confidence threshold of 0.1. 
Using the earlier code, you will notice that though the person was detected, but on comparing its IOU with cycle, led to ignoring it in the final results. This is because it makes no sense to compare a cycle with a man or any different object.

Corrected filtering on basis of IoU

---

tools/downloader/common.py

Requests enables compression by default. However, it's not a good idea to do that when making a range request, because if the server decides to use compression, then it'll return a range from the _compressed_ file, which is useless (you can't decompress a chunk from the middle of a compressed file).
Because of that, I suspect that most servers already either disable compression or don't honor range requests, but just in case, disable it on our side too.

downloader: disable compression when resuming a download

---

ci/requirements-ac-test.txt
ci/requirements-ac.txt
ci/requirements-conversion.txt
ci/requirements-demos.txt
ci/requirements-downloader.txt
tools/downloader/requirements-caffe2.in
tools/downloader/requirements-pytorch.in

Unfortunately, pytorch/vision#2132 prevents us from moving to PyTorch 1.5, so I had to cap it at 1.4.

Bump dependency versions

---

models/public/deeplabv3/accuracy-check.yml
models/public/deeplabv3/deeplabv3.md
models/public/deeplabv3/model.yml

The Model Optimizer issue that prevented us from doing this has been fixed at some point, so there's nothing preventing us from doing it.
This makes this model's input consistent with most others, and makes it so that people can use it with our segmentation demo without modifying the demo (or losing accuracy).

Enable input channel reversal for deeplabv3

---

models/intel/resnet18-xnor-binary-onnx-0001/accuracy-check.yml
models/intel/resnet50-binary-0001/accuracy-check.yml
models/intel/unet-camvid-onnx-0001/accuracy-check.yml

There's no functional difference, but this is more correct in terms of semantics: the `pillow_imread` reader produces RGB images, which we convert to BGR for our networks.

Replace bgr_to_rgb with rgb_to_bgr in several AC configs

---

.editorconfig

* Remove junk.
* Remove the end_of_line setting, which is useless, since Git transforms all line endings to the LF format upon commit anyway. (And since it transforms them to the native format upon checkout, all files end up inconsistent with `.editorconfig` on Windows if this setting is used.)

Clean up .editorconfig

---

tools/accuracy_checker/accuracy_checker/adapters/action_recognition.py
tools/accuracy_checker/accuracy_checker/adapters/adapter.py
tools/accuracy_checker/accuracy_checker/adapters/attribute_classification.py
tools/accuracy_checker/accuracy_checker/adapters/attributes_recognition.py
tools/accuracy_checker/accuracy_checker/adapters/centernet.py
tools/accuracy_checker/accuracy_checker/adapters/classification.py
tools/accuracy_checker/accuracy_checker/adapters/detection.py
tools/accuracy_checker/accuracy_checker/adapters/detection_person_vehicle.py
tools/accuracy_checker/accuracy_checker/adapters/hit_ratio.py
tools/accuracy_checker/accuracy_checker/adapters/image_inpainting.py
tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
tools/accuracy_checker/accuracy_checker/adapters/mask_rcnn.py
tools/accuracy_checker/accuracy_checker/adapters/mask_rcnn_with_text.py
tools/accuracy_checker/accuracy_checker/adapters/mixed_adapter.py
tools/accuracy_checker/accuracy_checker/adapters/mono_depth.py
tools/accuracy_checker/accuracy_checker/adapters/nlp.py
tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py
tools/accuracy_checker/accuracy_checker/adapters/pose_estimation_3d.py
tools/accuracy_checker/accuracy_checker/adapters/regression.py
tools/accuracy_checker/accuracy_checker/adapters/reidentification.py
tools/accuracy_checker/accuracy_checker/adapters/retinaface.py
tools/accuracy_checker/accuracy_checker/adapters/segmentation.py
tools/accuracy_checker/accuracy_checker/adapters/ssd.py
tools/accuracy_checker/accuracy_checker/adapters/style_transfer.py
tools/accuracy_checker/accuracy_checker/adapters/text_detection.py
tools/accuracy_checker/accuracy_checker/adapters/text_recognition.py
tools/accuracy_checker/accuracy_checker/adapters/yolo.py
tools/accuracy_checker/tests/test_adapters.py

with enabling preprocessing throw ie, some preprocessing metadata missed.
adapters which use such info are updated to work without it (by default scaling coefficients calculated like for case with single resize to input resolution - ie resize behaviour. if coeffs provided, then we use them (they can be different from default, for example, if we use aspect ratio preserving resize + padding to input size)

AC: allow to process result without resize meta

---

demos/classification_demo/main.cpp
demos/common/include/samples/common.hpp
demos/gaze_estimation_demo/include/ie_wrapper.hpp
demos/gaze_estimation_demo/include/utils.hpp
demos/gaze_estimation_demo/main.cpp
demos/interactive_face_detection_demo/detectors.cpp
demos/interactive_face_detection_demo/detectors.hpp
demos/interactive_face_detection_demo/main.cpp
demos/multi_channel/common/graph.hpp
demos/pedestrian_tracker_demo/src/utils.cpp
demos/smart_classroom_demo/main.cpp

Recommendation from IE core team is to use `inference_engine.hpp` which contains all other common IE headers (not including plugin specific headers with their configuration options). This approach is more future proof in terms if we shuffle headers / remove deprecated classes and headers as well.

Updated ie headers

---

demos/README.md
demos/build_demos_msvc.bat

This seems to be a holdover from when the original demos were extracted
from the Inference Engine repository. They're not IE demos anymore, they're
OMZ demos.

Stop calling the demos "Inference Engine demos"

---

tools/downloader/downloader.py

The purpose of deleting it is to make sure the user doesn't end up with an incomplete or unverified file. However, deleting the whole directory is overkill, and can lead to nasty surprises if the user sets an existing directory as the output directory.
Instead, just delete the file we were trying to download. This means we can leave the user with an incomplete _set_ of files, but that doesn't seem like a significant issue.

downloader: don't delete the whole output directory if the download fails

---

demos/build_demos_msvc.bat

This simplifies the script and makes it easier to add support for new versions of Visual Studio. I also trust CMake more with this than I do our home-grown logic; CMake is more actively maintained, so they're more likely to handle any obscure cases.
I also took the opportunity to improve some of the error messages.

build_demos_msvc.bat: let CMake find MSBuild for us

---

tools/accuracy_checker/accuracy_checker/adapters/retinaface.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

some openvino plugins support both NCHW and NHWC execution modes. Depends from layout, output data stored in different order and can require additional postprocessing (transpsition, reshape, e. t. c.). Usually we make decision based on input shape, however it is not always matched with layout (at  least in OV), so I suggest to provide additional info about output layout.

AC: provide output layout to the adapter

---

tools/downloader/common.py
tools/downloader/downloader.py

This has a few advantages over what we're doing now (postprocessing all models at the end):
* Postprocessing is parallelized along with downloading (we could've parallelized the postprocessing loop explicitly, but this way is much simpler).
* If the downloader is interrupted, models that have already been processed will be fully ready to use.
* The code structure is simpler, with no parallel loops.

downloader: postprocess each model immediately after downloading it

---

tools/accuracy_checker/accuracy_checker/launcher/launcher.py
tools/accuracy_checker/requirements.in
tools/accuracy_checker/setup.py
tools/accuracy_checker/tests/test_dlsdk_launcher.py

AC: fix warnings

---

models/public/resnet-50-tf/model.yml
models/public/resnet-50-tf/resnet-50-tf.md

I don't know what's going on in there, but the new link is now broken and the old one is fine.
This reverts commit 57b7ac1664f6d359717b228f956c9dfd4523b48c.

Revert "resnet-50-tf: fix broken link on model repo (#1406)"

---

tools/accuracy_checker/accuracy_checker/annotation_converters/action_recognition.py

optical flow is aggregation of 2 frames (current and previous), so per frame converted dataset contains on 2 frame less then original video.

AC: fix kinetics conversion for flow

---

tools/accuracy_checker/accuracy_checker/config/config_reader.py

in quantization flow, the model path can be ommited, however in some case required approach to set model specific attributes (vocab file for example.), changed config merge to handle this case

AC: update config merge

---

demos/python_demos/monodepth_demo/monodepth_demo.py
demos/python_demos/segmentation_demo/segmentation_demo.py

The demo dir can be non-writable by the current user (in the common case where the demo is installed systemwide as part of OpenVINO toolkit). Use the current directory instead.

demos: don't write files into the demo directory

---

tools/accuracy_checker/accuracy_checker/metrics/README.md
tools/accuracy_checker/accuracy_checker/metrics/__init__.py
tools/accuracy_checker/accuracy_checker/metrics/speech_recognition.py

The existing implementation of "wer" metric computed CER metric instead, and incorrectly averaged it over samples.  The existing greedy_wer metric was the correct WER metric, consistent with the other implementations (for example, Mozilla DeepSpeech).

Fix WER metric, rename greedy_wer to wer, add CER metric for speech recognition

---

models/intel/person-detection-retail-0002/description/person-detection-retail-0002.md
models/public/brain-tumor-segmentation-0001/brain-tumor-segmentation-0001.md
models/public/retinaface-resnet50/retinaface-resnet50.md
models/public/ssd-resnet34-1200-onnx/ssd-resnet34-1200-onnx.md
models/public/yolo-v2-tiny-tf/yolo-v2-tiny-tf.md

The title should always be the same as the name of the model.

Fix small errors in model documentation page titles

---

tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
tools/accuracy_checker/tests/test_segmentation_representation.py

previous implementation store all poligons parts together. it is impossible to get polygons belong to specific object

 AC: fix per object polygons for instance segment

---

tools/downloader/README.md
tools/downloader/common.py

We used to have models with precisions INT1 and INT8. But we don't anymore. Remove those precisions from the codebase to avoid confusion.

downloader: remove prefix-less integer precisions

---

demos/security_barrier_camera_demo/net_wrappers.hpp

That avoids a mismatch when the model wrapper have an implicit assumption which dimension is of non 1 size.
Every LPR model output shape is [1, 88, 1, 1] now.
But the implemented approach relaxes the requirement to have a specific order of dimensions.

security_barrier_camera: check every lpr output dimension

---

tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
tools/accuracy_checker/tests/test_segmentation_representation.py

1. fix for labels stored in numpy array
2. fix for annotation decoding mask (original format stored in raw_mask is not applicable for decoding)

AC: fix instance segmentation to polygon dumping

---

ci/get-jobs-for-changes.py

Occasionally we merge a PR that deletes a model and then demo tests start failing, because one of the demos depended on it. This change is a step towards preventing that from happening.
Right now, there isn't anything actually connected to this "models_lst" identifier. I plan to add a check to the demo job that just runs the info dumper on every models.lst file in the repository, and to trigger that check when the "models_lst" job is requested.
I could just set it to run the full demo job when a model is deleted, but that seems like an overkill; the demo tests take a while, and a model can only be used in tests if it's listed in models.lst, thus checking models.lst is sufficient.

get-jobs-for-changes.py: request a models.lst check when a model is deleted

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/classification.py
tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
tools/accuracy_checker/accuracy_checker/annotation_converters/criteo_kaggle_dac.py
tools/accuracy_checker/accuracy_checker/data_readers/README.md
tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/accuracy_checker/metrics/README.md
tools/accuracy_checker/accuracy_checker/metrics/classification.py

Work around too slow accuracy tests with DLRM models on Criteo datasets.
Key problem: prepare batch data for model inputs from record-oriented annotations consumes much more time than batch inference.
Solution: make processing batch-oriented 
Changes: 
1. Add "block" parameter to criteo_kaggle_dac converter to produce batch-oriented annotations
2. Add "block" parameter to numpy_reader to allow reading full batch input
3. Modification of DLSDKLauncher._data_to_blob() to correctly handle 3D data to 2D input layout
4. Add "block" parameter to ClassificationAdapter to allow whole batch output be transformed into single prediction object
5. Add "match" parameter to "accuracy" metric to allow sklearn.metric.accuracy_score in the context of AC "accuracy" metric 
Performance benefit from these …

Mzuevx ac criteo block

---

models/public/deeplabv3/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/postprocessor/extend_segmentation_mask.py
tools/accuracy_checker/accuracy_checker/preprocessor/README.md
tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py

default deeplab v3 config written for specific image size in the dataset (if we provide image larger than 513x513, AC failed on input filling case, because padding will not applied), generalized it for case if images larger than default (can be useful in visualization case) and added deprocessing padded prediction mask for single image processing mode

AC: support resize in padding and deprocessing padded mask

---

models/public/ctpn/model.yml
models/public/densenet-121-tf/model.yml
models/public/densenet-161-tf/model.yml
models/public/densenet-169-tf/model.yml

--keep_shape_ops key enabled by default in MO and the option is gone. Updated model.yml do not use it

Public models: remove deprecated keep_shape_ops option

---

tools/downloader/downloader.py

We need to use the number of bytes downloaded by the _current_ call to process_download, not the total number downloaded so far.

downloader: show speed correctly when resuming a download

---

tools/accuracy_checker/accuracy_checker/metrics/im2latex_images_match.py

License header in the im2latex image metric is updated because of partial use of the code from https://github.com/harvardnlp/im2markup

upd license header

---

models/public/colorization-v2-norebal/model.yml
models/public/colorization-v2/model.yml

original caffe implementation colorization were moved to separarated branch, we already update docs for it, however model files also moved

update downloading url for colorization models

---

demos/README.md

Only multi_channel demos need TBB vars and they don't document the
possibility of being built with TBB. Moreover, I couldn't come up
with easy-to-understand formulation describing TBB var for root demos
readme. So, this var is not included in the patch.

demos: clarify build procedure on *Config.cmake

---

tools/accuracy_checker/accuracy_checker/launcher/dummy_launcher.py
tools/accuracy_checker/accuracy_checker/launcher/loaders/json_loader.py

the idea in opportunity provide file with list of identifiers used in inference if it is not fully matched with annotation (e.g. inferrend whole dataset while in validation used only subset)

AC: support explicit identifiers list specification in dummy launcher

---

demos/super_resolution_demo/main.cpp

Don't fix input names. This can be handy for srgan model, which is
not added, but has AC support.
Resize input image instead of skipping it.
Set batchSize equal to inputImages.size().
While I was sorting out all that problems I replaced
setBatchSize() with reshape(). reshape() is more stable usually so I
kept this change.

super_resolution: update

---

demos/python_demos/colorization_demo/colorization_demo.py
demos/python_demos/image_inpainting_demo/inpainting_gui.py
demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py
demos/python_demos/speech_recognition_demo/utils/audio_features.py

This gets rid of all camelCase variable names other than those in the monitors module. Which I think we should fix too, but that's a more involved change, so I'm putting it off.

Fix naming convention violations in Python demos

---

models/intel/vehicle-detection-0203/accuracy-check.yml
models/intel/vehicle-detection-0204/accuracy-check.yml
models/intel/vehicle-detection-0205/accuracy-check.yml
models/public/googlenet-v3-pytorch/accuracy-check.yml
models/public/googlenet-v3-pytorch/googlenet-v3-pytorch.md
models/public/mobilenet-v2-pytorch/accuracy-check.yml

In case of the deleted comments, yamllint was complaining about indentation, and while I could've fixed it, we already have reference metric values in the documentation, so I don't think we need to duplicate them in the config.
In the case of `googlenet-v3-pytorch`, the values in the config were different from the ones in the documentation. I chose to replace the values in the doc with the ones from the config, because:
1. The torchvision documentation lists the same values;
2. I ran AC on this model, and the results are closer to these values than the ones that are currently listed in the doc.

Fix issues found by yamllint

---

models/public/faceboxes-pytorch/accuracy-check.yml
models/public/faceboxes-pytorch/faceboxes-pytorch.md
models/public/faceboxes-pytorch/model.yml

I don't see any advantage in using numeric names, and it has a disadvantage: PyTorch fails to export the model to ONNX if opset is set to version 11 (presumably numeric names are disallowed). So replace them with descriptive names.
The demo doesn't seem to care what the names are, so I'm not modifying it.

faceboxes-pytorch: use human-friendly names for outputs

---

models/public/midasnet/model.yml
tools/downloader/pytorch_to_onnx.py

This has a few beneficial effects:
* it removes conversion warnings that used to be printed for several models about how certain layers don't work the same way in ONNX until opset 11;
* it allows us to remove one of the regex replacements in the midasnet model, which, I believe, was originally added to work around ONNX limitations;
* it allows us to add future models which require a newer opset.
I have run an accuracy check on all affected models (on CPU), and didn't see any degradation. midasnet actually improved, going from an RMSE of 0.08 to 0.07.

Raise the ONNX opset version used for converting PyTorch models to 11

---

tools/downloader/common.py
tools/downloader/quantizer.py

This used to not be necessary, because the Accuracy Checker configs used to refer to this file, so everything worked automatically. However, since !1129 the configs no longer reference this file, which broke the quantizer.
Set the `DEFINITIONS_FILE` environment variable explicitly to fix it.

Model Quantizer: supply the dataset definitions file path to POT

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

compaled nets have constant input info, setting precision for this case leads to errors

AC: fix precision setting for compiled networks

---

ci/update-requirements.py
demos/CMakeLists.txt
tools/accuracy_checker/requirements-test.in
tools/accuracy_checker/setup.py
tools/downloader/README.md
tools/downloader/requirements-caffe2.in
tools/downloader/requirements-pytorch.in

Python 3.5 is EOL and OpenVINO doesn't support it anymore, so I don't think we need to support it either.
This removes the need to cap the PyTorch version, so don't do that anymore.
We also technically don't need the workaround with the forced `atomicwrites` requirement in `requirements-test.in` anymore, since now it should be possible to regenerate the `requirements-*.txt` files on Windows. I don't want to only be able to do it to Windows, though, so I'd rather keep the workaround.

Bump minimal Python version to 3.6

---

tools/downloader/requirements-caffe2.in
tools/downloader/requirements-pytorch.in

I got a bit overzealous when I was removing the workarounds in 5cc0a7abae7d2f20c177025b6944d3de1c1bb231.

tools/downloader: restore the PyTorch dependencies

---

demos/gaze_estimation_demo/include/eye_state_estimator.hpp
demos/gaze_estimation_demo/include/gaze_estimator.hpp
demos/gaze_estimation_demo/include/head_pose_estimator.hpp
demos/gaze_estimation_demo/include/landmarks_estimator.hpp
demos/human_pose_estimation_demo/src/human_pose_estimator.cpp
demos/multi_channel/common/input.cpp
demos/multi_channel/human_pose_estimation_demo/postprocess.cpp
demos/pedestrian_tracker_demo/include/descriptor.hpp
demos/smart_classroom_demo/main.cpp

This is a) a good thing to do, and b) fixes a failure to build on macOS, because Clang has `-Winconsistent-missing-override` as part of `-Wall`, and so, thanks to `-Werror`, fails to compile `demos/multi_channel/common/input.cpp`.
I'd like to add `-Wsuggest-override` to compiler options, but we still have to support CentOS 7, and the version of GCC in there doesn't have it.

Add missing override qualifiers

---

models/public/mobilenet-v2-pytorch/mobilenet-v2-pytorch.md
models/public/mobilenet-v2-pytorch/model.yml

It's the exact same topology, and, although the weights are different, it has nearly the same accuracy metrics. However, its weights are hosted on PyTorch's website rather than the author's personal Google Drive, so I think they're less likely to vanish in the future.

mobilenet-v2-pytorch: switch to the torchvision implementation

---

tools/downloader/pytorch_to_onnx.py

Since OpenVINO 2021.1, MO prefers output names to node names, so we don't need the workaround anymore.

Remove the workaround introduced in 53dc8cc3

---

tools/downloader/tests/representative-models.lst

`mobilenet-v2-pytorch` can no longer be used to test external module support, because we've recently replaced it with the equivalent torchvision model. However, it _can_ be used to test torchvision support, and it's a better representative for that than `resnet-50-tf`, due to being much smaller.
Its replacement will be `faceboxes-pytorch`, because it's very small and yet covers external modules, Google Drive downloads and even custom model parameters.

downloader: update the list of representative models

---

models/public/hrnet-v2-c1-segmentation/model.py
models/public/hrnet-v2-c1-segmentation/model.yml
tools/downloader/converter.py
tools/downloader/pytorch_to_onnx.py

Put all the code needed to create the model into a source file, instead of splitting it into little regex patches and model arguments. This makes model configuration more readable.
This approach should also be helpful for any future models which cannot be easily created purely by supplying simple arguments to the constructor.

hrnet-v2-c1-segmentation: use a custom model creation module instead of patches

---

tools/downloader/pytorch_to_onnx.py

1. Mark them as required, because they are; the script won't work without them.
2. Describe the values correctly in the description.

pytorch_to_onnx.py: fix the definitions of --input-names and --output-names

---

models/public/resnet-50-pytorch/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/annotation_converters/inpainting.py
tools/accuracy_checker/accuracy_checker/annotation_converters/style_transfer.py

the pipeline expects that in directory stored only images, however in some case this directory can contains other files (e.g. annotation file used in another task), so usage iterdir in this case is unsafe. Added check file extension

AC: correct image files search in inpainting and style transfer case

---

demos/common/src/images_capture.cpp

Original implementation returned incorrect error message in case of invalid device name, also status of cap.open() was not checked.

VideoCapWrapper refactoring

---

tools/accuracy_checker/accuracy_checker/__init__.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/asr_encoder_decoder_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/colorization_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/mtcnn_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/sequential_action_recognition_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/text_spotting_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
tools/accuracy_checker/setup.py

AC pipeline is always calculate metrics however sometimes they should be not used. Generally it is low-time-cost for metrics calculation, but with growth of the number supported metrics., it is not always true.
Proposed opportunity to turn off metrics calculation in quantization flow.

AC: metrics ignoring for quantization POC

---

demos/CMakeLists.txt

Having `-Werror` on by default means that the build can get broken if the code is built with a version of the compiler that we didn't test with. This isn't just theoretical - it has already happened (see 66aa1d1a and 948b4d8f).
`-Werror` is useful, but for developers rather than users. I plan to add it as an extra option in our CI, so that we can benefit from it ourselves without risking breaking the build for our users.
Also, remove the Windows equivalent, which is not enabled by default, but hidden behind an undocumented and unnecessary option. `-DCMAKE_CXX_ARGS=/WX` accomplishes the same effect as `TREAT_WARNING_AS_ERROR`, and requires no additional code.

demos: Remove mandatory -Werror

---

demos/mask_rcnn_demo/main.cpp

These aren't normally supposed to occur, but there's a currently a bug in OpenVINO master where the GPU plugin produces invalid boxes when inferring with `mask_rcnn_resnet101_atrous_coco`. This change works around that (and, in general, makes the demo more resilient to misbehaving networks).

mask_rcnn_demo: skip zero-size boxes

---

demos/python_demos/action_recognition/README.md
demos/python_demos/action_recognition/action_recognition.py
demos/python_demos/action_recognition/action_recognition_demo/steps.py

There was no handling of situation when the demo fails to open the input video (one or many). Add the handler of this error to prevent the demo further running.

Add the handler of open video error in action_recognition demo

---

models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md

update model accuracy ref value for map@person metric. originally reported value can't be reproduced

person-vehicle-bike-detection-crossroad-0078

---

tools/accuracy_checker/accuracy_checker/postprocessor/README.md
tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
tools/accuracy_checker/accuracy_checker/postprocessor/crop_ground_truth_image.py

Corner crop of ground truth image can be used for predictable crop of reference images  in accuracy checking pipelines of super resolution models

Corner crop of ground truth image

---

ci/check-release-readiness.py

Otherwise, you can get multiple identical messages if there are several TODO comments, which looks silly.

ci/check-release-readiness.py: print the line number when complaining about TODO comments

---

tools/downloader/downloader.py

Providing `model_file` and `destination` parameters directly instead of using Tuple in `try_retrieve_from_cache()`.

Removed unnecessary tuple

---

models/public/googlenet-v1-tf/model.yml
models/public/googlenet-v2-tf/model.yml
models/public/googlenet-v4-tf/model.yml

This removes some warnings during conversion and will hopefully prevent the pre-convert script from failing with future versions of TensorFlow.

googlenet-v?-tf: fix deprecated API usage in tf_slim

---

ci/update-requirements.py
tools/downloader/README.md
tools/downloader/requirements-tensorflow.in

There are two reasons why such a file is needed:
* The EfficientDet models are only convertible with TF 2.3+, while Model Optimizer requires 1.15+. This, if the user just uses the requirements from Model Optimizer, they can install an incompatible version of TF.
* TensorFlow is incompatible with h5py 3.x, but it doesn't say so in its requirements. If the user just uses the requirements from MO, they may end up installing an incompatible version of h5py, which will break the conversion of YOLO models. This should be fixed in TensorFlow 2.4, but it has not yet been released. Meanwhile, we can add a workaround via this file.

downloader: add a separate requirements file for TensorFlow model conversion

---

tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
tools/accuracy_checker/accuracy_checker/config/config_validator.py
tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
tools/accuracy_checker/accuracy_checker/launcher/launcher.py
tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/tf_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher_readme.md
tools/accuracy_checker/accuracy_checker/postprocessor/README.md
tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
tools/accuracy_checker/accuracy_checker/postprocessor/super_resolution_image_recovery.py

it is difficult to quantize colorization models due to composite config struture and metrics based on inference classification model.
Now standard image processing metrics (PSNR, SSIM, MAE can be calculated on colorization models)

AC: enable non-inferenece based metrics for colorization

---

tools/accuracy_checker/requirements-core.in
tools/accuracy_checker/requirements.in

increase minimal numpy version like in common OV requirements, remove kenlm as obligated requirement due to issues in Windows install

AC: requirements update

---

licensing/third-party-programs.txt

This file lists TensorFlow, which isn't redistributed by OMZ yet, but #1779 adds a piece of it, so I'm adding it to the TPP file pre-emptively.

Add a third-party-programs.txt file following Intel guidelines

---

.flake8
ci/documentation_updater/documentation_updater.py
demos/python_demos/bert_question_answering_demo/bert_question_answering_demo.py
demos/python_demos/common/html_reader.py

Fix all existing instances of these warnings, all of which are invalid escape sequences.

flake8: enable the pycodestyle deprecation warnings

---

demos/python_demos/common/models/model.py
demos/python_demos/object_detection_demo/object_detection_demo.py

Using `pathlib` results in more compact and correct code compared to `os.path` (or just plain string manipulation), so I think it's about time we migrated the demos to it.
`object_detection_demo` is as good a place to start as any, and by updating `common/models` I create an incentive for future demos to use `pathlib` as well. :)

Switch object_detection_demo and common/models to pathlib

---

demos/CMakeLists.txt
demos/python_demos/speech_recognition_demo/ctcdecode-numpy/CMakeLists.txt

* Use the modern CMake commands for adding compiler options.
* Remove redundant options:
* `/EHsc` is supplied by default;
* the various `-W` options are included in `-Wall`;
* `-std=c++11` isn't needed, because we now require a version of CMake that supports `CMAKE_CXX_STANDARD`.
* `/LARGEADDRESSAWARE` only makes sense on 32-bit Windows, which is not supported.
* Distinguish between Windows-specific and MSVC-specific options.
* Enable `-Wall` for Clang and not just for GCC.

demos: clean up the compiler options

---

demos/common/models/include/models/detection_model_ssd.h
demos/common/models/include/models/segmentation_model.h
demos/common/pipelines/src/async_pipeline.cpp
demos/interactive_face_detection_demo/visualizer.cpp
demos/interactive_face_detection_demo/visualizer.hpp

* inconsistent override qualifiers;
* unnecessary std::move;
* unused class member.

demos: fix warnings found with Clang

---

demos/tests/run_tests.py

This makes it more clear that we're running the demos with a modified environment, and ensures we're not modifying the environment of any non-demo child process.

run_tests.py: explicitly pass the modified environment to demos

---

.yamllint

It can be useful to have more than one space after a colon in order to align map values (and this is heavily used in existing configs), so set `max-spaces-after` to -1 to disable that check.

Enable a few more yamllint checks

---

ci/requirements-demos.txt

See https://github.com/numpy/numpy/issues/16744. Hopefully, this bug will be fixed in Windows by the time we bump the requirements next time, so we won't need to permanently pin the NumPy version.

ci/requirements-demos.txt: downgrade NumPy to work around a Windows bug

---

demos/common/models/src/detection_model_ssd.cpp
demos/common/models/src/detection_model_yolo.cpp
demos/object_detection_demo/README.md

Algorithm for labels list adjustment (adding class for background) is removed. Check for labels list to correspond to number of output classes is removed.
If there's no label to some particular ID it will be shown as Label #N

Remove labels list adjustment in object detection models (SSD and Yolo).

---

tools/accuracy_checker/accuracy_checker/__init__.py
tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
tools/accuracy_checker/accuracy_checker/dataset.py
tools/accuracy_checker/tests/test_dataset.py

now converted annotation will store info about conversion.
These changes are backward compatible, so old annotations without such info still can be used

AC: added info about dumped annotation

---

demos/object_detection_demo/main.cpp

Object detection demo outputs object's width and height instead of xmax and ymax coordinates in raw results, this PR fixes it.

cpp object detection demo fix

---

tools/downloader/pytorch_to_onnx.py

This reduces memory usage, in some cases dramatically (for `cocosnet`, the reduction is from ~3 GB to ~2 GB).
The resulting ONNX models are unchanged.

pytorch_to_onnx.py: disable gradient calculation

---

tools/downloader/common.py

`postproc_file` already contains `output_dir` in it.

downloader: fix archive unpacking when --output_dir is a relative path

---

tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
tools/accuracy_checker/accuracy_checker/config/config_reader.py
tools/accuracy_checker/accuracy_checker/utils.py

some annotation conversion parameters have multiple possible sources (e.g. vocab files can be located in model_dir, data_dir or model_attributes_dir) stored as list of paths. Current fix resolves this situation.

AC: fix storing conversion meta if multiple path provided

---

demos/README.md
models/intel/driver-action-recognition-adas-0002/description/driver-action-recognition-adas-0002.md
tools/accuracy_checker/README.md
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/README.md
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
tools/accuracy_checker/sample/README.md
tools/downloader/README.md

Markdown links are shorter and more readable than HTML links, so they should be used whenever possible.
The HTML links were originally used because Doxygen didn't process external links to Markdown files correctly. This was fixed in Doxygen 1.8.16, and the OpenVINO documentation is now built using a newer version, so that bug is no longer relevant.

docs: replace HTML links with Markdown links

---

tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py

majority SR datasets has several input images for different upscaling factor (x2, x3, x4, e.t.c.), sometimes, this index is also included to file name and matched to regular expression for index search if relaxed names given.

AC: fix ID search logic for super resolution directory based conversion

---

ci/prepare-documentation.py
ci/requirements-documentation.in
models/intel/action-recognition-0001/composite-model.yml
models/intel/driver-action-recognition-adas-0002/composite-model.yml
models/intel/formula-recognition-medium-scan-0001/composite-model.yml
models/intel/formula-recognition-polynomials-handwritten-0001/composite-model.yml
models/intel/text-spotting-0003/composite-model.yml
models/public/forward-tacotron/composite-model.yml
models/public/mtcnn/composite-model.yml
models/public/wavernn/composite-model.yml

The layout file and page IDs generated by the script were previously maintained by the OpenVINO documentation team. Having them generated automatically lifts that burden off their shoulders and also makes it possible for us to autogenerate other aspects of the documentation in the future.
In the generated layout file, the titles of some pages are overridden. This is so that they match the titles in the table of contents from the previous releases of OpenVINO. Ideally, we should align the titles in the layout with the titles in the pages themselves, but I'm not yet sure which ones are better, so I'm deferring that for later.
About the requirements file: I used a pretty generic name for it (requirements-documentation), because I expect that other
documentation-related scripts (e.g. a model …

Add a script to prepare documentation for inclusion into OpenVINO docs

---

models/public/regnetx-3.2gf/model.py
models/public/regnetx-3.2gf/model.yml

Previously, it wasn't used in any way; the model constructor just downloaded the weights anew.

regnetx-3.2gf: use the weights file that we download

---

ci/requirements-ac-test.txt
ci/requirements-ac.txt
ci/requirements-check-basics.txt
ci/requirements-conversion.txt
ci/requirements-demos.txt
ci/requirements-downloader.txt
ci/requirements-quantization.txt
ci/update-requirements.py

The notable changes are:
* Updating PyYAML to 5.4.1, which fixes a long-standing security vulnerability (which we're not affected by, but still).
* Updating NumPy to 1.19.5, which works around the Windows bug that previously forced us to downgrade it to 1.19.3.
I've also regenerated the files with updated pip-compile, which formats it differently, but that's in a separate commit from version bumps.

Bump all CI requirement versions

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

some fresh devices is has not been listed in known plugins yet, but they should load configuration

AC: allow setting device config if device unknown

---

models/public/face-recognition-mobilefacenet-arcface/accuracy-check.yml
models/public/face-recognition-resnet100-arcface/accuracy-check.yml
models/public/face-recognition-resnet34-arcface/accuracy-check.yml
models/public/face-recognition-resnet50-arcface/accuracy-check.yml
models/public/facenet-20180408-102900/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
tools/accuracy_checker/accuracy_checker/metrics/classification.py

in numpy 1.19.5 np.str alias is deprecated and shown warning about it.

AC: minor issues fixes

---

tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/lpcnet_evaluator.py

Fixed number of arguments for predict method of sequential model to avoid TypeError: predict() got multiple values for argument 'callback'

AC: fixed lpcnet evaluator

---

ci/prepare-documentation.py

I originally added the list so that if a model with a new task type is added, the prepare-documentation script crashes and so the contributor has to consider what the human-readable description of the task type should be.
However, given that:
1. for almost all task types, the default string transformation yields a good description, and
2. the cost of getting the description wrong is just an awkwardly-named section in the documentation TOC,
I don't think that the cost of keeping an extra copy of the task type list is justified. Instead we should just instruct contributors to name task types so that the default transformation gives a good result, or, if that's not possible, to add an override.

ci/prepare-documentation.py: remove the hardcoded task type list

---

tools/accuracy_checker/accuracy_checker/preprocessor/color_space_conversion.py

Deletes casting to np.float32 when performing transformation to grayscale. This improves accuracy for at least text-recognition-0013 model up to 87.58 (baseline: 87.39)

Delete cast to np.float32 in grayscale transformations

---

tools/accuracy_checker/requirements.in

in the previous release, we fix parasail version due to issue with installation on windows. Now this issue resolved with new parasail version, so I remove this restriction

AC requirements: remove parasail version restriction

---

models/public/mozilla-deepspeech-0.6.1/accuracy-check-fast.yml
models/public/mozilla-deepspeech-0.6.1/accuracy-check.yml
models/public/mozilla-deepspeech-0.8.2/accuracy-check-fast.yml
models/public/mozilla-deepspeech-0.8.2/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/preprocessor/audio_preprocessing.py

Release 2021.3 had WER=6.13% for mozilla-deep-speech-0.8.2 (beam=500), 29 Jan 2021 develop commit deteriorated WER to 6.89%, this PR corrects this: now WER=6.13% again (for beam=500 with accuracy-check-fast.yml config). In addition there're code style corrections + removed an unused config option.

Fix computation of audio features in AC for mozilla-deepspeech-* that was broken by 28e5a72

---

models/intel/text-recognition-0013/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/preprocessor/color_space_conversion.py

Though #2112  improves accuracy of text-recognition-0013, it lowers accuracy of the text-recognition-0012. Now casting to float is optional which is True by default.

optional casting to float in grayscale

---

models/intel/text-recognition-0013/accuracy-check.yml
tools/accuracy_checker/accuracy_checker/adapters/text_recognition.py

This PR allows to use greedy search with text-recognition-0013 model. This does not affect accuracy, but speeds up measurement.
Currently, beam search with beam width=10 and greedy search produce the same result for text-recognition-0013.

add parameters to greedy decoder to make it able run tr-0013

---

demos/speech_recognition_demo/python/speech_recognition_demo.py

Use `safe_load`, which can't construct arbitrary Python objects.

speech_recognition_demo: avoid yaml.load

---

demos/common/cpp/models/include/models/internal_model_data.h
demos/common/cpp/models/src/detection_model.cpp
demos/common/cpp/models/src/hpe_model_associative_embedding.cpp
demos/common/cpp/models/src/hpe_model_openpose.cpp
demos/common/cpp/models/src/segmentation_model.cpp

Only human_pose_estimation crashed because it pads an image which
creates new Mat and other demos keep unchanged data in `ImageMetaData`.

demos: make sure input data lives during inference

---

demos/common/cpp/models/include/models/detection_model_yolo.h
demos/object_detection_demo/cpp/main.cpp

align default params between cpp/python object_detection_demo for yolo-v3 case

align cpp/python object_detection_demo 

---

demos/smart_classroom_demo/cpp/src/cnn.cpp

This PR add safeguard check if model can be processed in dynamic batch. According to OpenVINO [documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_DynamicBatching.html) dynamic batch feature not supported for models which have:
> layers that might arbitrary change tensor shape (such as Flatten, Permute, Reshape), layers specific to object detection topologies (ROIPooling, ProirBox, DetectionOutput), and custom layers

smart_classroom: allow running without dynamic batch

---

demos/README.md

The idea is to add the paths to demos (for both distribution package and repo) to the title page.

add pointers to demo location at demos README.md

---

tools/downloader/common.py

If a child process is terminated by a signal, there is usually no indication that that happened; it just looks like it exited normally. This is confusing for users looking at the conversion log.
Examine the process exit status and, if it was terminated by a signal, print the signal name and number.

tools/downloader: print signal name when a child processes is terminated by one

---

demos/formula_recognition_demo/python/README.md
models/intel/formula-recognition-medium-scan-0001/description/formula-recognition-medium-scan-0001.md
models/intel/formula-recognition-polynomials-handwritten-0001/description/formula-recognition-polynomials-handwritten-0001.md

formula-recognition demo and models descriptions did not refer to where one can get required vocabulary file, although these are provided in Open Model Zoo. This PR intend to fix the issue by adding reference to required files in model description and mentioning this in demo readme

add vocabulary files reference to formula-recognition models and demo

---

models/public/rexnet-v1-x1.0/model.yml
tools/downloader/requirements-pytorch.in

Only one model currently doesn't work with it; apply a workaround for it.

Allow using PyTorch 1.8 for model conversion

---

demos/tests/run_tests.py

Fixed incorrect PYTHONPATH modification with non-Windows delimiters on Windows.

Add PYTHONPATH modification logic for running python demos on Windows

---

models/public/regnetx-3.2gf/model.py
models/public/regnetx-3.2gf/model.yml

The `pycls.models.model_zoo.regnetx` function downloads the config file, which is bad, because:
1. all downloading is supposed to be done by the downloader, and
2. there's no integrity checking on the downloaded file (and in fact, the file can change, because the link points to the master branch of the repository), which endangers the security and reproducibility of the conversion process.
Add the config file to the list of the model's files and change the model creation code to avoid the unwanted download.

regnetx-3.2gf: don't download anything at conversion time

---

tools/accuracy_checker/accuracy_checker/metrics/regression.py
tools/accuracy_checker/accuracy_checker/presenters.py

PSNR & SSM metrics have differen target directions for different components (mean - higher-better, std - higher-worse), implemented mechanism which allow provide target info for results independently

AC: fix setting metric meta if several results required different

---

demos/tests/run_tests.py

The broken link to Image_Retrieval's list of images (gallery.txt) was replaced by new one.
The file was moved in [this](https://github.com/openvinotoolkit/training_extensions/commit/089de2f24667329a58e8560ed4e01ef203e99def) commit.

Fix broken link in run_tests.py description

---

tools/accuracy_checker/accuracy_checker/adapters/centernet.py
tools/accuracy_checker/accuracy_checker/adapters/detection.py
tools/accuracy_checker/accuracy_checker/adapters/retinaface.py
tools/accuracy_checker/accuracy_checker/annotation_converters/oar3d.py
tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py

in numpy 1.20 np.float alias for builtin float is deprecated, remove this dtype usage in AC

AC: remove deprecated np.float usage

---

demos/README.md

demos: update outdated references to CMake 2.8

---

ci/requirements-ac-test.txt
ci/requirements-ac.txt
ci/requirements-quantization.txt
tools/accuracy_checker/accuracy_checker/utils.py
tools/accuracy_checker/requirements-core.in

This solves several problems:
* it removes the use of the deprecated `cElementTree` module;
* it prevents developers from accidentally using lxml-specific features (AC doesn't require lxml, so that's unreliable);
* it prevents DoS on malicious input (`ElementTree` is vulnerable to entity expansion attacks).

AC: use defusedxml to read XML files instead of ET/lxml

---

tools/accuracy_checker/accuracy_checker/preprocessor/README.md
tools/accuracy_checker/accuracy_checker/preprocessor/normalization.py

by default normalization applied to all model inputs, however not all of them may require normalization. Prevent usage normalization parameters for non image inputs in case, when user explicitly set it

AC: ignore non image inputs in normalization

---

tools/downloader/downloader.py

Help message changed as below:
```
--precisions PREC[,PREC...]
download only models with the specified precisions
(actual for DLDT networks); specify one or more of:
FP16-INT8,FP16,FP32,FP32-INT8,FP32-INT1,FP16-INT1
```
Previously, it was:
```
--precisions PREC[,PREC...]
download only models with the specified precisions
(actual for DLDT networks)
```

Minor help message improvement for the ease of use

---

demos/multi_camera_multi_target_tracking_demo/python/run_evaluate.py
demos/smart_classroom_demo/cpp/action_event_metrics.py

defusedxml prevents DoS due to malicious XML entities.
I don't think we need to add it to the requirements, because we only parse XML in supplementary scripts that likely won't be used by most users of the demos.

demos: use defusedxml to parse XML

---

tools/accuracy_checker/tests/test_dlsdk_launcher.py

affinity setting test was disabled due to runtime issue in the previous used package version. Now issue resolved, so I return test back

AC tests: enable affinity test back

---

.gitattributes

Previously, the AC jobs used to run yamllint on the configs, but now that is done by the trigger job as part of the basic checks, so there's no reason to run AC jobs when config files are changed anymore.

Don't run the AC CI jobs on changes to the config files

---

tools/accuracy_checker/accuracy_checker/adapters/yolo.py
tools/accuracy_checker/accuracy_checker/dataset.py
tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/tests/test_dataset.py

there is problem with getting fp16 output from imported blobs (during translation from C++ to Python, it become I16), properly handle this out data type

AC: workaround fp16 output precision issue

---

demos/formula_recognition_demo/python/formula_recognition_demo.py
demos/formula_recognition_demo/python/utils.py
demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
demos/multi_camera_multi_target_tracking_demo/python/configs/vehicle.py
demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/mct.py
demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/sct.py
demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
demos/multi_camera_multi_target_tracking_demo/python/utils/misc.py
demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py
demos/speech_recognition_demo/python/speech_recognition_demo.py
demos/speech_recognition_demo/python/utils/ctcnumpy_beam_search_decoder.py
demos/whiteboard_inpainting_demo/python/utils/network_wrappers.py
models/public/mozilla-deepspeech-0.8.2/mds_convert_utils/parse_openfst.py
models/public/mozilla-deepspeech-0.8.2/mds_convert_utils/parse_trie_v6.py
models/public/mozilla-deepspeech-0.8.2/scorer_to_kenlm.py

When the keys of a dictionary are identifier-like strings that are known ahead of time, I find `types.SimpleNamespace` to be better suited for the job than `dict`. The attribute access syntax feels more natural than indexing syntax, and the `repr` of namespace instances is more readable than that of `dict`s. Namespaces can also be replaced with more specific types (e.g. dataclasses) to improve type safety in the future, without changing the code that accesses the attributes.
Note that I import the type as `namespace`, because that's the name it uses in the `repr`.

demos: replace some dicts with namespaces

---

.flake8
demos/speech_recognition_demo/python/utils/deep_speech_pipeline.py

Fix the last remaining violations.
I would've preferred to turn the profiles in `speech_recognition_demo` into instances of `types.SimpleNamespace` (instead of changing the initialization syntax), but they have to be compatible with what `yaml.safe_load` returns, which is a dict.
Granted, it would be possible to convert the result of `yaml.safe_load` into a namespace, but then there would need to be error handling for the case that the keys are not strings; plus if the profile ever needs to contain nested dicts, those would need to be converted too. All in all, it's possible, but it looks like enough of a mess that I don't want to get into it. :-)

Enable flake8-comprehensions warning C408

---

models/public/cocosnet/model.yml

We now require PyTorch 1.8+, so it's no longer relevant.
This has no effect on the resulting IRs.

cocosnet: remove the PyTorch 1.7 workaround

---

.gitattributes
ci/prepare-openvino-content.py

This replicates the logic that is currently used in internal CI to prepare OMZ contents for inclusion into OpenVINO toolkit. It will now live in this repository, which increases transparency and makes it easier to update the packaging logic in sync with the project.

Add a script to prepare OMZ content for OpenVINO

---

models/public/faster_rcnn_inception_resnet_v2_atrous_coco/faster_rcnn_inception_resnet_v2_atrous_coco.md
models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md
models/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.md
models/public/faster_rcnn_resnet50_coco/faster_rcnn_resnet50_coco.md
models/public/index.md
models/public/mask_rcnn_inception_resnet_v2_atrous_coco/mask_rcnn_inception_resnet_v2_atrous_coco.md
models/public/mask_rcnn_inception_v2_coco/mask_rcnn_inception_v2_coco.md
models/public/mask_rcnn_resnet101_atrous_coco/mask_rcnn_resnet101_atrous_coco.md
models/public/mask_rcnn_resnet50_atrous_coco/mask_rcnn_resnet50_atrous_coco.md

Сhecked accuracy results for faster_rcnn and mask_rcnn models with AC configs from OMZ and updated accuracy values for these models in documentation.

Updated accuracy values for faster_rcnn and mask_rcnn models

---

.gitattributes
CONTRIBUTING.md
ci/check-basics.py
ci/check-documentation.py
ci/lib/omzdocs.py
ci/prepare-documentation.py

Currently it's just checking local links, but later on we could add checks on the indexes, page title checks, etc.
The script is lightweight enough to be run for every pull request, so do that.
See commit messages for more details.

Add a script to do quick documentation checks

---

.gitattributes
ci/dependencies.yml

This will let us upgrade OpenVINO on CI by submitting a PR that edits the config, which will make it easy to test OMZ with new OpenVINO packages, as well as make synchronized project changes if necessary (e.g. changing the Python dependencies).
I used different Python keys for different OSes, because sometimes different builds are used as the final release for each OS. We might also want to use different pre-release builds for whatever reason.

Add a config describing which version of OpenVINO toolkit to use in CI

---

ci/check-documentation.py
ci/lib/omzdocs.py

I have previously fixed errors where people would accidentally add text that was interpreted as HTML syntax even though it was not intended to be (see af9d6d02). This check helps to prevent such errors in the future.
We can't prevent all errors, because we can't prohibit raw HTML entirely, as some constructs aren't expressible in native Markdown (e.g. `<sup>`). But we can check that any HTML elements that are used are known by Doxygen (which is used to build OpenVINO documentation), which will at least prevent some errors.
Technically, we could also prohibit some elements that _are_ known by Doxygen, but for which there are native Markdown equivalents (e.g. `<code>`). I've not done that, because I don't want to figure out the exact list right now. Maybe later.

ci: add a check for unknown HTML elements in the documentation

---

data/dataset_definitions.yml
data/datasets.md
models/public/index.md
models/public/mobilenet-ssd/accuracy-check.yml
models/public/mobilenet-ssd/mobilenet-ssd.md
models/public/ssd300/accuracy-check.yml
models/public/ssd300/ssd300.md
models/public/ssd512/accuracy-check.yml
models/public/ssd512/ssd512.md
models/public/yolo-v1-tiny-tf/accuracy-check.yml
models/public/yolo-v1-tiny-tf/yolo-v1-tiny-tf.md

- Added dataset to dataset_definitions.yml
- Updated docs and accuracy results for mobilenet-ssd, ssd300, ssd512, yolo-v1-tiny-tf public models
- Updated dataset preparation guide, included VOC2007 dataset for object detection task

Added VOC2007 dataset, changed VOC2012 to VOC2007 for public models

---

demos/common/python/models/__init__.py
demos/common/python/models/centernet.py
demos/common/python/models/faceboxes.py
demos/common/python/models/model.py
demos/common/python/models/ssd.py
demos/common/python/models/ultra_lightweight_face_detection.py
demos/common/python/models/utils.py
demos/object_detection_demo/python/README.md
demos/object_detection_demo/python/object_detection_demo.py

Add support of models in ONNX format for object_detection_demo.py:
- ctdet_coco_dlav0_384
- ctdet_coco_dlav0_512
- faceboxes-pytorch
- ssd-resnet34-1200-onnx
- ultra-lightweight-face-detection-rfb-320
- ultra-lightweight-face-detection-slim-320
The info about mean_values, scale_values and reverse_input_channels is located in `model.yml` for each model.

object_detection_demo.py: add import of ONNX models

---

demos/README.md
demos/image_retrieval_demo/python/README.md
demos/instance_segmentation_demo/python/README.md
tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
tools/accuracy_checker/accuracy_checker/launcher/pytorch_launcher_readme.md

Notes about specific links:
* In `image_retrieval_demo`, use a specific commit to prevent the link from breaking in the future (the same commit that's referenced in `run_tests.py`). Since it's supposed to just be an example, there's no reason to reference the latest version of the file.
* In `instance_segmentation_demo`, remove the link entirely, because OTE no longer contains the text that was referenced.

Fix broken links

---

models/public/aclnet-int8/README.md
tools/accuracy_checker/README.md
tools/downloader/README.md

This also ends up fixing the `datasets.md` links, which were broken when that file was moved into the `data/` directory.

Replace absolute links to Markdown files with relative ones

---

ci/requirements-demos.txt
demos/multi_camera_multi_target_tracking_demo/python/README.md
demos/multi_camera_multi_target_tracking_demo/python/requirements.txt
demos/requirements.txt

TensorBoard is a heavy package with a lot of dependencies, and it's not actually *used* by the demo - the user is supposed to run it manually.

multi_camera_multi_target_tracking_demo: remove TensorBoard from deps

---

demos/multi_camera_multi_target_tracking_demo/python/requirements.txt

Not sure why it was there in the first place. The demo doesn't use it.

multi_camera_multi_target_tracking_demo: remove setuptools from requirements.txt

---

demos/common/cpp/utils/src/args_helper.cpp
demos/common/cpp/utils/src/config_factory.cpp
demos/common/python/pipelines/__init__.py
demos/common/python/pipelines/async_pipeline.py
demos/deblurring_demo/python/deblurring_demo.py
demos/human_pose_estimation_demo/cpp/main.cpp
demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
demos/object_detection_demo/cpp/main.cpp
demos/object_detection_demo/python/object_detection_demo.py
demos/segmentation_demo/cpp/main.cpp
demos/segmentation_demo/python/segmentation_demo.py

Don't bind threads: thread binding came from benchmark_app which
does't run anything during inference. But if -d MULTI:CPU,GPU is
set, there is an extra thread to maintain GPU. In that case threads
aren't bound. Following that logic demos never bind threads because
there is main thread running pre and postprocessing. Additionally,
that's what IE says:
> 'YES' (default) binding option maps threads to cores - this
works best for static/synthetic scenarios like benchmarks.
Fix Python IE configs and follow C++ implementation.

demos: align C++ and Python IE configs

---

tools/accuracy_checker/accuracy_checker/metrics/README.md

The PDF is not accessible without a Springer subscription.
My claim that #2327 fixed the last broken link turned out to be incorrect. 😔

AC: replace Springer PDF link with DOI link

---

tools/accuracy_checker/setup.py

AC installer uses readme during installation as long description. After last docs update https://github.com/openvinotoolkit/open_model_zoo/pull/2321 , install process was broken due to addition symbols which can be unsuccessfully decoded on some systems. Added decoding during file reading. Currently internal validation CI is broken... so please merge ASAP
P.S. @ntyukaev please in the next time call me on review if you will update AC docs to prevent such situations.

Fix AC install after docs update

---

ci/check-release-readiness.py

* Documentation files have a specific name now (`README.md`).
* We now have `composite-model.yml` files which also should be checked (they are needed for correct documentation generation).

ci/check-release-readiness.py: update to match layout changes

---

tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py

fix average over channels (it was averaged over samples)
add keepdim to be sure that 1 and 2 channels audio files produces output with the same dim [chanel_num, samples_num]

fix for wave reader mono flag processing

---

tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py

Postprocessor execution is disabled when there is no need to compute a metric. A little refactoring of the code.

AC: Fixed quantization_model_evaluator in the case when there is no need to calculate metric

---

demos/common/cpp/models/include/models/results.h
demos/common/cpp/models/src/classification_model.cpp
demos/common/cpp/models/src/detection_model_centernet.cpp
demos/common/cpp/models/src/detection_model_faceboxes.cpp
demos/common/cpp/models/src/detection_model_retinaface.cpp
demos/common/cpp/models/src/detection_model_ssd.cpp
demos/common/cpp/models/src/detection_model_yolo.cpp
demos/common/cpp/models/src/hpe_model_associative_embedding.cpp
demos/common/cpp/models/src/hpe_model_openpose.cpp
demos/common/cpp/models/src/segmentation_model.cpp

Initializing results object fields using constructors instead of implicit copying after object instantiation.

Refactoring: init paramteres are added to the Results classes

---

tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py

when conversion executed via `convert_annotation` script there is no commandline mapping, however paths are still present in annotation parameters. 
Previous solution skips this case and make annotation incompatible to run on different platforms (e.g. convert on linux and run on windows)

AC: fix paths storing in annotation meta

---

demos/build_demos_msvc.bat

Parentheses are special characters in the Windows command line interpreter, so if `%0` contains them (which will often be the case, given that OpenVINO installs into "C:\Program Files (x86)" by default), its substitution will create a syntax error on the `echo` line.
Normally, quotes suppress processing of special characters, and the substitution of `%0` _was_ in quotes. However, `%0` contains quotes of its own (since you have to quote the batch file path to run it), which end up canceling out the quotes around the substitution.
The solution is to strip the inner quotes from `%0` (by using `%~0` instead), so that the outer quotes can suppress the processing of the parentheses. (I could remove the outer quotes instead, but I'm not sure we can rely upon the inner quotes always being …

build_demos_msvc.bat: fix syntax error when %0 contains parentheses

---

tools/downloader/pyproject.toml
tools/downloader/setup.cfg
tools/downloader/setup.py
tools/downloader/src/open_model_zoo/model_tools/_common.py
tools/downloader/src/open_model_zoo/model_tools/quantizer.py

This is needed to enable the integration of the model tools into the `openvino-dev` distribution.

tools/downloader: add setuptools configuration

---

models/public/resnest-50-pytorch/model.yml

The original link is broken due to the host reaching a download limit.

resnest-50-pytorch: replace weights download link

---

tools/downloader/tests/representative-models.lst

It's in `representative-models-quantization.lst`, but for it to be quantized, it has to be downloaded/converted first, and the CI scripts use this file to select models for downloading and conversion.

tools/downloader/tests/representative-models.lst: add hbonet-0.5

---

tools/downloader/README.md
tools/downloader/src/open_model_zoo/model_tools/_common.py
tools/downloader/src/open_model_zoo/model_tools/converter.py

If our tools are installed as part of the `openvino-dev` distribution, then it doesn't make sense to ask the user to run `setupvars`, seeing as:
1. It doesn't exist.
2. We know that MO is installed as part of the same distribution.
Therefore, before trying to find MO the old way, try to locate its package and if that succeeds, run it as a package.
I moved the documentation for the `-p` option up, because I'm referencing its value in the documentation for the `--mo` option.
`get_package_path` is in `_common`, because we're likely going to implement the same thing in the quantizer (for POT).

Model Converter: try to run Model Optimizer as a package

---

tools/downloader/README.md
tools/downloader/src/open_model_zoo/model_tools/_configuration.py
tools/downloader/src/open_model_zoo/model_tools/info_dumper.py
tools/downloader/src/open_model_zoo/model_tools/quantizer.py

This has been long overdue - now the users of the info dumper can determine programmatically which models can be quantized.
Instead of a boolean, we report the quantizer output precisions. This way, we can have different precisions per model in the future. Similarly for the added `if` in the quantizer - it's currently useless, as there's no way to skip every precision for a model, but if some model has an unusual set of output precisions in the future, that will become a possibility.
The name `quantization_output_precisions` is a bit bulky, but I thought that if it was called just `quantization_precisions`, it would be unclear whether that was referring to input or output precisions.

tools/downloader: dump the information about which models are quantizable

---

models/intel/face-detection-0200/README.md
models/intel/face-detection-0202/README.md
models/intel/face-detection-0204/README.md
models/intel/face-detection-0205/README.md
models/intel/face-detection-0206/README.md
models/intel/horizontal-text-detection-0001/README.md
models/intel/instance-segmentation-security-0002/README.md
models/intel/instance-segmentation-security-0091/README.md
models/intel/instance-segmentation-security-0228/README.md
models/intel/instance-segmentation-security-1039/README.md
models/intel/instance-segmentation-security-1040/README.md
models/intel/person-detection-0200/README.md
models/intel/person-detection-0201/README.md
models/intel/person-detection-0202/README.md
models/intel/person-detection-0203/README.md
models/intel/person-vehicle-bike-detection-2000/README.md
models/intel/person-vehicle-bike-detection-2001/README.md
models/intel/person-vehicle-bike-detection-2002/README.md
models/intel/person-vehicle-bike-detection-2003/README.md
models/intel/person-vehicle-bike-detection-2004/README.md
models/intel/text-spotting-0004/README.md
models/intel/vehicle-detection-0200/README.md
models/intel/vehicle-detection-0201/README.md
models/intel/vehicle-detection-0202/README.md

Add links in model descriptions to OpenVINO Training Extensions, where applicable

add OpenVINO Training Extensions links

---

models/public/resnest-50-pytorch/model.yml

The Dropbox upload was evidently temporary, as the repository author has now uploaded the weights as GitHub release artifacts (zhanghang1989/ResNeSt#156).

resnest-50-pytorch: replace weights download link again

---

tools/downloader/src/open_model_zoo/model_tools/_configuration.py
tools/downloader/src/open_model_zoo/model_tools/downloader.py

Historically, hashes have sometimes been represented as bytes and sometimes as character strings. Fundamentally, however, hashes are bytestrings, so represent them as such internally and convert them from/to strings when doing input/output.

tools/downloader: consistently represent hashes as bytes objects

---

demos/common/cpp/utils/include/utils/ocv_common.hpp

A code analyzer was worried that `scaleFactor` was uninitialized. We
never use it in such cases, but the fix is simple, so let it be.

demos: assign default value for scaleFactor

---

tools/downloader/src/open_model_zoo/model_tools/converter.py

`convert` initially started small, so it made sense to make it a local function within `main`. But then it grew and grew, to the point where it's now the same length as the rest of `main` (not counting the argument parsing). It's clearly no longer readable to keep it as a local function, so move it to the module level instead.

Model Converter: move the convert function to the module level

---

models/public/aclnet-int8/README.md
models/public/aclnet/README.md
models/public/ctdet_coco_dlav0_384/README.md

Fixed broken <omz_dir> links to files with datasets classes (`aclnet_53cl.txt` and `coco_80cl.txt`).

Fixed broken <omz_dir> links.

---

tools/downloader/README.md
tools/downloader/src/open_model_zoo/model_tools/quantizer.py

Basically, the same thing as in 1df8e872, but for POT instead of MO. The code is simpler here, because we don't need to know the directory POT is installed in.

Model Quantizer: try to run POT as a package

---

demos/multi_channel_common/cpp/multichannel_params.hpp
demos/multi_channel_face_detection_demo/cpp/README.md
demos/multi_channel_human_pose_estimation_demo/cpp/README.md
demos/multi_channel_object_detection_demo_yolov3/cpp/README.md

fix multi-channel demos `-i` option description, missed at 7916a098af33203c64a0d184dd9dcfaae4cbe553 commit

fix multi channel demo description

---

demos/common/cpp/utils/include/utils/default_flags.hpp
demos/human_pose_estimation_demo/cpp/main.cpp
demos/object_detection_demo/cpp/main.cpp
demos/segmentation_demo/cpp/main.cpp

It is better to define the flag only for demos, where it is used.

Don't make -output_resolution flag as default

---

demos/action_recognition_demo/python/README.md
demos/monodepth_demo/python/README.md
tools/accuracy_checker/accuracy_checker/annotation_converters/README.md

This improves consistency, and, in the case of `driver_actions.txt`, enables automatic path checking.
Also, replace the `<openvino_install_dir>` placeholder (which isn't used anywhere else) with `<openvino_dir>` (which is).

Use code spans to format paths in the documentation

---

demos/human_pose_estimation_demo/cpp/main.cpp

With `frameNum = -1` the demo did not process and draw result for one image

human_pose_estimation_cpp: fix default value of frameNum

---

tools/accuracy_checker/accuracy_checker/adapters/text_recognition.py

in POT json, dict keys can be incorrectly parsed by the tool (as the result we get strings instead of ints)

AC: cast custom label map

---

tools/accuracy_checker/setup.py

current installation way is unsafe and can use wrong python executable for installation dependencies.
Beside that it does not handle commented lines properly

AC: update install for arm

---

demos/social_distance_demo/cpp/include/person_trackers.hpp
demos/social_distance_demo/cpp/src/geodist.cpp

In the next lines:
` double bdinf = B.x < D.x ? -9999999999. : 9999999999.;`
` double acinf = A.x < C.x ? -9999999999. : 9999999999.;`
If we get equal values, `bdinf` ( or `acinf`) will have wrong sign and eventually program wil get stuck in the infinite loop. So I changed condition threre, and rounded doubles to ints for correct comparison ( A, B, C, D points contain coordinates in pixels and it's better to compare them in int).

Social distance demo fix

---

demos/multi_channel_human_pose_estimation_demo/cpp/README.md
demos/multi_channel_human_pose_estimation_demo/cpp/models.lst

multi_channel_human_pose_estimation_demo support only human-pose-estimation-0001 model, but we got more models with similar name and other versions, so template in models.lst have to be reduced to single supported model

reduce models.lst to only supported model

---

demos/common/python/models/yolo.py

do not rely on output blob names for yolo-v4

fix yolo-v4 demo

---

tools/accuracy_checker/accuracy_checker/annotation_converters/label_me_converter.py
tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py
tools/accuracy_checker/accuracy_checker/metrics/detection.py
tools/accuracy_checker/accuracy_checker/metrics/regression.py
tools/accuracy_checker/tests/test_regression_metrics.py

1. sometimes json can not automatically detect int keys in dict, need to be explicitly casted
2. interval metric get incorrect result due to wrong list of class names in metrc

AC: bugfixes for label me and interval metric

---

demos/common/python/models/centernet.py
demos/common/python/models/ctpn.py
demos/common/python/models/faceboxes.py
demos/common/python/models/retinaface.py
demos/common/python/models/ssd.py
demos/common/python/models/ultra_lightweight_face_detection.py
demos/common/python/models/utils.py
demos/common/python/models/yolo.py
demos/object_detection_demo/python/object_detection_demo.py

1. `draw_detections` and `print_raw_results` functions don't have to apply thresholding, because all models (except ssd) filter detections by threshold in postprocess. Added thresholding to SSD models instead
2. In two stage pipelining the second model may require clipped boxes, so the clipping should be moved to postprocess (otherwise the clipping is applied twice)

object_detection_demo.py: move boxes clipping to postprocess

---

demos/tests/cases.py

cpp smart classroom demo hasn't been tested since merging gapi version of this demo due to changes in [cases.py](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/tests/cases.py). In both cases were tested cpp_gapi demo ([here](https://github.com/openvinotoolkit/open_model_zoo/blob/d488c3b5705383de38eb20b51ba83b02f82ed6da/demos/tests/cases.py#L394) and [here](https://github.com/openvinotoolkit/open_model_zoo/blob/d488c3b5705383de38eb20b51ba83b02f82ed6da/demos/tests/cases.py#L428)).

Fix test case for cpp smart classroom demo

---

demos/formula_recognition_demo/python/README.md

In some cases, `dvi-png` is not included in texlive distribution and should be installed separately. Also, `standalone.cls` may be required (not included in texlive by default). It is installed as part of the texlive-extra package.

Update formula-recognition-demo docs.

---

ci/prepare-documentation.py
demos/classification_demo/cpp/README.md
demos/multi_channel_object_detection_demo_yolov3/cpp/README.md
demos/object_detection_demo/cpp/README.md
demos/text_detection_demo/cpp/README.md

checks for each model (or part of composite model) reference existence:
- in `device_support.md` files (based on models folders names)
- in demos `README.md` files (based on `models.lst` files content)

Added checks for models references in documentation files

---

tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py

Inference Engine Python API can not properly handle dict-like objects as device configuration (however python itself and AC does not have such restriction in data types usage), need explicit casting to dictionary, when it provided.

AC: handle unexpected device config type for IE

---

demos/common/cpp/models/include/models/segmentation_model.h
demos/common/cpp/models/src/segmentation_model.cpp
demos/common/python/models/segmentation.py
demos/segmentation_demo/cpp/README.md
demos/segmentation_demo/cpp/main.cpp
demos/segmentation_demo/python/README.md
demos/segmentation_demo/python/segmentation_demo.py

With `-r` option on, both C++ and Python segmentation demo print raw result as class distribution, e.g.:
```
[ INFO ]  Class ID | Pixels | Percentage
[ INFO ]        #0 | 870304 | 94.434%
[ INFO ]        #1 |  51296 | 5.56597%
```
TODO:

Add class distribution for segmentation demo results

---

demos/speech_recognition_deepspeech_demo/python/README.md

Converted file has hyphens, not underscores.

Correct IE model filennames

---

demos/speech_recognition_deepspeech_demo/python/README.md

Converted file has hyphens, not underscores.

Correct IE model filennames (#2610)

---

demos/common/cpp/pipelines/include/pipelines/requests_pool.h
demos/common/cpp/pipelines/src/async_pipeline.cpp
demos/common/cpp/pipelines/src/requests_pool.cpp
demos/object_detection_demo/cpp/main.cpp

Fix for [issue](https://community.intel.com/t5/forums/forumtopicpage/board-id/distribution-openvino-toolkit/message-id/24012#M24012) reported on user forum (internal id CVS-59597)
Free lambda callbacks on requests pool destruction because callback cleanup does not work from callback itself for HDDL
sync processing of tail (in main.cpp) with segmentation demo

fix object_detection_demo work on hddl

---

demos/common/cpp/pipelines/include/pipelines/requests_pool.h
demos/common/cpp/pipelines/src/async_pipeline.cpp
demos/common/cpp/pipelines/src/requests_pool.cpp
demos/object_detection_demo/cpp/main.cpp

* Free lambda callbacks on requests pool destruction because callback cleanup does not work from callback itself for HDDL
sync processing of tail (in main.cpp) with segmentation demo
* Update demos/common/cpp/pipelines/src/async_pipeline.cpp
Co-authored-by: Fedor Zharinov <fedor.zharinov@intel.com>
* Update demos/common/cpp/pipelines/src/async_pipeline.cpp
Co-authored-by: Fedor Zharinov <fedor.zharinov@intel.com>
* Update demos/common/cpp/pipelines/src/async_pipeline.cpp
Co-authored-by: Fedor Zharinov <fedor.zharinov@intel.com>
Co-authored-by: Fedor Zharinov <fedor.zharinov@intel.com>

fix object_detection_demo work on hddl (#2603)

---

demos/action_recognition_demo/python/action_recognition_demo.py
demos/colorization_demo/python/colorization_demo.py
demos/deblurring_demo/python/deblurring_demo.py
demos/face_recognition_demo/python/face_recognition_demo.py
demos/gesture_recognition_demo/python/gesture_recognition_demo.py
demos/human_pose_estimation_3d_demo/python/human_pose_estimation_3d_demo.py
demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
demos/image_retrieval_demo/python/image_retrieval_demo.py
demos/instance_segmentation_demo/python/instance_segmentation_demo.py
demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py
demos/object_detection_demo/python/object_detection_demo.py
demos/place_recognition_demo/python/place_recognition_demo.py
demos/segmentation_demo/python/segmentation_demo.py
demos/single_human_pose_estimation_demo/python/single_human_pose_estimation_demo.py
demos/text_spotting_demo/python/text_spotting_demo.py
demos/whiteboard_inpainting_demo/python/whiteboard_inpainting_demo.py

In PR #2547 cpp implementation of `reportMeans()` function was changed to allow printing with `[ INFO ]`  prefix on each new line:
```
[ INFO ] Resources usage:
[ INFO ]        Mean core utilization: 99.7% 99.4% 99.7% 99.7%
[ INFO ]        Mean CPU utilization: 99.6%
[ INFO ]        Memory mean usage: 8.4 GiB
[ INFO ]        Mean swap usage: 0.2 GiB
```
This PR supports these changes in python

Change how presenter.reportMeans() is printed in python demos.

---

demos/common/cpp/utils/src/performance_metrics.cpp
demos/common/python/helpers.py
demos/common/python/images_capture.py
demos/common/python/performance_metrics.py
demos/common/python/pipelines/async_pipeline.py
demos/deblurring_demo/python/deblurring_demo.py
demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
demos/image_retrieval_demo/python/image_retrieval_demo.py
demos/object_detection_demo/python/object_detection_demo.py
demos/place_recognition_demo/python/place_recognition_demo.py
demos/segmentation_demo/python/segmentation_demo.py

Add logging of latency per stage for API demos, update `PerformanceMetrics` to be consistent with C++ implementation (fix latency for one image case, move drawing metrics on the frame in a separate function)

Python: latency logging for every stage of pipeline

---

demos/segmentation_demo/cpp/README.md
demos/segmentation_demo/cpp/main.cpp
demos/segmentation_demo/python/README.md
demos/segmentation_demo/python/segmentation_demo.py

Activated by `-only_masks`/`--only_masks` option or by `TAB` key during demo running

Segmentation demo: switch between overlay masks / only masks

---

demos/segmentation_demo/cpp/README.md
demos/segmentation_demo/cpp/main.cpp
demos/segmentation_demo/python/README.md
demos/segmentation_demo/python/segmentation_demo.py

* Add switch overlay masks / only masks for both CPP and Python segmentation demo

Segmentation demo: switch between overlay masks / only masks (#2648)

---

demos/CMakeLists.txt

Create PR instead of corrupted https://github.com/openvinotoolkit/open_model_zoo/pull/2684
Fix to https://github.com/openvinotoolkit/open_model_zoo/pull/2641
It sets `armv7` instruction set to x32 only. The previous PR treats ARM64 architecture which is used in Apple M1 chip incorrectly.

Define armv7 instruction set for OMZ demos built natively on x32 ARM

---

models/intel/noise-suppression-poconetlike-0001/README.md
models/intel/noise-suppression-poconetlike-0001/accuracy-check.yml

Update weights for noise_suppresion model. The model topology is the same (except some states tensors) but new weights is trained on full DNS-Challenge dataset and provide better quality. New sisdr_diff is 8.81 in comparison to old one 8.1

Update weights for noise_suppresion model.

---

models/intel/icnet-camvid-ava-0001/README.md
models/intel/icnet-camvid-ava-0001/accuracy-check.yml
models/intel/icnet-camvid-ava-sparse-30-0001/README.md
models/intel/icnet-camvid-ava-sparse-30-0001/accuracy-check.yml
models/intel/icnet-camvid-ava-sparse-60-0001/README.md
models/intel/icnet-camvid-ava-sparse-60-0001/accuracy-check.yml

According to the documentation, `unlabeled` class should be ignored during metrics calculation.

Update accuracy for intel segmentation models

---

ci/requirements-conversion.txt

Fixing `ModuleNotFoundError: No module named 'mxnet'` (occurs during the models converting stage).

Added mxnet==1.2.0 to requirements-conversion.txt for Demos Windows 10 Job

---

models/public/yolo-v4-tiny-tf/model.yml

Model yolo-v4-tiny-tf quantized by POT from OpenVINO 2021.4 with default algorithm and demonstrate acceptable accuracy drop in quantized form. This PR marks model as quantizable.
Accuracy validation results on CPU w/VNNI instructions set
|model|metric|REF|FP16|FP16-INT8|
|---|---|---|---|---|
|yolo-v4-tiny-tf|map|0.403|0.40388|0.398336|
|yolo-v4-tiny-tf|AP@0.5|0.463|0.463847|0.456495|
|yolo-v4-tiny-tf|AP@0.5:0.05:95|0.226|0.226601|0.221222|

Added yolo-v4-tiny-tf model to quantizable models

---

demos/common/cpp/models/include/models/segmentation_model.h
demos/common/cpp/models/src/segmentation_model.cpp

The same implementation as in `ImageModel` class, from which the `SegmentationModel` is inherited.

cpp: remove preprocess() from SegmentationModel

---

demos/speech_recognition_deepspeech_demo/python/ctcdecode-numpy/ctcdecode_numpy/word_prefix_set.h

The include was added in order to build `ctcdecode_numpy` on GCC 6.
GCC 6 raises the compilation error because `size_t` definition is not found.

cstddef include added

---

demos/common/python/models/yolo.py

Optimize yolo postprocessing for detection demo, by using flatten operation and apply sigmoid function to all boxes at the same time.
**Speed up yoloV4**:
1. For YoloV4: `2.4 -> 3.7 fps` It's x1.55.
2. For YoloV4-tiny: `25 -> 50+ fps` It's x2.
The calculations were carried out on the CPU `Intel® Core™ i7-8700 CPU` and on video with resolution `1280 × 720`. `nstreams = 4, nrequests = 5, nthreads = auto` 
**Speed up yolo family**:
1. For `yolo-v3-tf`: `7.5 -> 8.4 fps` , **x1.12**
2. For `yolo-v3-tiny-tf`: `32 -> 62.8 fps`, **x1.96**
3. For `yolo-v2-tf`: `9 -> 9.1 fps`, x1
4. For `yolo-v2-tiny-tf`: `60 -> 70 fps`, **x1.16**
5. For `yolo-v2-tiny-ava-0001`: `51.6 -> 56.5 fps`, x1.1
6. For `yolo-v2-tiny-ava-sparse-30-0001`: `51.3 -> 57 fps`, x1.11
7. For `yolo-v2-tiny-ava-sparse-60-0001`: `52.5 …

Optimize yolo model postprocessing for python detection demo

---

models/public/device_support.md

wav2vec2-base does not work on GPU with OpenVINO 2021.4

wav2vec2-base suppress on GPU

---

models/public/common-sign-language-0001/README.md

The link to jester dataset was replaced by web.archive.org based one.

Fixed link to jester dataset

---

demos/common/python/models/__init__.py
demos/common/python/models/centernet.py
demos/common/python/models/ctpn.py
demos/common/python/models/detection_model.py
demos/common/python/models/detr.py
demos/common/python/models/faceboxes.py
demos/common/python/models/image_model.py
demos/common/python/models/model.py
demos/common/python/models/retinaface.py
demos/common/python/models/segmentation.py
demos/common/python/models/ssd.py
demos/common/python/models/ultra_lightweight_face_detection.py
demos/common/python/models/utils.py
demos/common/python/models/yolo.py
demos/object_detection_demo/python/README.md
demos/object_detection_demo/python/object_detection_demo.py

This PR demonstrates the possible refactoring of ModelAPI. The main goals of it is to make model wrappers more flexible and reusable.
TODO:
The class structure is represented below
- *Model*
Constructor parameters: `(ie, model_path)`
Abstract class, which just loads model from the disk and presents to methods to overload: `preprocess(inputs) -> preprocessed_inputs, meta` and `postprocess(outputs, meta) -> postprocessed_outputs`
- *ImageModel*
Constructor parameters: `(..., input_transform, resize_type)`
Incapsulates most common operations for image inputs, like resizing etc.  Finds image input blob with `_get_image_input()` method and puts it to `image_blob_name` field (image input is 4D tensor, if no or more than one found raise an error). Configures the resize operation (see …

Model API refactoring

---

demos/common/cpp/models/src/detection_model_yolo.cpp

See https://openvino-ci.intel.com/blue/organizations/jenkins/private-ci%2Fie%2Fbuild-linux-centos76/detail/build-linux-centos76/52237/pipeline/
For some reason this code from OMZ:
```c++
namespace ngraph {
namespace op {
namespace v0 {
class RegionYolo;
}
using v0::RegionYolo;
}
}
```
And this from ngraph:
```c++
namespace ngraph {
namespace op {
namespace v0 {
using ov::op::v0::RegionYolo;
}  // namespace v0
using v0::RegionYolo;
}  // namespace op
}  // namespace ngraph
```
Are conflicting with errors:
```sh
[ 77%] Building CXX object common/cpp/models/CMakeFiles/models.dir/src/detection_model_yolo.cpp.o
In file included from /home/sandye51/Documents/Programming/git_repo/dldt/ngraph/core/include/ngraph/ops.hpp:126:0,
from /home/sandye51/Documents/Programming/git_repo/dldt/ngraph/core/inc …
```

Fixed compilation with forward declaration

---

demos/tests/args.py
demos/tests/cases.py
demos/tests/run_tests.py

Added the setting of specific precisions (one/many) for testing the models in `.xml` format via the `--precisions` key and `set_precisions()` function.  
For every model the supported precisions (the info is located in `model_info[model_name].precisions`) are compared with precisions we want to test. For example, if the --precisions are set as following: [FP16, FP16-INT8], the models, which do not have IRs for FP16-INT8, are tested only in FP16 precision.
If a model does not support ANY of required precisions, the model is not tested at all.

[Tests] Set precisions for model testing via --precisions parameter

---

demos/interactive_face_detection_demo/cpp_gapi/face.hpp

I hope, that this `#include <list>` was an unnecessary removal.

GAPI: Returning include to IFD GAPI.

---

demos/image_retrieval_demo/python/README.md

The file was deleted in
https://github.com/openvinotoolkit/training_extensions/pull/660

demos/image_retrieval: update link to gallery.txt

---

demos/tests/cases.py

Enable face-detection-adas-0001 in interactive_face_detection_demo (cpp, cpp_gapi). This model is already present in the test cases, but its use is suppressed by the subsequent test case.

face-detection-adas-0001 interactive_face_detection_demo

---

tools/model_tools/src/openvino/model_zoo/_configuration.py

Make subdirectory for composite models relative to model root, same as for regular models.

model_tools: fix subdirectory for composite models

---

tools/accuracy_checker/setup.py

Looks like https://github.com/kpu/kenlm/commit/5cea457db26950a73d638425c183b368c06ed7c6 commit broken the ability to build kenlm module on Windows: https://openvino-ci.intel.com/job/private-ci/job/ie/job/accuracy-windows-acc_test/3989/
PR to check this fix in OpenVINO validation: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/664 
The issue submitted on kenlm: https://github.com/kpu/kenlm/issues/364

Fix kenlm version on the latest stable

---

demos/common/python/openvino/model_zoo/model_api/models/open_pose.py

stick OMZ python model api implementation for open pose model to opset7 which work both with 2021.4.2 and 2022.1 runtime

stick open pose model to opset7

---

models/intel/face-detection-0200/README.md
models/intel/face-detection-0202/README.md
models/intel/face-detection-0204/README.md
models/intel/face-detection-0205/README.md
models/intel/face-detection-0206/README.md
models/intel/horizontal-text-detection-0001/README.md
models/intel/instance-segmentation-person-0007/README.md
models/intel/instance-segmentation-security-0002/README.md
models/intel/instance-segmentation-security-0091/README.md
models/intel/instance-segmentation-security-0228/README.md
models/intel/instance-segmentation-security-1039/README.md
models/intel/instance-segmentation-security-1040/README.md
models/intel/person-detection-0200/README.md
models/intel/person-detection-0201/README.md
models/intel/person-detection-0202/README.md
models/intel/person-detection-0203/README.md
models/intel/text-spotting-0005/README.md
models/intel/vehicle-detection-0200/README.md
models/intel/vehicle-detection-0201/README.md
models/intel/vehicle-detection-0202/README.md

OTE changed `develop` branch to `misc` branch, so we have to update OTE links

update OTE links

---

tools/model_tools/src/openvino/model_zoo/_configuration.py
tools/model_tools/src/openvino/model_zoo/download_engine/cache.py
tools/model_tools/src/openvino/model_zoo/download_engine/downloader.py
tools/model_tools/src/openvino/model_zoo/download_engine/file_source.py
tools/model_tools/src/openvino/model_zoo/omz_downloader.py

Summary:
1. Some code from the `omz_downloader` main function is moved to a `bulk_download_model` method to make it easier to reuse.
2. Embedded functions are deprecated for the same reason.
3. `KNOWN_FRAMEWORKS` and `KNOWN TASK_TYPES` are turned into optional parameters to allow developers to use their own configs and thus handle validation.
4. Small code movement in order to save lib users from importing protected modules from OMZ.
5. Interface of `start_download` is slightly changed for those file types which need checksum info for downloading. Also, it allows to validate downloaded files additionally (e.g. compare the checksum of a downloaded file with the expected one).

Cvs 62354/adopt download engine for onezoo

---

ci/requirements-conversion.txt
tools/model_tools/requirements-paddle.in

paddle 2.1.3 has incompatible dependency with tf on windows, in 2.2.0 this problem is resolved

deps: move paddle version

---

demos/README.md
demos/background_subtraction_demo/cpp_gapi/CMakeLists.txt
demos/background_subtraction_demo/cpp_gapi/README.md
demos/background_subtraction_demo/cpp_gapi/background_subtraction_demo_gapi.hpp
demos/background_subtraction_demo/cpp_gapi/include/custom_kernels.hpp
demos/background_subtraction_demo/cpp_gapi/main.cpp
demos/background_subtraction_demo/cpp_gapi/models.lst
demos/background_subtraction_demo/cpp_gapi/src/custom_kernels.cpp
demos/tests/cases.py

* `--adapter` - demo works only with single model
* `-t` since needed only for `detection` models
* `--resize-type`- needed only for model adapter which isn't used
* `--labels` - supported only `instance-segmentation-person-????` models, that don't need labels
* `--show_with_original_frame`  - extra behavior for that demo
* `--output_resolution` - needed for `--show_with_original_frame` flag
* `--raw_output_message` - relevant only for detection models?

G-API: Background subtraction demo

---

demos/machine_translation_demo/python/requirements.txt
demos/requirements.txt
tools/accuracy_checker/requirements.in

We need to restrict tokenizers version in scope of 0.10 release at least temporarily, to fix issues with installation on Mac and Win in precommits (see https://openvino-ci.intel.com/job/private-ci/job/ie/job/e2e-tests-windows-pip-conflicts/21672/). Proper fix require updating environment on all physical nodes, which can be done later

Restrict tokenizers version to workaround install on Mac and Win

---

demos/segmentation_demo/python/README.md
demos/segmentation_demo/python/segmentation_demo.py

The purpose is to not keep this palette in SegmentationVisualizer class itself, but load colors from file in palettes folder, representing this palette.
Also, rendering is updated in order to decrease the latency of rendering time (80ms->10ms)

segmentation_demo.py: load default Pascal palette from file 

---

demos/requirements.txt

temporaly remove demo dependency on openvino as pypi version is not compatible with upcoming release

PYTHON DEMOS: remove ov from requirements

---

demos/tests/cases.py
demos/text_spotting_demo/python/text_spotting_demo.py

In the latest IR version `text_features` name is used.

text_spotting_demo: fix output layer name, restore the test

---

demos/interactive_face_detection_demo/cpp/detectors.cpp

There is only one model out of 6 which could make
use of auto_resize. I don't think it's worth it
to make it configurable.

demos/interactive_face_detection: disable auto_resize

---

demos/common/cpp/utils/include/utils/kuhn_munkres.hpp
demos/common/cpp/utils/src/kuhn_munkres.cpp
demos/gesture_recognition_demo/cpp_gapi/src/tracker.cpp
demos/pedestrian_tracker_demo/cpp/src/tracker.cpp
demos/smart_classroom_demo/cpp/src/tracker.cpp

Undo changes done in https://github.com/openvinotoolkit/open_model_zoo/pull/3227 and https://github.com/openvinotoolkit/open_model_zoo/pull/2923. 
Changing `size_t` to `int` broke initial logic and causes next error:
`
[ ERROR ] OpenCV(4.5.2-openvino) C:\Users\ivikhrev\Documents\Work\openvino\temp\opencv_4.5.2\opencv\include\opencv2/core/mat.inl.hpp:872: error: (-215:Assertion failed) (unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels()) in function 'cv::Mat::at' 
`
in some cases.

return size_t type to result in kuhn munkres

---

demos/text_detection_demo/cpp/include/cnn.hpp
demos/text_detection_demo/cpp/include/text_detection.hpp
demos/text_detection_demo/cpp/include/text_recognition.hpp
demos/text_detection_demo/cpp/main.cpp
demos/text_detection_demo/cpp/src/cnn.cpp
demos/text_detection_demo/cpp/src/text_detection.cpp
demos/text_detection_demo/cpp/src/text_recognition.cpp
demos/text_detection_demo/cpp/text_detection_demo.hpp

GPU plugin doesn't support auto resize feature. Make opencv resize as default.
p.s  `text-recognition-0015-encoder` model will fail with stack overflow error.

text_detection_demo: fix auto resize 

---

demos/gesture_recognition_demo/cpp_gapi/include/stream_source.hpp
demos/gesture_recognition_demo/cpp_gapi/main.cpp
demos/interactive_face_detection_demo/cpp_gapi/main.cpp
demos/smart_classroom_demo/cpp_gapi/include/tracker.hpp
demos/smart_classroom_demo/cpp_gapi/smart_classroom_demo_gapi.hpp
demos/smart_classroom_demo/cpp_gapi/src/tracker.cpp

Minor:
- Removed limit flag from ImagesCapture for IFD;
- Added help message for FLAG_limit for SCD;
- Changed name of CustomCaptureSource class for GestRec demo (common class has the same name);
- throw with extended messages for GestRec demo.

G-API: Align limit flag behavior of G-API demos with OMZ

---

tools/model_tools/src/openvino/model_zoo/download_engine/downloader.py

Fixes downloader message in case if specified precision is unsupported by the model (76778)

model_tools: add message about unsupported model precisions

---

demos/handwritten_text_recognition_demo/python/handwritten_text_recognition_demo.py

Use `set_property()` for GPU if only device is set in args.device. This behavior is aligned with action_recognition_demo.py, where we call set_property for MYRIAD device if the user set it directly.

handwritten_text_recognition_demo.py: set_property if GPU is specified in args.device

---

demos/tests/cases.py
demos/tests/data_sequences.py

`semantic-segmentation-adas` testset is used in segmentation demos also, so I decided to create separate smaller test set for this demo to avoid CI issues.

Reduce test set for mask rcnn demo

---

tools/accuracy_checker/requirements.in

latest version of imagecodecs droped python3.7 support, pin the last available for avoiding troubles

AC requirements: pin imagecodecs for py3.7

---

demos/3d_segmentation_demo/python/README.md
demos/README.md
demos/face_recognition_demo/python/README.md
demos/formula_recognition_demo/python/README.md
demos/handwritten_text_recognition_demo/python/README.md
demos/image_retrieval_demo/python/README.md
demos/multi_camera_multi_target_tracking_demo/python/README.md
demos/speech_recognition_deepspeech_demo/python/README.md
demos/whiteboard_inpainting_demo/python/README.md

Remove description of how to install requirements.txt for Python demos, since all requirements files are merged into one common file (https://github.com/openvinotoolkit/open_model_zoo/pull/3160)

Python demos documentation: remove info about requirements installation

---

demos/common/python/openvino/model_zoo/model_api/models/bert.py

Prevent the `IndexError: list index out of range` error in bert_named_entity_recongition_demo

BertNamedEntityRecognition wrapper: fix bounds for filtered_labels_id

---

demos/common/cpp/utils/src/config_factory.cpp

Restore the setting of nstreams for CPU. Before the default value for nstreams was 1 and the value from -nireq cmd parameter did not passed to the config

Set nstreams in cofig_factory.cpp for CPU 

---

demos/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py

The Layout utility datatype was recently introduced. However, it seems
to be polymorphic depending on the way it was constructed: sometimes
it's just a string, sometimes it has a data member called "layout".
This is just a fix to make OVMSAdapter work with the most common use
case. There is a bigger fix needed to patch all code paths in
OVMSAdapter and OpenvinoAdapter.

Work around Layout == str issue

---

demos/requirements.txt
tools/accuracy_checker/requirements.in

updated requirements to stay compatible with new transformers lib
tokenizers version was pinned globally in this PR https://github.com/openvinotoolkit/open_model_zoo/pull/3123
due to lack of wheels for win and mac for python3.6 in newer versions.
With transformers 4.17, we can not use such old tokenizers version

less restricted tokenizers version

---

demos/tests/run_tests.py

Added ability to write demos logs to file, set timeout for subprocess to 10 minutes, and sum up failures at the end.

add write logs to file, summary of failures, timeout for subprocess in run_tests.py

---

demos/README.md
demos/security_barrier_camera_demo/cpp/README.md
demos/social_distance_demo/cpp/README.md
demos/speech_recognition_deepspeech_demo/python/README.md
demos/speech_recognition_quartznet_demo/python/README.md
demos/speech_recognition_wav2vec_demo/python/README.md
demos/tests/run_tests.py
tools/accuracy_checker/configs/README.md

* remove old and deprecated deployment_tools path
* Apply suggestions from code review
Co-authored-by: Ekaterina Aidova <ekaterina.aidova@intel.com>
* restore auto-generated files
* rm VS2017
* restore DAV file
Co-authored-by: Ekaterina Aidova <ekaterina.aidova@intel.com>

fix deployment_tools in docs (#3364)

---

demos/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py

The Layout utility datatype was recently introduced. However, it seems
to be polymorphic depending on the way it was constructed: sometimes
it's just a string, sometimes it has a data member called "layout".
This is just a fix to make OVMSAdapter work with the most common use
case. There is a bigger fix needed to patch all code paths in
OVMSAdapter and OpenvinoAdapter.

Work around Layout == str issue (#3358)

---

tools/accuracy_checker/openvino/tools/accuracy_checker/data_readers/audio_readers.py

update error catching for soundfile
on ubuntu, soundfile requires install additional lib and failed with oserror if not installed

AC: fix extend import error for soundfile

---

demos/common/python/openvino/model_zoo/model_api/adapters/model_adapter.py
demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py
demos/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py
demos/common/python/openvino/model_zoo/model_api/models/detection_model.py
demos/common/python/openvino/model_zoo/model_api/models/image_model.py
demos/common/python/openvino/model_zoo/model_api/models/model.py

Update the outdated docstrings for abstract classes in Python Model API with the latest state of wrappers. 
Docstrings might be useful for online documentation as well as someone uses `help()` in Python

Python Model API: update docstrings for Model, ImageModel, DetectionModel wrappers

---

tools/accuracy_checker/requirements.in

continuation of https://github.com/openvinotoolkit/open_model_zoo/pull/3408  
This helped to prevent dependency resolution issues that suddenly started to happen in OpenVINO precommits: https://openvino-ci.intel.com/job/private-ci/job/ie/job/e2e-tests-windows-pip-conflicts/26440

Fix imagecodecs version for py>=3.8

---

tools/accuracy_checker/requirements.in

forgot to test it for python 3.9, so previous changes were not enough =(  
continuation of https://github.com/openvinotoolkit/open_model_zoo/pull/3413  
passed run: https://openvino-ci.intel.com/job/private-ci/job/ie/job/e2e-tests-windows-pip-conflicts/26626/console

Fix scikit-image versions

---

demos/action_recognition_demo/python/action_recognition_demo/models.py
demos/action_recognition_demo/python/action_recognition_demo/pipeline.py
demos/action_recognition_demo/python/action_recognition_demo/steps.py
demos/gesture_recognition_demo/python/gesture_recognition_demo/common.py

The PR fixes two separate issues with action_recognition_demo:
- The usage of AsyncInferQueue instead of list of inference requests prevents the demo hanging for both CPU and GPU devices
- Adds the cancelation of all encoder and decoder infer requests before the demo ends. It helps to avoid accidental crashes on CI, when the demo has already finished inference

action_recognition_demo.py: use AsyncInferQueue

---

demos/common/python/openvino/model_zoo/model_api/models/utils.py

Fixing a issue regarding 86756.
This change would enhance numerical stability by preventing NaN output from softmax by shifting input range of exp() input.

 Fix NaN issue for exp() in softmax function

---

demos/common/python/openvino/model_zoo/model_api/models/utils.py

* Improve numerical stability of softmax function implemented by numpy exp().
* Same fix with #3489 which is targeting releases/2022/SCv1.1

Fix NaN issue for exp() in softmax function (for master)

---

models/intel/index.md
models/public/index.md

In the 'public models' and "Intel models' menu sections no additional grouping is necessary, so the models should be sorted alphabetically.

DOCS-sort public models alphabetically

---

models/intel/index.md
models/public/index.md

In the 'public models' and "Intel models' menu sections no additional grouping is necessary, so the models should be sorted alphabetically.

DOCS-sort public models alphabetically-to-22.1

---

data/datasets.md

This PR addresses CVS-86927.
Hyperlinks are not rendered when used as a sole text in headers. 
Additionally, it appears that using nested markdown (backquotes within square brackets in hyperlinks) also is problematic

Fixing headers and links in Datasets.

---

data/datasets.md

This PR addresses CVS-86927.
Hyperlinks are not rendered when used as a sole text in headers.
Additionally, it appears that using nested markdown (backquotes within square brackets in hyperlinks) also is problematic:

Fixing headers in datasets - to master

---

tools/accuracy_checker/requirements.in

there is pip conflict between common OV networkx requirements and upper bound in scikit-image, until it is not solved, explicitly set desired networkx version

requirements: workaround networkx issue

---

demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py

Coordinates of the detected bounding boxes were able to be outside of the input video resolution. So, this request fixes to restrict the coordinates of the bounding boxes within the video resolution.

Fix coordinates range of the detected bounding boxes.

---

tools/accuracy_checker/requirements.in

Accuracy checker is one of the modules in OpenVINO `openvino_dev` package. We are currently working on enabling Python 3.10, which requires a higher version of `SciPy`. Without this change building an `openvino_dev` wheel throws dependency conflict errors.
Motivation:
- `SciPy 1.5.4` has been released on November 04, 2020
- Low `SciPy` version has been mentioned in issues https://github.com/openvinotoolkit/openvino/issues/12735 and https://github.com/openvinotoolkit/openvino/issues/11532
- More about enabling Python 3.10 can be discussed through internal channels

Bump SciPy version requirement in accuracy checker

---

ci/requirements-openvino-dev.in
tools/model_tools/requirements-pytorch.in

OMZ is a thirdparty dependency of OpenVINO. We are currently working on upgrading ONNX to 1.12, which causes the following dependency conflict when building the project:
`The conflict is caused by:
openvino-dev[caffe,kaldi,mxnet,onnx,pytorch,tensorflow2] 2022.3.0.dev20220909 depends on onnx<1.12 and >=1.8.1; extra == "pytorch"
openvino-dev[caffe,kaldi,mxnet,onnx,pytorch,tensorflow2] 2022.3.0.dev20220909 depends on onnx==1.12.0; python_version >= "3.7" and extra == "onnx"`

Bump ONNX to 1.12

---

demos/tests/run_tests.py

Make --downloader-cache-dir not required because there is --models-dir.
Sort args: first by required, second by alphabet.

demos/run_tests.py: update argparser

---

tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/dlsdk_launcher.py
tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py

AC fails with `AttributeError: 'OpenVINOLauncher' object has no attribute '_model'` when running in delayed model loading mode, e.g. when restoring from stored predictions.

AC: Handle delayed model loading in get_model_file_type

---

demos/common/python/requirements.txt
demos/requirements.txt
tools/model_tools/requirements-pytorch.in

There is a mismatch between `scipy` version in OpenVINO and OMZ, which causes pip conflicts in the CI pipelines. We would be thankful for a quick review. 
`scipy==1.5.4` has been released on November 5, 2020.

Bump `scipy` to a higher version

---

tools/accuracy_checker/requirements-extra.in

We need a higher `pandas` version to support Python 3.10.

Relax `pandas` requirement

---

demos/requirements.txt

There is a failing check on Python 3.10 CI at https://github.com/openvinotoolkit/openvino/pull/12578 (e2e-tests-linux-ubuntu20-pip-conflicts).
After a lengthy investigation and reproducing the issue locally, we found that `matplotlib` package is dependent on `pyparsing` and it installs `pyparsing==3.0.9` (through a `pyparsing>=2.2.1` requirement), which is incompatible with other project dependencies.

Limit `pyparsing` module

---

tools/accuracy_checker/openvino/tools/accuracy_checker/utils.py

In this PR https://github.com/openvinotoolkit/openvino/pull/13613 PartialShape to string methods are aligned to return shape of unified format. This format has square brackets. Example:
"[1,3,100,100]"
parse_partial_shape() works only with old format without square brackets. Example:
"1,3,100,100"
In this PR I fix parse_partial_shape() to work with both formats.
Ticket 89901

Fixed parse_partial_shape() to work with aligned shape format.

---

demos/common/python/setup.py

I have checked what it takes to create a PyPi package. We already have setup.py which can generate needed artifacts. We only need to rearrange the folders structure to remove the openvino folder. So if OTX changes their mind and refuses to use OMZ as a submodule, we should be able to publish ModelAPI to PyPi. But I guess we will need to use my personal account instead of Intel’s one for publishing since we won’t follow common processes.

Fix ModelAPI setup.py

---

models/public/quartznet-15x5-en/model.yml

for torch 1.13 model become unreshapable in OV, so convert it to onnx with dynamic axes

quartznet update onnx export command for preserving dynamic shapes

---

demos/face_recognition_demo/python/face_recognition_demo.py

when --input_crop arg is given, it is throwing error with "truth value of an array with more than on element ambiguous". since already there is check for crop_size>0 I I guess .any() should be sufficient.

fix truth value of of numpy array

---

demos/CMakeLists.txt

On gcc-11 and higher armv7 architecture native build fails on demos compilation with the following error:
```
cc1plus: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
```
This patch is intended to fix this issue.
Related patch in OpenVINO: https://github.com/openvinotoolkit/openvino/pull/14832

Fix demos build on armv7

---

models/public/vitstr-small-patch16-224/model.py

in latest torch versions optional integer args are interpreted as input, hide it inside model for avoid wrong input numbers

vitstr: remove second input

---

tools/accuracy_checker/requirements-extra.in

- Update requirements to version which supports Python 3.11 according to PyPI
- 96724

Update scikit-learn in preparation for Python 3.11

---

tools/accuracy_checker/openvino/tools/accuracy_checker/metrics/image_quality_assessment.py

Now 
c1 = 2.4336
c2 = 44.6224
but on [formula](https://en.wikipedia.org/wiki/Structural_similarity)
c1 = (k1 * L)**2
c2 = (k2 * L)**2
And on [opencv.org](https://docs.opencv.org/4.x/d5/dc4/tutorial_video_input_psnr_ssim.html)
```
C1 = 6.5025
C2 = 58.5225
```

[AC]: Fix error on calculate ssim

---

tools/accuracy_checker/openvino/tools/accuracy_checker/adapters/README.md
tools/accuracy_checker/openvino/tools/accuracy_checker/adapters/__init__.py
tools/accuracy_checker/openvino/tools/accuracy_checker/adapters/ssd.py

It's useful for ssdlite_mobilenet_v2 and ssd_mobilenet_v1_coco at least with AC on TF framework
For example:
```
- name:  ssdlite_mobilenet_v2
launchers:
- framework: tf
model: ssdlite_mobilenet_v2_coco_2018_05_09/model.ckpt.meta
output_names:
- detection_classes
- detection_scores
- detection_boxes
- num_detections
inputs:
- name: image_tensor
type: INPUT
shape: 1,300,300,3
adapter:
type: ssd_onnx
scores_out: detection_scores
labels_out: detection_classes
bboxes_out: detection_boxes
diff_coord_order: True
datasets:
- name: ms_coco_detection_91_classes
preprocessing:
- type: bgr_to_rgb
- type: resize
size: 300
postprocessing:
- type: resize_prediction_boxes
metrics:
- type: coco_precision
```
It's strange to use "onnx" adapter for tf model, but looks like it's the simpliest way for now

Add ssd_tf adapter

---

demos/background_subtraction_demo/cpp_gapi/main.cpp

Problem:
This PR fixes a bug with multiple call to the camera:
```
$: ./background_subtraction_demo_gapi -i 0 <other ...>
[ WARN:0@1.229] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.229] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
[ ERROR ] Can't open the camera from 0
```
Solution:
Added reset() for the `ImagesCapture` pointer used to get the size of the first frame.

G-API: Background subtraction. Small fix for camera usage.

---

tools/accuracy_checker/openvino/tools/accuracy_checker/launcher/openvino_launcher.py

There was assumption that all models expect onnx shall have weights file with .bin suffix.

Disable assumption of weights file for TensorFlow models

---

tools/accuracy_checker/requirements-extra.in

The latest available scikit-learn verion for Python3.7 is 1.0.2.
To satisfy Python 3.11 keep scikit-learn>=1.2.0 for Python3.11. See https://github.com/openvinotoolkit/open_model_zoo/pull/3663

Relax scikit-learn version requirement for Python3.7

---

tools/accuracy_checker/requirements-extra.in

`fast-ctc-decode` is not available for Python 3.11, it results in an error when trying to install dependencies on Python 3.11, which is currently being enabled in OpenVINO.
I see that that dependency is not being used anywhere in the code, maybe we could delete it altogether? Its last release was nearly a year ago: https://pypi.org/project/fast-ctc-decode/0.3.2/#history.
cc @eaidova

Disable installing `fast-ctc-decode` for Python 3.11

---

demos/segmentation_demo/cpp/main.cpp

This PR fixes the case where we get `Rendering:      nan(snan) ms` for 1 frame which is rather confusing. With properly updating render metric for leftover frames we get the correct number of frames in `getTotal()` function thus correct metric (`Rendering:      0.6 ms`).

Fix incorrect rendering metric in case of processing 1 frame

---

demos/requirements.txt

There's no Python 3.11 release for `librosa` and `pandas<3.6` doesn't support Python 3.11.

Update dependencies for Python 3.11

---

demos/classification_benchmark_demo/cpp/README.md
demos/classification_benchmark_demo/cpp/main.cpp
demos/common/cpp/models/src/classification_model.cpp
demos/common/cpp/models/src/image_model.cpp
demos/common/cpp/models/src/segmentation_model.cpp
demos/common/cpp/models/src/super_resolution_model.cpp
demos/common/cpp/utils/src/config_factory.cpp
demos/image_processing_demo/cpp/README.md
demos/image_processing_demo/cpp/main.cpp
demos/segmentation_demo/cpp/main.cpp

1) Add `scale/normalization` for some demos in command arguments
2) Enforce segmentation model layout to NCHW conversion

Improve OMZ demos for launching REDOWA models out-of-the-box

---

tools/accuracy_checker/tests/test_preprocessor.py

It seems that now preprocessor.steps is empty. That causes fails in https://github.com/openvinotoolkit/open_model_zoo/pull/3777

AC: remove color_format tests

---

models/public/mobilenet-v3-large-1.0-224-tf/model.yml
models/public/mobilenet-v3-small-1.0-224-tf/model.yml

OpenVINO 2023.0 just got released. `model_api` precommit fails to convert `mobilenet-v3-large-1.0-224-tf` with new OpenVINO

Fix `mobilenet-v3-large-1.0-224-tf` conversion

---

tools/accuracy_checker/requirements-extra.in

To comply with NNCF's upperbound: https://github.com/openvinotoolkit/nncf/blob/a8af39627647ddbb89ef33cf42ff42e9c048b981/setup.py#L106. Pip conflicts checks are failing after the recent Scipy release: https://pypi.org/project/scipy/1.11.0

Restrict scipy module version for Accuracy Checker extras

---

tools/accuracy_checker/openvino/tools/accuracy_checker/postprocessor/README.md
tools/accuracy_checker/openvino/tools/accuracy_checker/postprocessor/extract_answers_tokens.py

Adds 2 parameters for SQuADv2 datasets:
- v2_with_no_answers - enables processing of SQuADv2 dataset questions impossible to answer using no_answer_score_threshold.
- no_answer_score_threshold - gives no answer for sum of start_logit and end_logit predictions below threshold

Enable postprocessing of SQuADv2 datasets with impossible answers

---

demos/3d_segmentation_demo/python/3d_segmentation_demo.py
demos/multi_channel_common/cpp/graph.hpp

brain-tumor-segmentation-0001 produces int64 which triggers `ValueError: Image data has type int64, which may cause incompatibilities with other tools. To use this type, pass an explicit header or dtype argument to Nifti1Image()` We can't even convert in on precommits thus we don't observe the issue. brain-tumor-segmentation-0002 gives uint8.
Ticket 111903

3d_segmentation_demo: fix ValueError

---

demos/interactive_face_detection_demo/cpp_gapi/main.cpp

- There's output wrte limit mistakenly used as an input limit in the G-API IFD demo.
- Also removed an unnecessary capture initialization before the actual start of the pipeline.

Interactive Face Detection (G-API): Fix the input stream limit

---

.github/workflows/accuracy_checker.yml
tools/accuracy_checker/requirements-extra.in
tools/accuracy_checker/setup.py

Drop Python3.7

---

demos/action_recognition_demo/python/action_recognition_demo.py
demos/tests/cases.py

This PR aims to parameterize model device and enable demo tests to run with device other than CPU. 
Scope of impact as below:
- Demo
- `action_recognition_demo.py`  - `encoder_target_device`
- Demo tests
- `gaze_estimation_demo` (both 'cpp_gapi' and 'cpp') - `-d_es`, duplicated PR: #3865
-  `machine_translation_demo` ('python') - `-d`, duplicated PR: #3874

Parameterize model device for demo and tests

---

demos/classification_benchmark_demo/cpp_gapi/classification_benchmark_demo_gapi.hpp
demos/face_detection_mtcnn_demo/cpp_gapi/main.cpp
demos/interactive_face_detection_demo/cpp_gapi/main.cpp

103104
G-API Background Subtraction Demo, Classification Benchmark C++ G-API Demo, G-API Gaze Estimation Demo and other - fail on NPU with the following error: `dynamic shape issues`
```
get_shape was called on a descriptor::Tensor with dynamic shape
```
- OpenVINO is actively removing API 1.0 from their code
- Both G-API framework and G-API demos use API 1.0 --> which leads to disruption of certain functionality
Conclusion: We need to port the G-API demos to API2.0 to make them work.
Passing:
Part 2: https://github.com/openvinotoolkit/open_model_zoo/pull/3887 - WIP

[E-103104] - Port G-API demos to API2.0 - part 1

---

tools/accuracy_checker/accuracy_checker/__init__.py
tools/model_tools/src/omz_tools/_common.py

I'm not going to enforse inclusion of these changes into 24.0, but it's good to have it awnyway

Bump AC version remove deprecated frameworks

---

demos/common/python/model_zoo/__init__.py

Updated `__init__.py` for the demos/common/python/model_zoo package.

Fix for missing model_zoo package.

---

demos/requirements.txt

To resolve conflict between nncf and omz requirements.
There already was such a [PR](https://github.com/openvinotoolkit/open_model_zoo/pull/3890).

remove pyparsing upperbound for 2022.3 LTS

---

demos/common/python/requirements.txt
demos/requirements.txt
tools/accuracy_checker/requirements-core.in

Related story: https://github.com/openvinotoolkit/openvino/pull/24103
**Tickets:**
* [CVS-138838](https://jira.devtools.intel.com/browse/CVS-138838)

[PyOV] Limit numpy to major version

---

demos/speech_recognition_deepspeech_demo/python/asr_utils/profiles.py

It seems MO added :0 to the names for mozilla-deepspeech-0.6.1 and mozilla-deepspeech-0.8.2 despite the fact that the config doesn't have :0: https://github.com/openvinotoolkit/open_model_zoo/blob/828890a839480240467bffc0c4165e37b38719a8/models/public/mozilla-deepspeech-0.6.1/model.yml#L47

demos: fix speech_recognition_deepspeech

---

demos/common/python/model_zoo/model_api/pipelines/async_pipeline.py

In the Python demo, the argument -device can only take AUTO because of the previous bug inside of the async_pipeline.py script. Updated the script so it can handle the device configuration correctly.

Fix plugin bug in object detection demo

---

demos/classification_benchmark_demo/cpp/main.cpp

Ticket: [144363]
Classification Benchmark C++ might crash when classification results list is empty. Fix is to substitute default 'N/A' value in case of empty result.
classification_benchmark_demo

Avoid accessing absent element of the empty container

---

.github/workflows/accuracy_checker.yml
.github/workflows/cpp_gapi-demos.yml
.github/workflows/model_api.yml

Token permissions fix

---

demos/common/cpp/models/src/classification_model.cpp

Use last model layer for benchmarking (do not pick softmax layer, which may be located somewhere in the middle of the model (#147490)
Ticket: [147490]
Description:
Classification Benchmark C++ classification_benchmark_demo provides incorrect classification results for some networks.
Networks affected:
levit-128s
resnest-50-pytorch
swin-tiny-patch4-window7-224
t2t-vit-14
Affected demos:
classification_benchmark_demo

Use last model layer for benchmarking (do not pick softmax layer, which may be located somewhere in the middle of the model (#147490)

---

tools/model_tools/requirements-pytorch.in

`torchvision 0.16`, for some reason preferred by pip on Python 3.8 CI pipelines, is coupled with `torch 2.1.2`, which has vulnerabilities CVE-2024-31580 and CVE-2024-31583.
The new lower bound is compatible with the lowest supported Python version.
Details in CVS-150809

Bump `torchvision` to avoid an unsafe `torch` version

---

tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
tools/accuracy_checker/accuracy_checker/dataset.py
tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py

Correct creation of subset for kaldi dataset and use of coco_orig_metrics with reduced subsets.

Correct subset creation and evaluation

---

tools/model_tools/requirements-tensorflow.in

Details in CVS-151865
Related PR: https://github.com/openvinotoolkit/openvino/pull/26507

Exclude a specific tensorflow version which does not support Python 3.8 on MacOS

---

tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/README.md
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/whisper_evaluator.py

Fix device format for OpenVINO Runtime in whisper evaluator, update Readme.md.

Fix device for OpenVINO Runtime in whisper evaluator

---

tools/accuracy_checker/accuracy_checker/adapters/mask_rcnn.py

Warn and ignore invalid predictions from mask_rcnn adapter causing fail to allocate memory errors

Warn and ignore invalid predictions from mask_rcnn adapter

---

tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/base_custom_evaluator.py
tools/accuracy_checker/accuracy_checker/evaluators/custom_evaluators/openvino_clip_evaluator.py

Extend openvino_clip_evaluator to allow validation of both jina-clip from huggingface and openvino converted model.

Add jina-clip evaluator

---

tools/accuracy_checker/accuracy_checker/preprocessor/crop.py

Usage of numpy.math is not supported in numpy2

Use math instead of numpy.math

---

tools/accuracy_checker/accuracy_checker/adapters/README.md
tools/accuracy_checker/accuracy_checker/adapters/reidentification.py

Correct validation of bert-base-multilingual-cased with STS-B dataset

Mean pooling for last hidden state

---

tools/accuracy_checker/setup.py

Current kenlm sha/version seems to look for some older cmake, and is failing our builds:
```
19:31:05  Building wheels for collected packages: kenlm
19:31:05    Building wheel for kenlm (pyproject.toml): started
19:31:05    Building wheel for kenlm (pyproject.toml): finished with status 'error'
19:31:05    error: subprocess-exited-with-error
19:31:05    
19:31:05    × Building wheel for kenlm (pyproject.toml) did not run successfully.
19:31:05    │ exit code: 1
19:31:05    ╰─> [65 lines of output]
19:31:05        Will build with KenLM max_order set to 6
19:31:05        running bdist_wheel
19:31:05        running build
19:31:05        running build_ext
19:31:05        CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
19:31:05          Compatibility with CMake < 3.5 has been removed …
```

[accuracy checker] Update kenlm sha

---

demos/requirements.txt

It currently discards prebuilt wheels and fails to build from source. This PR forces pip to use prebuilt version
```bash
[2025-09-17T09:05:51.571Z] [2025-09-17 11:05:51,471] [16452] helper.cmd_exec INFO: Collecting scikit-learn>=0.24.1 (from -r c:\jenkins\workspace\private-ci\ie\e2e-tests-windows-pip-conflicts\b\install\dldt_cpack\extras\open_model_zoo\demos\requirements.txt (line 10))
[2025-09-17T09:05:51.571Z] [2025-09-17 11:05:51,488] [16452] helper.cmd_exec INFO:   Using cached scikit_learn-1.7.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
[2025-09-17T09:05:52.532Z] [2025-09-17 11:05:52,162] [16452] helper.cmd_exec INFO:   Downloading scikit_learn-1.7.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
[2025-09-17T09:05:53.120Z] [2025-09-17 11:05:52,798] [16452] helper.cmd_exec INFO: …
```

Force pip to choose prebuilt wheel for Python 3.13 scikit-learn
